'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {Budget,defaults,dateKey,shiftMonth}=require('../src/main/budget');
const handbook=require('../src/renderer/panel/budget-handbook'),brands=require('../src/renderer/panel/budget-brands');
function setup(){let saved=defaults();const b=new Budget({get:()=>saved,set:v=>saved=structuredClone(v)}),bank=b.act('account',{name:'Banka',type:'bank',currency:'TRY',opening:'50000'});return {b,bank};}
const clock=(hour,minute=0)=>new Date(2026,9,6,hour,minute);
function subscription(b,bank,extra={}){return b.act('plan',{name:'Netflix',type:'expense',amount:'150',accountId:bank.id,categoryId:'expense-0',start:'2026-01-31',frequency:'monthly',brandId:'netflix',...extra});}
test('Otomatik abonelik ay sonunu korur, kapalı dönemleri yakalar ve çift kayıt üretmez',()=>{
 const {b,bank}=setup(),p=subscription(b,bank,{auto:true});assert.equal(b.autoPost('2026-03-31').posted,3);assert.equal(b.autoPost('2026-03-31').posted,0);assert.deepEqual(b.state.transactions.map(t=>t.date),['2026-01-31','2026-02-28','2026-03-31']);assert.equal(b.accountBalance(bank.id,'2026-03-31'),4955000);assert.ok(b.state.transactions.every(t=>t.brandId==='netflix'));b.act('pausePlan',{id:p.id});assert.equal(b.autoPost('2026-04-30').posted,0);
});
test('Yanlış otomatik ödemeyi geri alma bakiyeyi düzeltir ve yeniden otomatik yazmaz',()=>{
 const {b,bank}=setup(),p=subscription(b,bank,{auto:true});b.autoPost('2026-01-31');const t=b.state.transactions[0];b.act('unpay',{planId:p.id,occurrence:'2026-01-31'});assert.equal(b.accountBalance(bank.id,'2026-01-31'),5000000);assert.equal(b.autoPost('2026-01-31').posted,0);assert.equal(b.occurrences('2026-01-31','2026-01-31').length,1);b.act('pay',{planId:p.id,occurrence:'2026-01-31'});assert.equal(b.accountBalance(bank.id,'2026-01-31'),4985000);assert.throws(()=>b.act('undo',{id:t.id}),/tekrar/);
});
test('Abonelik fiyat değişimi yalnız yürürlük tarihinden sonraki kayıtlara uygulanır',()=>{
 const {b,bank}=setup(),p=subscription(b,bank,{auto:true});b.autoPost('2026-02-28');b.act('revisePlan',{id:p.id,amount:'200',effective:'2026-03-01',auto:true});b.autoPost('2026-03-31');assert.deepEqual(b.state.transactions.map(t=>t.amount),[15000,15000,20000]);assert.throws(()=>b.act('revisePlan',{id:p.id,amount:'250',effective:'2026-02-01'}));const restored=new Budget({get:()=>b.export(),set:()=>{}});assert.equal(restored.occurrences('2026-04-30','2026-04-30')[0].amount,20000);
});
test('Beklenen maaş banka bakiyesine onaylanmadan girmez; otomatik seçilmişse tarihinde girer',()=>{
 const {b,bank}=setup();const p=b.act('scheduleTransaction',{status:'planned',repeat:true,auto:true,type:'income',accountId:bank.id,categoryId:'income-0',amount:'30000',date:'2026-10-21',frequency:'monthly',payee:'Maaş'});assert.equal(b.autoPost('2026-10-20').posted,0);assert.equal(b.cashFlow('2026-10','2026-10-20').expected,3000000);assert.equal(b.accountBalance(bank.id,'2026-10-20'),5000000);assert.equal(b.autoPost('2026-10-21').posted,1);assert.equal(b.accountBalance(bank.id,'2026-10-21'),8000000);assert.equal(b.cashFlow('2026-10','2026-10-21').expected,0);assert.equal(b.state.transactions[0].planId,p.id);
});
test('Mevcut para, toplam taksit borcu, bu ayın ödeme yükü ve gider ayrı kalır',()=>{
 const {b,bank}=setup(),card=b.act('account',{name:'Kart',type:'credit',currency:'TRY',opening:'0',cutDay:10,dueDay:20,limit:'100000'});const p=b.act('plan',{name:'Bilgisayar',type:'expense',accountId:card.id,fundingAccountId:bank.id,categoryId:'expense-0',amount:'60000',start:'2026-10-20',purchaseDate:'2026-10-01',frequency:'monthly',installments:6});let f=b.cashFlow('2026-10','2026-10-06');assert.equal(f.available,5000000);assert.equal(f.installmentDebt,6000000);assert.equal(f.payable,1000000);assert.equal(f.afterPayments,4000000);assert.equal(b.summary('2026-10-01','2026-10-31').netExpense,6000000);assert.equal(b.cardStatement(card,'2026-10-11').estimatedDue,1000000);
 b.act('pay',{planId:p.id,occurrence:'2026-10-20',date:'2026-10-20'});f=b.cashFlow('2026-10','2026-10-21');assert.equal(f.available,4000000);assert.equal(f.installmentDebt,5000000);assert.equal(f.payable,0);assert.equal(b.summary('2026-10-01','2026-10-31').netExpense,6000000);assert.equal(b.installmentDetails('2026-10-21')[0].paidCount,1);b.act('unpay',{planId:p.id,occurrence:'2026-10-20'});assert.equal(b.accountBalance(bank.id,'2026-10-21'),5000000);assert.equal(b.installmentDetails()[0].remaining,6000000);
});
test('Kendi nakit/banka hesapları arası planlanan transfer harcama veya beklenen gelir değildir',()=>{
 const {b,bank}=setup(),cash=b.act('account',{name:'Cüzdan',type:'cash',opening:'0'});b.act('plan',{name:'Nakit çek',type:'transfer',accountId:bank.id,toAccountId:cash.id,amount:'1000',start:'2026-10-21',frequency:'once'});const f=b.cashFlow('2026-10','2026-10-06');assert.equal(f.expected,0);assert.equal(f.payable,0);
});
test('Bildirim 7 gün, 1 gün ve aynı gün için seçilen saatten sonra birer kez gelir',()=>{
 const {b,bank}=setup(),p=subscription(b,bank,{start:'2026-10-21',frequency:'once'});b.act('notificationSettings',{enabled:true,days:[7,1,0],time:'17:30'});assert.equal(b.reminders('2026-10-14',clock(17,29)).length,0);assert.equal(b.reminders('2026-10-14',clock(17,30))[0].lead,7);assert.equal(b.reminders('2026-10-14',clock(18)).length,0);assert.equal(b.reminders('2026-10-20',clock(18))[0].lead,1);assert.equal(b.reminders('2026-10-21',clock(18))[0].lead,0);assert.equal(b.reminders('2026-10-21',clock(19)).length,0);b.act('pay',{planId:p.id,occurrence:'2026-10-21'});assert.equal(b.reminders('2026-10-21',clock(19)).length,0);
});
test('Bildirim takvim günü hesabında artık yıl ve ay sınırını doğru geçer; kapalı tercihi uygulanır',()=>{
 const {b,bank}=setup();subscription(b,bank,{start:'2028-03-01',frequency:'once'});b.act('notificationSettings',{enabled:true,days:[7,1,0],time:'00:00'});assert.equal(b.reminders('2028-02-23',clock(1))[0].lead,7);assert.equal(b.reminders('2028-02-29',clock(1))[0].lead,1);b.act('notificationSettings',{enabled:false,days:[0],time:'00:00'});assert.equal(b.reminders('2028-03-01',clock(1)).length,0);assert.throws(()=>b.act('notificationSettings',{enabled:true,days:[2],time:'09:00'}));assert.throws(()=>b.act('notificationSettings',{enabled:true,days:[0],time:'25:00'}));
});
test('Yaklaşan kayıtlar yalnız güncel ve sonraki ay; takvim seçilen ay ve gecikmeler ayrı',()=>{
 const {b,bank}=setup(),today=dateKey(),current=today.slice(0,7),next=shiftMonth(current+'-01',1).slice(0,7),later=shiftMonth(current+'-01',2).slice(0,7);subscription(b,bank,{start:shiftMonth(current+'-01',-1),frequency:'monthly'});subscription(b,bank,{start:later+'-01',frequency:'once'});const v=b.view(later);assert.ok(v.upcoming.every(o=>[current,next].includes(o.date.slice(0,7))));assert.ok(v.overdue.every(o=>o.date<current+'-01'));assert.ok(v.calendar.every(o=>o.date.startsWith(later)));
});
test('Üç finans teması ve yazı boyutu bağımsız değişir, yedekten geri gelir',()=>{
 const {b}=setup();b.act('preferences',{financeTheme:'nero'});b.act('preferences',{textSize:'large'});assert.equal(b.view().preferences.financeTheme,'nero');const c=new Budget({get:()=>b.export(),set:()=>{}});assert.equal(c.view().preferences.textSize,'large');c.act('preferences',{financeTheme:'modern'});assert.equal(c.view().preferences.textSize,'large');c.act('preferences',{financeTheme:'cards'});const restored=new Budget({get:()=>c.export(),set:()=>{}});assert.equal(restored.view().preferences.financeTheme,'cards');assert.equal(restored.view().preferences.textSize,'large');assert.throws(()=>c.act('preferences',{financeTheme:'unknown'}));
});
test('94 ders 14 modülde tam kapsanır; quiz cevabı, kaldığın yer ve kaynaklar tutarlı',()=>{
 assert.equal(handbook.chapters.length,94);assert.equal(handbook.modules.length,14);const ids=handbook.modules.flatMap(m=>m.chapters);assert.equal(new Set(ids).size,94);assert.equal(ids.length,94);for(const c of handbook.chapters){assert.equal(c.quiz.options.length,3);assert.ok(c.quiz.correct>=0&&c.quiz.correct<3);assert.ok(c.quiz.explanation.length>40);assert.ok(c.outcomes.length>=2);assert.ok(c.sections.every(s=>s.text.length>100));for(const source of c.sources)assert.ok(handbook.sources[source]);}
 const {b}=setup(),c=handbook.chapters[0];b.act('quiz',{id:c.id,answer:(c.quiz.correct+1)%3});assert.equal(b.view().learning.answers[c.id].correct,false);b.act('quiz',{id:c.id,answer:c.quiz.correct});b.act('resumeLesson',{id:c.id});const restored=new Budget({get:()=>b.export(),set:()=>{}});assert.equal(restored.view().learning.last,c.id);assert.equal(restored.view().learning.answers[c.id].correct,true);assert.throws(()=>b.act('quiz',{id:c.id,answer:4}));
});
test('100 çevrimdışı marka ikonu yüklenebilir; Netflix, YouTube ve ChatGPT otomatik tanınır',()=>{
 assert.equal(brands.brands.length,100);assert.equal(new Set(brands.brands.map(b=>b.id)).size,100);for(const b of brands.brands){const svg=fs.readFileSync(path.join(__dirname,'../src/renderer/panel/brands',b.id+'.svg'),'utf8');assert.match(svg,/<svg/);assert.doesNotMatch(svg,/<script|onload=|<foreignObject|href="https?:/i);assert.ok(b.source.startsWith('https://'));}assert.equal(brands.detect('Netflix aylık').id,'netflix');assert.equal(brands.detect('YouTube Premium').id,'youtube');assert.equal(brands.detect('ChatGPT Plus').id,'openai');
});
test('Bozuk tema/quiz/plan yedeği mevcut kayıtları değiştirmeden reddedilir',()=>{
 const {b}=setup(),before=b.export();for(const bad of [s=>s.preferences.financeTheme='bad',s=>s.learning.answers={'money-map':{answer:9,correct:true}},s=>s.notifications.time='24:59']){const invalid=structuredClone(before);bad(invalid);assert.throws(()=>b.replace(invalid));assert.deepEqual(b.export(),before);}
});
test('İleri tarihli gelir/gider güncel bakiyeyi ve gerçekleşmiş özeti değiştirmez, projeksiyonda görünür',()=>{
 const {b,bank}=setup(),future=shiftMonth(dateKey().slice(0,7)+'-01',1),month=future.slice(0,7);b.act('transaction',{type:'income',accountId:bank.id,categoryId:'income-0',amount:'30000',date:future});b.act('transaction',{type:'expense',accountId:bank.id,categoryId:'expense-0',amount:'1000',date:future});b.act('budget',{month,categoryId:'all',amount:'5000'});const v=b.view(month);assert.equal(v.summary.income,0);assert.equal(v.summary.netExpense,0);assert.equal(v.cashFlow.available,5000000);assert.equal(v.cashFlow.expected,3000000);assert.equal(v.cashFlow.payable,100000);assert.equal(v.budgets[0].spent,0);
});
test('İleri tarihli taksit kaydı gerçekleşmeden toplam borcu ve nakdi düşürmez',()=>{
 const {b,bank}=setup(),card=b.act('account',{name:'Kart',type:'credit',opening:'0'}),purchase=dateKey(),future=shiftMonth(purchase,1);const p=b.act('plan',{name:'Taksit',type:'expense',accountId:card.id,fundingAccountId:bank.id,categoryId:'expense-0',amount:'6000',start:future,purchaseDate:purchase,frequency:'monthly',installments:6});b.act('pay',{planId:p.id,occurrence:future,date:future});assert.equal(b.installmentDetails(purchase)[0].paidCount,0);assert.equal(b.installmentDetails(purchase)[0].remaining,600000);assert.equal(b.cashFlow(future.slice(0,7),purchase).payable,100000);assert.equal(b.cashFlow(future.slice(0,7),purchase).available,5000000);assert.equal(b.installmentDetails(future)[0].remaining,500000);
});
