const test=require('node:test'),assert=require('node:assert/strict');const {Productivity,checklist}=require('../src/main/productivity');const {Timer}=require('../src/main/timer');const {Budget,defaults}=require('../src/main/budget');
const memory=data=>({data,get(){return this.data;},set(next){this.data=next;}});
test('Note checklists count checked rows without treating normal text as tasks',()=>{assert.deepEqual(checklist('Başlık\n- [x] A\n- [ ] B\nMetin').tasks.map(t=>t.done),[true,false]);assert.equal(checklist('normal [x] text').total,0);});
function fixture(){const store=memory({sessions:[],preferences:{}}),notes=memory([{id:'n',body:'Not'}]),todos=memory([{id:'t',text:'İş',bucket:'today'}]),jar=memory({items:[{id:'a',text:'A'},{id:'b',text:'B'},{id:'c',text:'C'}]}),timer=new Timer(),p=new Productivity({store,notes,todos,jar,timer});return {p,store,notes,todos,jar,timer};}
test('Note metadata preserves body; invalid colors fail',()=>{const f=fixture();f.p.meta('note',{id:'n',pinned:true,tag:'İş',color:'blue'});assert.equal(f.notes.get()[0].body,'Not');assert.equal(f.notes.get()[0].pinned,true);assert.throws(()=>f.p.meta('note',{id:'n',color:'invalid'}));});
test('Todo grouping and priority persist and malformed reorders fail',()=>{const f=fixture();f.p.meta('todo',{id:'t',bucket:'later',priority:'high',plannedDurationMin:45});assert.equal(f.todos.get()[0].plannedDurationMin,45);assert.throws(()=>f.p.prepare('t'));assert.throws(()=>f.p.reorder(['missing'],'today'));assert.throws(()=>f.p.reorder(['t','t'],'today'));});
test('Memory cycle survives restart and avoids immediate repeat at cycle boundary',()=>{const f=fixture(),seen=new Set();let last;for(let i=0;i<3;i++){last=f.p.randomMemory();seen.add(last.id);}assert.equal(seen.size,3);const p=new Productivity({...f,changed:()=>{}});assert.notEqual(p.randomMemory().id,last.id);});
test('Paused focus does not credit time twice; linked completed focus credits the correct task',()=>{const f=fixture();f.p.prepare('t');f.timer.start(5,'İş');f.timer.endsAt-=60000;f.timer.pause();const elapsed=f.p.current.elapsedMs;assert.ok(elapsed>=60000&&elapsed<61000);f.timer.resume();f.timer._stopLoop();f.timer._reset();f.timer.emit('done',{minutes:5});assert.equal(f.todos.get()[0].actualDurationMs,300000);assert.equal(f.store.get().sessions[0].status,'completed');assert.equal(f.store.get().sessions[0].todoId,'t');});
test('Cancelled focus credits only active elapsed time',()=>{const f=fixture();f.p.prepare('t');f.timer.start(5);f.timer.endsAt-=90000;f.timer.pause();f.timer.cancel();assert.ok(f.todos.get()[0].actualDurationMs>=90000&&f.todos.get()[0].actualDurationMs<91000);assert.equal(f.store.get().sessions[0].status,'cancelled');});
function budget(){const b=new Budget(memory(defaults()));const a=b.act('account',{name:'Banka',type:'bank',currency:'TRY',opening:'1000'});const p=b.act('plan',{name:'Fatura',type:'expense',accountId:a.id,categoryId:'expense-0',amount:'100',start:'2026-10-07',frequency:'monthly'});return {b,a,p};}
test('Partial payment keeps remaining obligation and accounts only actual payments',()=>{const {b,a,p}=budget();b.act('partialPay',{planId:p.id,occurrence:'2026-10-07',amount:'40',date:'2026-10-07'});assert.equal(b.occurrences('2026-10-07','2026-10-07')[0].amount,6000);assert.equal(b.accountBalance(a.id,'2026-10-07'),96000);assert.throws(()=>b.act('partialPay',{planId:p.id,occurrence:'2026-10-07',amount:'61'}));b.act('partialPay',{planId:p.id,occurrence:'2026-10-07',amount:'60',date:'2026-10-07'});assert.equal(b.occurrences('2026-10-07','2026-10-07').length,0);assert.equal(b.accountBalance(a.id,'2026-10-07'),90000);const restored=new Budget(memory(b.export()));assert.equal(restored.accountBalance(a.id,'2026-10-07'),90000);});
test('Single occurrence revisions preserve future amounts and paid history',()=>{const {b,p}=budget();b.act('editOccurrence',{planId:p.id,occurrence:'2026-10-07',amount:'120',scope:'one'});const rows=b.occurrences('2026-10-01','2026-11-30');assert.equal(rows[0].amount,12000);assert.equal(rows[1].amount,10000);});
test('Report preferences round-trip through budget backup',()=>{const {b}=budget();b.act('reportSettings',{from:'2026-10-01',to:'2026-10-31',account:'all'});assert.equal(new Budget(memory(b.export())).state.preferences.reportSettings.from,'2026-10-01');assert.throws(()=>b.act('reportSettings',{from:'2026-11-01',to:'2026-10-01'}));});
test('Nero loses normal happiness when unattended, but sleeping does not count as neglect',()=>{const {Mood}=require('../src/main/mood');const m=new Mood(memory({happiness:65,ignoredMs:0}));for(let i=0;i<180;i++)m.tick(60000,0);assert.ok(m.state.happiness<60);const before=m.state.happiness,ignored=m.state.ignoredMs;m.tick(3600000,1000);assert.equal(m.state.happiness,before);assert.equal(m.state.ignoredMs,ignored);m.interact('pet');assert.ok(m.state.happiness>before);});
test('Undo partial payments restores exact account balance and obligation',()=>{const {b,a,p}=budget();b.act('partialPay',{planId:p.id,occurrence:'2026-10-07',amount:'40',date:'2026-10-07'});b.act('unpay',{planId:p.id,occurrence:'2026-10-07'});assert.equal(b.accountBalance(a.id,'2026-10-07'),100000);assert.equal(b.occurrences('2026-10-07','2026-10-07')[0].amount,10000);});
test('Variable invoice changes this occurrence only; editing paid periods fails atomically',()=>{const {b,p}=budget();b.act('partialPay',{planId:p.id,occurrence:'2026-10-07',amount:'120',date:'2026-10-07',variable:true});assert.equal(b.occurrences('2026-11-07','2026-11-07')[0].amount,10000);const saved=JSON.stringify(b.export());assert.throws(()=>b.act('editOccurrence',{planId:p.id,occurrence:'2026-10-07',scope:'future',amount:'90'}));assert.equal(JSON.stringify(b.export()),saved);});
