import {nauticalFactories as N} from '../restaurant/nautical-stations.js';
import {krabsCleaner} from '../restaurant/staff-prototypes.js';
import React,{useEffect,useState,useSyncExternalStore} from 'react';
import {createRoot} from 'react-dom/client';
import {foodThumbnail,modelThumbnail} from '../restaurant/menu-thumbnails.js';
import * as B from '../restaurant/models-v2.js';
import * as K from '../restaurant/kitchen-models.js';
const money=n=>Number(n||0).toLocaleString('tr-TR',{maximumFractionDigits:2});
const names={orders:'Siparişler',kitchen:'Mutfak',recipes:'Tarifler',storage:'Depo',research:'Araştırmalar',team:'Ekip'};
function Icon({name}){const slots={orders:0,kitchen:1,recipes:2,storage:3,team:4,coin:5,compass:7,crab:8};if(name in slots){const n=slots[name];return <span aria-hidden="true" className="hud-icon hud-sprite" style={{backgroundPosition:(n%3)*50+'% '+Math.floor(n/3)*50+'%'}}/>;}const shapes={
 research:<><path d="M14 9h33v47H14q-6 0-6-6V15q0-6 6-6Z" fill="#8253a9"/><path d="M15 9v47m5-5h24" stroke="#eec775" strokeWidth="3"/><path d="M30 15h14m-11 1v12L23 44q-2 6 5 6h22q7 0 4-6L42 28V16" fill="#b8eeee" stroke="#35566b" strokeWidth="2"/><path d="M29 35h19l6 10q2 5-5 5H29q-8 0-5-6Z" fill="#36bbbd"/><circle cx="36" cy="39" r="2.5" fill="#efffe2"/><circle cx="43" cy="45" r="2" fill="#efffe2"/><path d="m53 6 2 4 4 2-4 2-2 4-2-4-4-2 4-2Z" fill="#ffd264"/></>,
 coin:<><circle cx="32" cy="32" r="25" fill="url(#gold)"/><circle cx="32" cy="32" r="20" fill="none" stroke="#ffedac" strokeWidth="3"/><path d="m32 16 5 10 11 2-8 8 2 11-10-5-10 5 2-11-8-8 11-2Z" fill="#fff1b0"/></>,
 orders:<><path d="M13 43c5-4 5-8 6-17a13 13 0 0 1 26 0c1 9 1 13 6 17Z" fill="url(#gold)"/><path d="M11 44h42v6H11Z" fill="#e9a128"/><ellipse cx="32" cy="52" rx="8" ry="4" fill="#af7629"/><circle cx="32" cy="11" r="4" fill="#f4c451"/><path d="M24 21q-4 6-4 15" fill="none" stroke="#fff0b3" strokeWidth="3"/></>,
 kitchen:<><path d="M4 31q0-19 19-19t19 19Z" fill="url(#gold)"/><path d="M5 32h37v6H5Z" fill="#78a944"/><path d="M4 39h38v7H4Z" fill="#85492c"/><path d="M6 47h34q-2 9-17 9T6 47" fill="#eaa24d"/><path d="m46 38 6-23" stroke="#55777c" strokeWidth="5"/><path d="m48 5 13 4-4 14-13-4Z" fill="#ccd7d5"/><path d="m49 9-2 8m7-7-2 8m6-7-2 8" stroke="#5c777a" strokeWidth="2"/></>,
 recipes:<><path d="M13 6h35l4 4v46H15q-6 0-6-6V12q0-6 4-6" fill="#c55d47"/><path d="M16 6v50M21 49h24" stroke="#f9d693" strokeWidth="3"/><circle cx="34" cy="19" r="3" fill="#f9d693"/><path d="M34 22v17m-9-9q0 12 9 9 9 3 9-9m-14-5h10" stroke="#f9d693" strokeWidth="3" fill="none"/></>,
 storage:<><path d="m8 15 24-9 24 9v36L32 59 8 50Z" fill="#c68b4a"/><path d="m8 15 24 10 24-10M32 25v34" stroke="#805c37" strokeWidth="3"/><path d="m13 25 13 5m-13 7 13 5m12-12 12-5m-12 17 12-5M17 19v32m28-32v32" stroke="#efd19c" strokeWidth="3"/></>,
 team:<><ellipse cx="43" cy="31" rx="13" ry="23" fill="#eab552"/><ellipse cx="21" cy="34" rx="14" ry="23" fill="#5eb5cf"/><path d="M8 44h26v14H8Zm27-3h21v15H35Z" fill="#4d83ac"/><circle cx="20" cy="24" r="5" fill="white"/><circle cx="29" cy="24" r="5" fill="white"/><circle cx="43" cy="19" r="5" fill="white"/><circle cx="51" cy="19" r="5" fill="white"/><path d="M23 24h2m20-5h2m-30 17q7 5 12 0m10-8q6 4 11-1" stroke="#264859" strokeWidth="3" fill="none"/></>,
 home:<><path d="m7 29 25-22 25 22-5 5-20-17-20 17Z" fill="#2d7184"/><path d="M16 30h32v26H16Z" fill="#44949a"/><path d="M27 39h11v17H27Z" fill="#fff3d3"/></>,
 compass:<><circle cx="32" cy="32" r="24" fill="#d9f1e8" stroke="#a5c5bc" strokeWidth="3"/><path d="m44 12-6 27-21 13 7-28Z" fill="#309eaf"/><path d="m44 12-20 12 14 15Z" fill="#f5d390"/></>,
 crab:<><ellipse cx="32" cy="35" rx="16" ry="13" fill="#db694b"/><circle cx="24" cy="19" r="7" fill="#f58561"/><circle cx="39" cy="19" r="7" fill="#f58561"/><path d="m18 35-10-8m38 8 10-8M18 44l-9 9m37-9 9 9" stroke="#cb6046" strokeWidth="5"/><circle cx="8" cy="21" r="8" fill="#ed825b"/><circle cx="56" cy="21" r="8" fill="#ed825b"/><circle cx="25" cy="18" r="3" fill="white"/><circle cx="38" cy="18" r="3" fill="white"/></>,
 settings:<><path d="m26 6 12 0 2 9 8 4 9-2 6 10-7 6-1 9 5 7-9 9-9-5-8 1-5 8-12-4v-9l-6-6-9-1-1-12 8-5 2-8-3-8 10-7Z" transform="translate(3 1) scale(.88)" fill="#347c89"/><circle cx="32" cy="32" r="10" fill="#fff4d6"/></>};return <svg viewBox="0 0 64 64" className="hud-icon" aria-hidden="true"><defs><linearGradient id="gold" x2="0" y2="1"><stop stopColor="#ffe796"/><stop offset=".55" stopColor="#ffc44b"/><stop offset="1" stopColor="#d69831"/></linearGradient></defs>{shapes[name]||shapes.team}</svg>;}
const machines={burger:N.burger,soda:N.soda,'hot-drink':N.coffee,juice:N.juice,shake:N.shake,oven:N.oven,fryer:N.fryer,hotdog:N.hotdog,'cold-prep':N['cold-prep'],dessert:N.dessert,icecream:N.icecream,'soup-pasta-extra':N.soup};
const photo=(m)=>foodThumbnail(m.modelId);
export function mountGameHud(service){let snapshot=service.snapshot();const listeners=new Set();const store={subscribe:f=>{listeners.add(f);return()=>listeners.delete(f);},get:()=>snapshot};createRoot(document.getElementById('game-ui')).render(<Hud service={service} store={store}/>);return s=>{snapshot=s;listeners.forEach(f=>f());};}
function Hud({service,store}){const s=useSyncExternalStore(store.subscribe,store.get),[sheet,setSheet]=useState(null),[ordersPinned,setOrdersPinned]=useState(false),[category,setCategory]=useState('all'),[researchFilter,setResearchFilter]=useState('available'),[researchPage,setResearchPage]=useState(0),[role,setRole]=useState('Servis'),[amounts,setAmounts]=useState({}),[notice,setNotice]=useState(''),[detail,setDetail]=useState(null),[views,setViews]=useState(false),[paused,setPaused]=useState(false),[clock,setClock]=useState('Gün 1 · 09:00'),[page,setPage]=useState(0);
useEffect(()=>{const listener=e=>setSheet(e.detail);window.addEventListener('hud-sheet',listener);const outside=e=>{const popup=document.querySelector('.hud-detail')||document.querySelector('.hud-popup')||document.querySelector('.hud-view-menu');if(popup&&!popup.contains(e.target)&&!e.target.closest('.hud-dock')){if(ordersPinned&&sheet==='orders'&&popup.classList.contains('orders'))return;e.preventDefault();e.stopPropagation();setSheet(null);setDetail(null);setViews(false);service.selectStation(null);}};document.addEventListener('pointerdown',outside,true);const esc=e=>{if(e.key==='Escape'){setSheet(null);setDetail(null);service.selectStation(null);}};window.addEventListener('keydown',esc);const timer=setInterval(()=>setClock(document.getElementById('game-clock')?.textContent||''),1000);return()=>{clearInterval(timer);document.removeEventListener('pointerdown',outside,true);window.removeEventListener('hud-sheet',listener);window.removeEventListener('keydown',esc);};},[ordersPinned,sheet]);
const chooseView=v=>{window.__neroRestaurantLayout?.view(v);setViews(false);};const stationKey=s.selectedStation;const selected=stationKey?s.menu[stationKey]:null;const st=stationKey?s.stations[stationKey]:null;
const inspect=k=>{setDetail(k);service.selectStation(k);};const closeDetail=()=>{setDetail(null);service.selectStation(null);};
const researchRows=Object.entries(s.menu).filter(([,m])=>s.research.policies[m.modelId]);
const activeResearchIds=new Set(s.research.jobs.map(j=>j.id));
const researchList=researchRows.filter(([k,m])=>!activeResearchIds.has(m.modelId)&&(researchFilter==='completed'?s.stations[k].unlocked:researchFilter==='locked'?!s.stations[k].unlocked&&!service.unlockConditions(k).allowed:!s.stations[k].unlocked&&service.unlockConditions(k).allowed));
const researchTitle=id=>Object.values(s.menu).find(m=>m.modelId===id)?.name||id;
const durationLabel=seconds=>Math.floor(seconds/60)+' dk '+Math.ceil(seconds%60)+' sn';
const startResearch=k=>{const result=service.unlockProduct(k);setNotice(result?'Araştırma başladı. Tarif tamamlanınca açılacak.':'Araştırma başlatılamadı. Seviye, önceki tarif, altın ve boş araştırma yerini kontrol et.');};
const ingredients=s.inventory.materials.filter(m=>m.unlocked);const total=ingredients.reduce((a,m)=>a+(amounts[m.id]||0)*m.unitGold,0);
const order=()=>{const r=service.orderSupplies(Object.fromEntries(Object.entries(amounts).filter(([,n])=>n>0)));setNotice(r.allowed?'Sipariş verildi. Malzemeler yolda.':r.reason==='gold'?'Yeterli altın yok.':r.reason==='capacity'?'Depoda yeterli yer yok.':'Bir malzeme adedi seç.');if(r.allowed)setAmounts({});};
return <div className="hud">
<header className="hud-top"><div className="hud-brand"><Icon name="crab"/><b>Ezgi’s Krab Shack</b></div><span className="hud-clock">{clock}</span><div className="hud-currency"><Icon name="coin"/><strong>{money(s.gold)}</strong></div><div className="hud-level"><b>Sv. {s.level}</b><div><progress value={s.xp} max={s.nextLevelXP}/><small>{s.xp} / {s.nextLevelXP} XP</small></div></div><button className="hud-round settings" title="Oyun seçenekleri" onClick={()=>setViews(!views)}><Icon name="settings"/></button></header>
<section className="hud-quests">{s.quests.active.map(q=><article key={q.id} className={'hud-quest '+(q.ready?'ready':'')}><div className="quest-picture">{q.productId?<img src={foodThumbnail(q.productId)} alt=""/>:<Icon name="team"/>}</div><div><strong>{q.productId?q.title.split(' · ')[0]:q.target+' müşteri ağırla'}</strong><progress value={q.progress} max={q.target}/><small>{q.progress} / {q.target}</small></div><button disabled={!q.ready} onClick={()=>service.claimQuest(q.id)} title={q.ready?'Ödülü al':'Görev ödülü'}><Icon name="coin"/><span>{q.ready?'Al · ':''}{q.reward}</span></button></article>)}</section>
<nav className="hud-dock">{Object.entries(names).map(([key,label])=><button key={key} aria-pressed={sheet===key} onClick={()=>{setSheet(sheet===key?null:key);closeDetail();}}><Icon name={key}/><span>{label}</span>{key==='orders'&&s.orders.length>0&&<b className="hud-badge">{s.orders.length}</b>}{key==='research'&&s.research.jobs.length>0&&<b className="hud-badge">{s.research.jobs.length}</b>}</button>)}</nav>
<div className="hud-camera"><button className="hud-round" onClick={()=>chooseView('interior')} title="Dükkâna dön"><Icon name="home"/></button><button className="hud-round" onClick={()=>setViews(!views)} title="Şehri gez"><Icon name="compass"/></button></div>
{views&&<div className="hud-view-menu">{Object.entries({interior:'Restoran',town:'Conch Street',traffic:'Yollar',overview:'Tüm şehir',kitchen:'Mutfak'}).map(([k,n])=><button key={k} onClick={()=>chooseView(k)}>{n}</button>)}<button onClick={()=>{window.__neroRestaurantLayout?.setMotion(paused);setPaused(!paused);}}>{paused?'Devam et':'Duraklat'}</button></div>}
{sheet&&<><div className={'hud-scrim '+(sheet==='orders'?'quiet':'')} onClick={()=>{if(sheet!=='orders'||!ordersPinned)setSheet(null);}}/><section className={'hud-popup '+(sheet==='orders'?'orders':'')} role="dialog" aria-label={names[sheet]}><div className="hud-popup-title"><Icon name={sheet}/><h2>{names[sheet]}</h2>{sheet==='orders'&&<button className="hud-pin" aria-label={ordersPinned?'Sabitlemeyi kaldır':'Siparişleri sabitle'} title={ordersPinned?'Sabit · Sabitlemeyi kaldır':'Siparişleri ekranda tut'} aria-pressed={ordersPinned} onClick={()=>setOrdersPinned(!ordersPinned)}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3h8l-1 7 4 4H5l4-4-1-7Z M12 14v7"/></svg></button>}<button className="hud-close" onClick={()=>setSheet(null)} aria-label="Kapat">×</button></div><div className="hud-popup-body">
{sheet==='orders'&&<>{s.orders.length===0?<div className="hud-empty"><Icon name="orders"/><h3>Yeni misafirler bekleniyor</h3><p>Siparişler burada görünecek.</p></div>:s.orders.map(o=><article className="hud-ticket" key={o.id}><header><b>#{String(o.id).padStart(3,'0')}</b><span>{o.takeaway?'Paket':'Masada'}</span></header><div className="order-foods">{o.needed.map((k,i)=><div key={k+'-'+i}><img src={photo(s.menu[k])} alt=""/><strong>{s.menu[k].name}</strong><small>{o.received.includes(k)?'✓ Hazır':'Hazırlanıyor'}</small></div>)}</div><footer>{o.received.length===o.needed.length?'Teslime hazır':'Hazırlanıyor'}<b><Icon name="coin"/>{money(o.total)}</b></footer></article>)}<button className="hud-secondary" onClick={()=>service.spawnCustomer()}>Müşteri çağır</button></>}
{sheet==='kitchen'&&<><div className="hud-tabs">{[['all','Açık istasyonlar'],['locked','Kilitli istasyonlar']].map(([k,n])=><button key={k} className={category===k?'active':''} onClick={()=>{setCategory(k);setPage(0);}}>{n}</button>)}</div>{Object.entries(s.menu).filter(([k])=>(category==='locked')?!s.stations[k].unlocked:s.stations[k].unlocked).filter(([,m],i,a)=>a.findIndex(([,v])=>v.station===m.station)===i).map(([k,m])=>{const t=s.stations[k],build=machines[m.station];return <article className="hud-machine" key={k}><img src={build?modelThumbnail(build,'machine-'+m.station):photo(m)} alt=""/><div><h3>{m.station==='burger'?'Burger istasyonu':m.station==='soda'?'İçecek makinesi':m.name}</h3><p>{m.name}</p><span className="hud-status">{!t.unlocked?'Sv. '+m.unlockLevel:s.production[k]!==null?'Hazırlanıyor · '+Math.ceil(s.production[k])+' sn':'Sipariş bekliyor'}</span><small>Hız {t.level}/5 · {t.automatic?'Otomatik':'Manuel'}</small></div><button className="hud-primary" onClick={()=>inspect(k)}>{t.unlocked?'Geliştir':'İncele'}</button></article>})}</>}
{sheet==='research'&&<>
<div className="research-summary"><div><strong>Araştırma atölyesi</strong><small>Yeni tarifler burada geliştirilir.</small></div><span className="hud-status">{s.research.jobs.length} / {s.research.slots} yer dolu</span></div>
<div className="research-active">{Array.from({length:s.research.slots},(_,index)=>{const job=s.research.jobs[index],m=job&&Object.values(s.menu).find(m=>m.modelId===job.id);return <article className={'research-slot '+(job?'working':'')} key={index}>{job?<><img src={photo(m)} alt=""/><div><h3>{m.name}</h3><small>Geliştiriliyor · {durationLabel(job.remaining)}</small><progress value={job.duration-job.remaining} max={job.duration}/><span>%{Math.floor((1-job.remaining/job.duration)*100)} tamamlandı</span></div></>:<><Icon name="research"/><div><h3>Boş araştırma yeri</h3><small>Aşağıdan bir tarif seçerek başlat.</small></div></>}</article>;})}</div>
{s.research.slots<2&&<button className="hud-secondary research-slot-buy" disabled={s.availableGold<s.researchSlotCost} onClick={()=>service.buyResearchSlot()}>İkinci araştırma yerini aç · {money(s.researchSlotCost)} altın</button>}
<div className="hud-tabs">{[['available','Başlatılabilir'],['locked','Kilitli'],['completed','Tamamlanan']].map(([k,n])=><button key={k} className={researchFilter===k?'active':''} onClick={()=>{setResearchFilter(k);setResearchPage(0);setNotice('');}}>{n}</button>)}</div>
{researchList.length===0?<div className="hud-empty"><Icon name="research"/><h3>{researchFilter==='completed'?'Henüz tamamlanan araştırma yok':researchFilter==='locked'?'Bu bölümde kilitli araştırma yok':'Şu an başlatılabilir araştırma yok'}</h3><p>{researchFilter==='available'?'Kilitli bölümünde gereken seviyeyi ve önceki tarifleri görebilirsin.':'Tarifler ilerledikçe bu bölüm güncellenir.'}</p></div>:researchList.slice(researchPage*8,researchPage*8+8).map(([k,m])=>{const t=s.stations[k],rule=service.unlockConditions(k),missing=rule.checks?.filter(c=>!c.met)||[];return <article className="hud-machine research-recipe" key={k}><img src={photo(m)} alt=""/><div><h3>{m.name}</h3><p>Sv. {m.unlockLevel} · {durationLabel(s.research.policies[m.modelId].seconds)}</p>{researchFilter==='completed'?<span className="hud-status">✓ Tarif açıldı</span>:<><small>{missing.map(c=>c.type==='level'?'Gerekli seviye: '+c.required:c.type==='prerequisite'?'Önce aç: '+researchTitle(c.id):c.type==='gold'?'Yeterli altın yok':'Koşul gerekli').join(' · ')||'Koşullar tamam'}</small>{rule.allowed&&s.research.jobs.length>=s.research.slots&&<small>Boş araştırma yeri bekleniyor</small>}</>}</div>{researchFilter!=='completed'&&<button className="hud-primary" disabled={!t.canUnlock} onClick={()=>startResearch(k)}>Araştır · {money(m.unlockGold)}</button>}</article>;})}
{researchList.length>8&&<div className="hud-pager"><button disabled={researchPage===0} onClick={()=>setResearchPage(researchPage-1)}>‹ Önceki</button><span>{researchPage+1} / {Math.ceil(researchList.length/8)}</span><button disabled={(researchPage+1)*8>=researchList.length} onClick={()=>setResearchPage(researchPage+1)}>Sonraki ›</button></div>}
<p className="hud-notice" role="status">{notice||'Ücret başlangıçta bir kez alınır. Araştırma tamamlanınca tarif otomatik açılır.'}</p>
</>}
{sheet==='team'&&<><div className="hud-tabs">{['Servis','Kasa','Aşçı','Temizlik'].map(n=><button key={n} className={role===n?'active':''} onClick={()=>setRole(n)}>{n}</button>)}</div>{role==='Servis'?<><article className="hud-person"><img src={modelThumbnail(B.nero,'portrait-nero')} alt="Nero"/><div><h3>Nero</h3><p>Servis komisi</p><span className="hud-status">Çalışıyor</span></div></article><article className="hud-person"><Icon name="team"/><div><h3>Servis ekibi · {s.workers.length}/10</h3><p>Nero dahil toplam 10 servisçi.</p></div><button className="hud-primary" disabled={!s.canHireWaiter} onClick={()=>service.hireWaiter()}>{s.workers.length>=10?'Ekip dolu':money(s.waiterCost)+' · İşe al'}</button></article></>:role==='Kasa'?s.cashiers.map(c=><article className="hud-person" key={c.id}><Icon name="storage"/><div><h3>Kasa {c.id+1}</h3><p>{c.hired?'İşlem: '+c.seconds.toFixed(2)+' sn · Hız '+c.speedLevel+'/5':'Boş kasa'}</p></div><button className="hud-primary" disabled={!c.canHire} onClick={()=>service.buyCashier(c.id)}>{c.hired?'Çalışıyor':money(c.cost)+' · İşe al'}</button>{c.hired&&<button className="hud-secondary" disabled={!c.canSpeed} onClick={()=>service.upgradeCashier(c.id)}>Hızlandır · {money(c.speedCost)}</button>}</article>):role==='Aşçı'?<><article className="hud-person"><img src={modelThumbnail(B.sponge,'portrait-sponge')} alt="SpongeBob"/><div><h3>SpongeBob</h3><p>Burger istasyonu</p><span className="hud-status">Çalışıyor</span></div></article>{(s.kitchenStaff||[]).filter(c=>c.station!=='burger').map(c=><article className="hud-person" key={c.station}><Icon name="kitchen"/><div><h3>{c.name}</h3><p>{c.role||c.station}</p><span className="hud-status">{c.state} · İstasyon aşçısı</span></div></article>)}<p>Her açık yemek istasyonunun bir aşçı görevi var. İstasyon açıldığında aşçısı otomatik yerleşir.</p></>:<article className="hud-person"><img src={modelThumbnail(krabsCleaner,'portrait-krabs')} alt="Bay Yengeç"/><div><h3>Bay Yengeç · Temizlik {s.cleaners?.length||1}/10</h3><span className="hud-status">Başlangıçtan açık · Temizlikçi</span><p>Temizlik: {5-s.table.level*1.5} saniye</p></div><button className="hud-primary" disabled={s.table.cleanerHired?!s.table.canUpgrade:!s.table.canHire} onClick={()=>s.table.cleanerHired?service.upgradeCleaner():service.hireCleaner()}>{s.table.cleanerHired?(s.table.level===2?'En yüksek hız':money(s.table.upgradeCost)+' · Geliştir'):money(s.table.hireCost)+' · İşe al'}</button><button className="hud-secondary" disabled={!s.table.canHire} onClick={()=>service.hireCleaner()}>{(s.cleaners?.length||1)>=10?'Ekip dolu':'Temizlikçi al · '+money(s.table.hireCost)}</button></article>}</>}
{sheet==='storage'&&<><div className="storage-meter"><div><b>Kapasite: {money(s.inventory.used)} / {money(s.inventory.capacity)}</b><progress value={s.inventory.used} max={s.inventory.capacity}/></div><button className="hud-secondary" disabled={!s.storageOffer||s.availableGold<s.storageOffer.cost} onClick={()=>service.upgradeStorage()}>{s.storageOffer?'Kapasiteyi artır · '+money(s.storageOffer.cost):'En yüksek kapasite'}</button></div><div className="material-list">{ingredients.map((m,i)=><div className="hud-material" key={m.id}><div className={'material-token tone-'+i%4}>{m.name.slice(0,2)}</div><div><strong>{m.name}</strong><small>{money(m.available)} adet · {money(m.unitGold)} altın/adet</small></div><div className="quantity"><button disabled={!amounts[m.id]} onClick={()=>setAmounts({...amounts,[m.id]:Math.max(0,(amounts[m.id]||0)-10)})}>−</button><input aria-label={m.name+' sipariş adedi'} type="number" min="0" max="10000" step="1" value={amounts[m.id]||0} onChange={e=>setAmounts({...amounts,[m.id]:Math.max(0,Math.min(10000,Math.floor(Number(e.target.value)||0)))})}/><button onClick={()=>setAmounts({...amounts,[m.id]:Math.min(10000,(amounts[m.id]||0)+10)})}>+</button></div></div>)}</div><div className="storage-checkout"><div><small>Sipariş tutarı</small><strong><Icon name="coin"/>{money(total)} altın</strong></div><button className="hud-primary" disabled={total===0||total>s.availableGold} onClick={order}>Sipariş ver</button></div><p className="hud-notice" role="status">{notice||'Teslimat: 20 saniye · Yolda: '+s.inventory.incoming+' adet'}</p><details><summary>Otomatik tedarik ve araştırmalar</summary><button className="hud-secondary" disabled={!s.inventory.automatic&&s.availableGold<s.supplyAutoCost} onClick={()=>service.enableAutoSupply()}>{s.inventory.automatic?(s.inventory.automatic.enabled===false?'Otomatik tedarik kapalı · Aç':'Otomatik tedarik açık · Kapat'):'Otomatik tedarik · '+money(s.supplyAutoCost)}</button><p>{s.research.jobs.map(j=>j.id+' · '+Math.ceil(j.remaining/60)+' dk').join(' / ')||'Araştırma bekliyor'}</p><button className="hud-secondary" disabled={s.research.slots===2||s.availableGold<s.researchSlotCost} onClick={()=>service.buyResearchSlot()}>Araştırma yeri: {s.research.slots} · {s.researchSlotCost} altın</button></details></>}
{sheet==='recipes'&&<><div className="hud-tabs">{[['all','Hepsi'],['main','Ana yemek'],['side','Yan ürün'],['drink','İçecek'],['dessert','Tatlı']].map(([k,n])=><button key={k} className={category===k?'active':''} onClick={()=>{setCategory(k);setPage(0);}}>{n}</button>)}</div><div className="hud-recipes">{Object.entries(s.menu).filter(([,m])=>category==='all'||!['main','side','drink','dessert'].includes(category)||m.category===category).slice(page*12,page*12+12).map(([k,m])=><button className={'hud-recipe '+(!s.stations[k].unlocked?'locked':'')} key={k} onClick={()=>inspect(k)}><img loading="lazy" src={photo(m)} alt=""/><div><strong>{m.name}</strong><small>{s.stations[k].unlocked?'✓ Açık':'Sv. '+m.unlockLevel}</small><span>İncele ›</span></div></button>)}</div><div className="hud-pager"><button disabled={page===0} onClick={()=>setPage(page-1)}>‹ Önceki</button><span>{page+1}</span><button disabled={(page+1)*12>=Object.values(s.menu).filter(m=>category==='all'||!['main','side','drink','dessert'].includes(category)||m.category===category).length} onClick={()=>setPage(page+1)}>Sonraki ›</button></div><a className="hud-tree" href="unlock-tree.html" target="_blank">Unlock ağacı ↗</a></>}
</div></section></>}
{(selected||s.selectedCashier!==null||s.selectedTable!==null)&&<section className="hud-detail" role="dialog" aria-label="Geliştirme"><button className="hud-close" onClick={closeDetail} aria-label="Kapat">×</button>{selected?<><img src={photo(selected)} alt=""/><h2>{selected.name}</h2><p>{selected.baseSeconds} sn · Satış {money(selected.price)} altın · Sv. {selected.unlockLevel}</p>{st.unlocked?<><span className="hud-status">Hız {st.level}/5 · {st.duration.toFixed(1)} sn</span><button className="hud-primary" disabled={!s.canProduce[stationKey]||st.automatic} onClick={()=>service.startProduction(stationKey)}>{st.automatic?'Siparişe göre otomatik':'Hazırla'}</button><button className="hud-secondary" disabled={!st.canAutomatic} onClick={()=>service.upgradeStation(stationKey,'automatic')}>{st.automatic?'Otomatik üretim açık':'Otomatik üretim · '+money(st.autoCost)}</button><button className="hud-secondary" disabled={!st.canSpeed} onClick={()=>service.upgradeStation(stationKey,'speed')}>{st.level===5?'En yüksek hız · −%50':'Hızlandır · '+money(st.speedCost)}</button></>:<><p>{st.researchRemaining!==null?'Araştırma: '+Math.ceil(st.researchRemaining/60)+' dk':st.unlockReason==='prerequisite'?'Önceki tarif gerekli':st.researchSeconds?'Araştırma: '+Math.ceil(st.researchSeconds/60)+' dk':'Seviye ve önceki tarif gerekli'}</p><button className="hud-primary" disabled={!st.canUnlock} onClick={()=>service.unlockProduct(stationKey)}>{money(selected.unlockGold)} altın · Aç</button></>}</>:s.selectedCashier!==null?(()=>{const c=s.cashiers[s.selectedCashier];return <><Icon name="storage"/><h2>Kasa {c.id+1}</h2><button className="hud-primary" disabled={!c.canHire} onClick={()=>service.buyCashier(c.id)}>{c.hired?'Kasiyer çalışıyor':'İşe al · '+money(c.cost)}</button>{c.hired&&<><p>İşlem {c.seconds.toFixed(2)} sn · Hız {c.speedLevel}/5</p><button className="hud-secondary" disabled={!c.canSpeed} onClick={()=>service.upgradeCashier(c.id)}>Kasa hızını artır · {money(c.speedCost)}</button></>}</>;})():(()=>{const t=s.tableOffers[s.selectedTable];return <><Icon name="home"/><h2>Yeni masa</h2><p>Üç bağımsız koltuk</p><button className="hud-primary" disabled={!t.canBuy} onClick={()=>service.buyTable(s.selectedTable)}>Masa kur · {money(t.cost)}</button></>;})()}</section>}
</div>;}
