'use strict';
// Offline visual check of the connected mesh's vertex deformation. This does not replace an Electron runtime test.
const fs=require('fs'),path=require('path'),sharp=require('sharp');
const dir=path.resolve(__dirname,'../../themes/default/assets/wardrobe');
const smooth=(a,b,v)=>{const t=Math.max(0,Math.min(1,(v-a)/(b-a)));return t*t*(3-2*t);};
function point(x,y,left,right,lf,rf){const turn=(cx,cy,a)=>[cx+Math.cos(a)*(x-cx)-Math.sin(a)*(y-cy)-x,cy+Math.sin(a)*(x-cx)+Math.cos(a)*(y-cy)-y];const ly=smooth(140,172,y)*(1-smooth(210,230,y)),lw=(1-smooth(35,65,x))*ly,rw=smooth(155,185,x)*ly,a=turn(51,153,left),b=turn(169,153,right);return [(x+a[0]*lw+b[0]*rw)*2,(y+a[1]*lw+b[1]*rw+smooth(223,243,y)*(lf+(rf-lf)*smooth(105,115,x)))*2,x,y];}
async function render(id,left,right,lf=0,rf=0){const src=await sharp(path.join(dir,id,'body.svg')).resize(440,520).ensureAlpha().raw().toBuffer(),out=Buffer.alloc(440*520*4);
function tri(a,b,c){let minX=Math.max(0,Math.floor(Math.min(a[0],b[0],c[0]))),maxX=Math.min(439,Math.ceil(Math.max(a[0],b[0],c[0]))),minY=Math.max(0,Math.floor(Math.min(a[1],b[1],c[1]))),maxY=Math.min(519,Math.ceil(Math.max(a[1],b[1],c[1])));const den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(den)<1e-8)return;
for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const px=x+.5,py=y+.5,u=((b[1]-c[1])*(px-c[0])+(c[0]-b[0])*(py-c[1]))/den,v=((c[1]-a[1])*(px-c[0])+(a[0]-c[0])*(py-c[1]))/den,w=1-u-v;if(u<0||v<0||w<0)continue;const sx=Math.max(0,Math.min(439,Math.floor((a[2]*u+b[2]*v+c[2]*w)*2))),sy=Math.max(0,Math.min(519,Math.floor((a[3]*u+b[3]*v+c[3]*w)*2))),si=(sy*440+sx)*4,oi=(y*440+x)*4;src.copy(out,oi,si,si+4);}}
for(let y=0;y<260;y+=4)for(let x=0;x<220;x+=4){const a=point(x,y,left,right,lf,rf),b=point(Math.min(220,x+4),y,left,right,lf,rf),c=point(x,Math.min(260,y+4),left,right,lf,rf),d=point(Math.min(220,x+4),Math.min(260,y+4),left,right,lf,rf);tri(a,b,c);tri(b,d,c);}
const layers=await Promise.all(['eyes-default.svg','pupils-default.svg','lids-heavy.svg','brows-normal.svg','mouth-neutral.svg'].map(async f=>({input:await sharp(path.join(dir,id,f)).resize(440,520).png().toBuffer()})));const composed=await sharp(out,{raw:{width:440,height:520,channels:4}}).composite(layers).png().toBuffer();return sharp(composed).resize(220,260).png().toBuffer();}
(async()=>{const ids=['daily-kot-ceket','winter-bordo-orgu','retro-01'];const pieces=[];let row=0;for(const id of ids){if(!fs.existsSync(path.join(dir,id)))continue;for(const [col,pose]of [[0,[0,0]],[1,[.48,-.48]],[2,[-.45,.45]],[3,[.3,-.4,0,-4]]])pieces.push({input:await render(id,...pose),left:col*240+10,top:row*280+10});row++;}await sharp({create:{width:960,height:row*280,channels:4,background:'#f7f2e8'}}).composite(pieces).png().toFile(path.resolve(__dirname,'../../mesh-preview.png'));})();
