'use strict';
(() => {
  const api=window.nero,$=id=>document.getElementById(id),root=$('view-budget'),content=$('budget-content'),editor=$('budget-editor');
  let view=null,tab='overview',month=new Date().getFullYear()+'-'+String(new Date().getMonth()+1).padStart(2,'0'),page=0,busy=false;
  const filters={search:'',type:'all',account:'all',category:'all',from:month+'-01',to:month+'-31',sort:'newest',min:'',max:''};
  let formKind=null,editId=null,preview=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const decimal=n=>(Number(n||0)/100).toFixed(2);
  const currency=(n,c=view?.baseCurrency||'TRY')=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:c,minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0)/100);
  const when=d=>new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'));
  const account=id=>view.accounts.find(a=>a.id===id),category=id=>view.categories.find(c=>c.id===id);
  const typeLabel={income:'Gelir',expense:'Gider',transfer:'Transfer',refund:'İade'},frequencyLabel={once:'Bir kez',daily:'Her gün',weekly:'Her hafta',monthly:'Her ay',yearly:'Her yıl'};
  const button=(action,label,id='',cls='')=>`<button type="${'button'}" class="${esc(cls)}" data-budget-action="${esc(action)}" data-id="${esc(id)}">${esc(label)}</button>`;
  const empty=(title,text,action,label)=>`<div class="budget-empty"><span class="budget-empty-mark" aria-hidden="true">◌</span><h3>${esc(title)}</h3><p>${esc(text)}</p>${action?button(action,label,'','budget-primary'):''}</div>`;
  const opts=(items,selected,first='')=>(first?`<option value="">${esc(first)}</option>`:'')+items.map(i=>`<option value="${esc(i.id??i.value)}" ${(i.id??i.value)===selected?'selected':''}>${esc(i.name??i.label)}</option>`).join('');
  function message(text,error=false){$('budget-message').hidden=!text;$('budget-message').textContent=text;$('budget-message').className=error?'budget-error':'budget-success';}
  async function call(channel,...args){const r=await api.invoke(channel,...args);if(!r?.ok){if(!r?.canceled)throw new Error(r?.error||'İşlem tamamlanamadı.');return null;}if(r.view)view=r.view;return r;}
  async function open(){if(busy||editor.open)return;busy=true;try{await call('budget:get',month);render();}catch(e){message(e.message,true);}finally{busy=false;}}
  window.neroBudget={open};$('budget-month').value=month;
  $('budget-month').addEventListener('change',()=>{if(!$('budget-month').value)return;month=$('budget-month').value;filters.from=month+'-01';filters.to=lastDay(month);page=0;open();});
  function lastDay(m){const [y,n]=m.split('-').map(Number);return m+'-'+new Date(y,n,0).getDate();}
  filters.to=lastDay(month);
  document.querySelectorAll('[data-budget-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.budgetTab;page=0;message('');render();b.scrollIntoView({block:'nearest',inline:'nearest'});}));
  function budgetCategory(id){return id==='all'?'Toplam bütçe':category(id)?.name||'Kategori';}
  function meter(spent,limit){const percent=limit?Math.max(0,spent/limit*100):0;return `<div class="budget-progress ${percent>=100?'over':percent>=80?'near':''}" role="meter" aria-label="Bütçe kullanımı" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.min(100,Math.round(percent))}"><i style="width:${Math.min(100,percent)}%"></i></div>`;}
  function summaryCards(){const s=view.summary,total=view.budgets.find(b=>b.categoryId==='all');return `<div class="budget-metrics"><article class="budget-card"><span>Bu ay gelir</span><strong class="budget-income">${currency(s.income)}</strong></article><article class="budget-card"><span>Bu ay net gider</span><strong>${currency(s.netExpense)}</strong><small>İadeler düşülmüş</small></article><article class="budget-card"><span>Gelir − gider</span><strong class="${s.net<0?'budget-negative':'budget-income'}">${currency(s.net)}</strong></article><article class="budget-card"><span>Kalan aylık bütçe</span><strong>${total?currency(total.remaining):'Belirlenmedi'}</strong>${total?meter(total.spent,total.limit):button('new-budget','Limit belirle')}</article></div>`;}
  function overview(){const upcoming=view.upcoming.filter(o=>o.date<=view.today).slice(0,4),next=view.upcoming.filter(o=>o.date>view.today).slice(0,3);return `${summaryCards()}<article class="budget-card budget-balance"><div><span>Toplam net bakiye</span><strong>${currency(view.netWorth)}</strong><small>Kart borçları düşülür · güncel kayıtlı kurlar</small></div>${button('new-transaction','+ İşlem ekle','','budget-primary')}</article>${view.missingRates.length?`<p class="budget-warning">${esc([...new Set(view.missingRates)].join(', '))} için kur eksik; toplam bakiye bu hesapları içermiyor. Hesaplar → Kurlar'dan ekle.</p>`:''}
      <article class="budget-card"><div class="budget-section-head"><h3>Ödeme takvimin</h3>${button('tab-plans','Tümü')}</div>${[...upcoming,...next].map(occurrenceRow).join('')||'<p class="budget-muted">Yaklaşan planlı ödeme yok.</p>'}</article>
      <article class="budget-card"><div class="budget-section-head"><h3>Harcamaların dağılımı</h3>${button('tab-reports','Raporlar')}</div>${categoryRows(view.summary.categories)}</article>
      <article class="budget-card"><div class="budget-section-head"><h3>Son işlemler</h3>${button('tab-transactions','Tümü')}</div>${view.transactions.filter(t=>t.date<=view.today).slice().sort(sortNewest).slice(0,4).map(transactionRow).join('')||'<p class="budget-muted">İlk işlemini eklediğinde burada görünecek.</p>'}</article>`;}
  function transactionRow(t){const name=t.payee||t.note||typeLabel[t.type],sign=t.type==='expense'?'−':t.type==='income'||t.type==='refund'?'+':'↔',sub=t.type==='transfer'?`${account(t.accountId)?.name} → ${account(t.toAccountId)?.name}`:`${account(t.accountId)?.name} · ${t.splits.map(s=>category(s.categoryId)?.name).filter(Boolean).join(', ')}`;return `<button type="button" class="budget-transaction" data-budget-action="edit-transaction" data-id="${esc(t.id)}"><span class="budget-type-icon ${t.type}" aria-hidden="true">${sign}</span><span class="budget-row-main"><b>${esc(name)}</b><small>${esc(sub)}</small><small>${esc(when(t.date))}${t.receiptIds?.length?' · Fiş ekli':''}${t.date>view.today?' · Gelecek tarihli':''}</small></span><span class="budget-row-value ${t.type==='income'||t.type==='refund'?'budget-income':''}">${sign} ${currency(t.amount,t.currency)}</span></button>`;}
  const sortNewest=(a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt);
  function filtered(){return view.transactions.filter(t=>{
    const text=[t.note,t.payee,t.tags,account(t.accountId)?.name,...(t.splits||[]).map(s=>category(s.categoryId)?.name)].join(' ').toLocaleLowerCase('tr');
    return (!filters.search||text.includes(filters.search.toLocaleLowerCase('tr')))&&(filters.type==='all'||t.type===filters.type)&&(filters.account==='all'||t.accountId===filters.account||t.toAccountId===filters.account)&&(filters.category==='all'||t.splits?.some(s=>s.categoryId===filters.category||category(s.categoryId)?.parentId===filters.category))&&t.date>=filters.from&&t.date<=filters.to&&(!filters.min||t.baseAmount>=Number(filters.min.replace(',','.'))*100)&&(!filters.max||t.baseAmount<=Number(filters.max.replace(',','.'))*100);
  }).sort(filters.sort==='largest'?(a,b)=>b.baseAmount-a.baseAmount:filters.sort==='oldest'?(a,b)=>-sortNewest(a,b):sortNewest);}
  function transactions(){const rows=filtered(),shown=rows.slice(page*30,(page+1)*30);return `<div class="budget-toolbar">${button('new-transaction','+ İşlem ekle','','budget-primary')}${button('csv-import','CSV al')}${button('csv-export','CSV çıkar')}${button('trash','Silinenler')}</div><div class="budget-card budget-filters"><label>Ara<input type="search" data-budget-filter="search" value="${esc(filters.search)}" placeholder="Açıklama, kişi, etiket…"></label><div class="budget-field-grid"><label>Tür<select data