(()=>{'use strict';const $=id=>document.getElementById(id),api=window.nero;let state,filters={search:'',priority:'all',tag:''},mounted=false,dragId=null,mode='user',doneCollapsed=true,pointerOrigin=null;
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const button=(text,fn)=>{const b=el('button',text,'nf-button');b.type='button';b.addEventListener('click',e=>{e.stopPropagation();Promise.resolve(fn()).catch(error=>notice(error.message));});return b;};
 const date=time=>new Date(time).toLocaleString('tr-TR',{dateStyle:'medium',timeStyle:'short'});
 const mins=ms=>Math.round((ms||0)/60000)+' dk';
 function notice(text){$('nf-status').textContent=text;}
 function dialog(title,build){const d=$('nf-dialog');delete d.dataset.financeTheme;d.replaceChildren();const head=el('header');head.append(el('h2',title),button('×',()=>d.close()));d.append(head);build(d);d.showModal();}
 function field(parent,label,value,type='text'){const l=el('label',label),input=el('input');input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value||'';l.append(input);parent.append(l);return input;}
 function select(parent,label,items,value){const l=el('label',label),s=el('select');for(const [id,text] of items){const o=el('option',text);o.value=id;s.append(o);}s.value=value;l.append(s);parent.append(l);return s;}
 async function pref(key,value){await api.invoke('features:preference',key,value);}
 function noteMenu(note){dialog('Not işlemleri',d=>{const pinned=field(d,'📎 Sabitle',note.pinned,'checkbox'),tag=select(d,'Etiket',[['','Etiketsiz'],['Kişisel','Kişisel'],['İş','İş'],['Fikir','Fikir']],note.tag||''),color=select(d,'Kağıt rengi',[['paper','Tema kağıdı'],['yellow','Sarı'],['pink','Pembe'],['blue','Mavi'],['green','Yeşil']],note.color||'paper');d.append(button('Kaydet',async()=>{await api.invoke('features:note',{id:note.id,pinned:pinned.checked,tag:tag.value,color:color.value});d.close();}),button(note.archivedAt?'Arşivden çıkar':'Arşivle',async()=>{await api.invoke('notes:archive',note.id,!note.archivedAt);d.close();}),button('Sil',()=>{d.replaceChildren(el('p','Bu not kalıcı olarak silinsin mi?'),button('Vazgeç',()=>d.close()),button('Evet, sil',async()=>{await api.invoke('notes:delete',note.id);d.close();}));}));});}
 function todoMenu(todo){dialog('İşi düzenle',d=>{const text=field(d,'İş',todo.text),bucket=select(d,'Bölüm',[['today','Bugün'],['later','Sonra']],todo.bucket||'today'),priority=select(d,'Öncelik',[['normal','Normal'],['high','Öncelikli'],['low','Düşük']],todo.priority||'normal'),tag=field(d,'Etiket',todo.tag),duration=field(d,'Planlanan dakika',todo.plannedDurationMin||'','number'),reminder=field(d,'Hatırlatma saati',todo.remindAt?new Date(todo.remindAt).toTimeString().slice(0,5):'','time');duration.min=0;duration.max=10080;d.append(button('Kaydet',async()=>{await api.invoke('todos:rename',todo.id,text.value);await api.invoke('features:todo',{id:todo.id,bucket:bucket.value,priority:priority.value,tag:tag.value,plannedDurationMin:Number(duration.value)||0});await api.invoke('todos:setReminder',todo.id,reminder.value);d.close();}),button(todo.archivedAt?'Arşivden çıkar':'Arşivle',async()=>{await api.invoke('todos:archive',todo.id,!todo.archivedAt);d.close();}),button('Sil',()=>{d.replaceChildren(el('p','Bu iş kalıcı olarak silinsin mi?'),button('Vazgeç',()=>d.close()),button('Evet, sil',async()=>{await api.invoke('todos:delete',todo.id);d.close();}));}));});}
 function formatNote(prefix,suffix=''){const t=$('note-body'),start=t.selectionStart,end=t.selectionEnd,text=t.value.slice(start,end);t.setRangeText(prefix+text+suffix,start,end,'select');t.dispatchEvent(new Event('input',{bubbles:true}));t.focus();}
 function mount(){if(mounted)return;mounted=true;const status=el('p','','nf-status');status.id='nf-status';status.setAttribute('role','status');document.querySelector('.shell').append(status);const d=el('dialog');d.id='nf-dialog';document.body.append(d);
  const tools=el('div',undefined,'nf-note-tools');tools.append(button('B',()=>formatNote('**','**')),button('I',()=>formatNote('_','_')),button('• Liste',()=>formatNote('\n- ')),button('☐ Kontrol listesi',()=>formatNote('\n- [ ] ')));$('note-paper').before(tools);
  const search=el('div',undefined,'nf-filters');search.id='nf-todo-filters';const input=el('input');input.placeholder='İşlerde ara…';input.setAttribute('aria-label','İşlerde ara');input.value=filters.search;const priority=el('select');priority.setAttribute('aria-label','Öncelik filtresi');for(const [v,t] of [['all','Tüm öncelikler'],['high','Öncelikli'],['normal','Normal'],['low','Düşük']]){const o=el('option',t);o.value=v;priority.append(o);}priority.value=filters.priority;const tag=el('input');tag.placeholder='Etiket';tag.setAttribute('aria-label','Etiket filtresi');tag.value=filters.tag;const change=()=>{filters={search:input.value,priority:priority.value,tag:tag.value};renderTodos();pref('todoFilters',filters);};input.addEventListener('input',change);priority.addEventListener('change',change);tag.addEventListener('input',change);search.append(input,priority,tag);$('todo-form').before(search);const plan=el('p','','nf-plan');plan.id='nf-plan';search.before(plan);
  const details=el('details',undefined,'nf-capture-options');details.append(el('summary','Süre ve hatırlatma'));$('todo-form').append(details);for(const node of document.querySelectorAll('#todo-form .todo-duration,#todo-form .todo-time'))details.append(node);
  const drops=el('div',undefined,'nf-dropzones');for(const [bucket,label] of [['today','Bugün’e taşı'],['later','Sonra’ya taşı']]){const zone=el('div',label,'nf-dropzone');zone.tabIndex=0;zone.dataset.bucket=bucket;zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('over');});zone.addEventListener('dragleave',()=>zone.classList.remove('over'));zone.addEventListener('drop',async e=>{e.preventDefault();zone.classList.remove('over');if(dragId)await api.invoke('features:todo',{id:dragId,bucket});});drops.append(zone);}$('todo-form').after(drops);
  const taskSelect=el('select');taskSelect.id='nf-timer-task';taskSelect.setAttribute('aria-label','Bugün listesinden iş seç');$('timer-label').before(taskSelect);$('timer-start').addEventListener('click',e=>{if(!taskSelect.value)return;e.stopImmediatePropagation();const t=state.todos.find(t=>t.id===taskSelect.value);api.invoke('timer:start',Number(document.querySelector('#presets .on')?.dataset.min||$('timer-custom').value||25),$('timer-label').value.trim()||t.text,t.id).catch(error=>notice(error.message));},true);
  const sessions=el('section',undefined,'card nf-sessions');sessions.id='nf-sessions';$('view-timer').append(sessions);
  const jarButton=button('Anıları oku',showJar);document.querySelector('.jar .card-head').append(jarButton);const countNode=document.querySelector('.jar .card-head span');if(countNode){countNode.tabIndex=0;countNode.setAttribute('role','button');countNode.addEventListener('click',showJar);countNode.addEventListener('keydown',e=>{if(e.key==='Enter')showJar();});}
  const modes=el('div',undefined,'nf-mood-modes');modes.append(button('Ben',()=>setMoodMode('user')),button('Nero',()=>setMoodMode('nero')),el('small','Kırmızı: zor · Sarı: orta · Yeşil: iyi'));document.querySelector('.user-mood-board').before(modes);
  document.querySelector('#todo-list').addEventListener('pointerdown',e=>{if(e.target.closest('button,input,textarea,select'))return;const row=e.target.closest('[data-todo-id]');if(row){dragId=row.dataset.todoId;pointerOrigin={x:e.clientX,y:e.clientY};}});
  window.addEventListener('pointermove',e=>{if(!pointerOrigin)return;if(Math.hypot(e.clientX-pointerOrigin.x,e.clientY-pointerOrigin.y)>8){document.body.classList.add('nf-dragging');document.querySelectorAll('.nf-dropzone').forEach(z=>z.classList.toggle('over',z===document.elementFromPoint(e.clientX,e.clientY)?.closest('.nf-dropzone')));}});
  window.addEventListener('pointerup',e=>{if(!pointerOrigin)return;const zone=document.elementFromPoint(e.clientX,e.clientY)?.closest('.nf-dropzone');const id=dragId;pointerOrigin=null;document.body.classList.remove('nf-dragging');document.querySelectorAll('.nf-dropzone').forEach(z=>z.classList.remove('over'));if(zone&&id)setTimeout(()=>api.invoke('features:todo',{id,bucket:zone.dataset.bucket}).catch(error=>notice(error.message)),0);},true);
  document.querySelector('#todo-list').addEventListener('dragstart',e=>{dragId=e.target.closest('[data-todo-id]')?.dataset.todoId||null;document.body.classList.add('nf-dragging');});document.addEventListener('dragend',()=>document.body.classList.remove('nf-dragging'));
 }
 function setMoodMode(next){mode=next;document.querySelector('.user-mood-board').hidden=mode!=='user';document.querySelector('.nero-mood-board').hidden=mode!=='nero';pref('moodboardMode',mode);}
 function showJar(){dialog('Kavanozdaki anılar',d=>{d.append(button('Rastgele bir anı',async()=>{const item=await api.invoke('jar:random');const output=d.querySelector('.nf-memory');output.replaceChildren(el('p',item?.text||'Henüz anı yok.'),el('small',item?date(item.createdAt):''));if(item?.onlyMemory)output.append(el('p','Kavanozda yalnızca bir anı var.'));}));d.append(el('div','','nf-memory'));for(const item of [...(state.productivity?.jar||[])].sort((a,b)=>b.createdAt-a.createdAt)){const card=el('article',undefined,'nf-memory-row');card.append(el('p',item.text),el('small',date(item.createdAt)));d.append(card);}});}
 function renderNotes(){const notes=state.notes.filter(n=>!n.archivedAt);const cards=[...$('notes-list').children].filter(n=>!n.classList.contains('new-note'));cards.forEach((card,index)=>{const note=notes[index];if(!note)return;card.dataset.noteId=note.id;card.style.order=note.pinned?'0':'1';card.dataset.noteColor=note.color||'paper';if(note.color&&note.color!=='paper')card.style.setProperty('--note',{yellow:'#fff0ad',pink:'#ffd8e8',blue:'#d3edfa',green:'#d7efcf'}[note.color]);const menu=button('⋯',()=>noteMenu(note));menu.classList.add('nf-menu');menu.setAttribute('aria-label','Not işlemleri');card.append(menu);const tag=el('span',(note.pinned?'📎 ':'')+(note.tag||'NOT'),'nf-note-tag');card.append(tag);for(const label of card.querySelectorAll('.fname,.bs-note-stub,.ticket-stub'))label.textContent=note.tag||'NOT';const tasks=String(note.body||'').split('\n').filter(l=>/^\s*[-*] \[[ xX]\]/.test(l));if(tasks.length){card.append(el('small',`${tasks.filter(l=>/\[[xX]\]/.test(l)).length}/${tasks.length} tamamlandı`,'nf-check-count'));const preview=el('div',undefined,'nf-check-preview'),lines=note.body.split('\n');for(const [index,line] of lines.map((line,index)=>[index,line]).filter(([,line])=>/^\s*[-*] \[[ xX]\]/.test(line)).slice(0,3)){const label=el('label'),box=el('input');box.type='checkbox';box.checked=/\[[xX]\]/.test(line);box.addEventListener('click',e=>e.stopPropagation());box.addEventListener('change',async()=>{lines[index]=line.replace(/\[[ xX]\]/,box.checked?'[x]':'[ ]');await api.invoke('notes:save',{id:note.id,body:lines.join('\n')});});label.append(box,el('span',line.replace(/^\s*[-*] \[[ xX]\] /,'')));preview.append(label);}card.querySelector('.note-preview')?.setAttribute('hidden','');card.append(preview);}});}
 function renderTodos(){const all=state.todos.filter(t=>!t.archivedAt),active=all.filter(t=>!t.done&&(t.bucket||'today')==='today'),planned=active.reduce((s,t)=>s+(t.plannedDurationMin||0),0),unknown=active.filter(t=>!t.plannedDurationMin).length;$('nf-plan').textContent=`Bugün: ${active.length} iş · yaklaşık ${planned} dk${unknown?' · '+unknown+' işin süresi belirtilmedi':''}`;
  const list=$('todo-list');list.querySelectorAll('.nf-group').forEach(n=>n.remove());const rows=[...list.children].filter(r=>r.dataset.todoId);for(const row of rows){const t=all.find(t=>t.id===row.dataset.todoId);if(!t)continue;const hay=t.text.toLocaleLowerCase('tr');row.hidden=!(hay.includes(filters.search.toLocaleLowerCase('tr'))&&(filters.priority==='all'||(t.priority||'normal')===filters.priority)&&(!filters.tag||(t.tag||'').toLocaleLowerCase('tr').includes(filters.tag.toLocaleLowerCase('tr'))));row.dataset.nfMatches=String(!row.hidden);if(t.done&&doneCollapsed)row.hidden=true;if(!row.querySelector('.nf-menu')){const menu=button('⋯',()=>todoMenu(t));menu.classList.add('nf-menu');menu.setAttribute('aria-label','İş işlemleri');row.append(menu);const meta=el('small',undefined,'nf-task-meta');const sub=t.subtasks||[];meta.textContent=[t.priority==='high'?'Öncelikli':t.priority==='low'?'Düşük öncelik':'',t.tag,sub.length?`${sub.filter(x=>x.done).length}/${sub.length} adım`:'',''].filter(Boolean).join(' · ');row.append(meta);}}
  for(const [key,title] of [['today','Bugün'],['later','Sonra'],['done','Bugün tamamlananlar'],['older','Önceki günlerde tamamlananlar']]){const matches=rows.filter(r=>{const t=all.find(t=>t.id===r.dataset.todoId);const finishedToday=t?.doneAt&&new Date(t.doneAt).toDateString()===new Date().toDateString();return key==='done'?t?.done&&finishedToday:key==='older'?t?.done&&!finishedToday:t&&!t.done&&(t.bucket||'today')===key;});if(!matches.length)continue;const heading=el('li',undefined,'nf-group');heading.append(el('strong',title));if(key==='done'||key==='older'){const fold=button('Göster / gizle',()=>{doneCollapsed=!doneCollapsed;for(const r of matches)r.hidden=doneCollapsed||r.dataset.nfMatches==='false';});heading.append(fold);}list.append(heading,...matches);}
 }
 function renderSessions(){const root=$('nf-sessions');root.replaceChildren(el('h3','Bugünkü oturumlar'));const today=new Date().toLocaleDateString('en-CA'),sessions=(state.productivity?.sessions||[]).filter(s=>s.day===today);if(!sessions.length)root.append(el('p','Henüz odak oturumu yok.'));for(const s of sessions){const row=el('div',undefined,'nf-session');row.append(el('strong',s.todoName||s.label||'Serbest odak'),el('span',mins(s.elapsedMs)),el('small',{completed:'Tamamlandı',cancelled:'Bırakıldı',interrupted:'Yarıda kaldı',running:'Çalışıyor',paused:'Duraklatıldı'}[s.status]||s.status));root.append(row);}}
 function update(next){state=next;if(!mounted){filters=state.productivity?.preferences?.todoFilters||filters;mode=state.productivity?.preferences?.moodboardMode||mode;mount();}renderNotes();renderTodos();renderSessions();const task=$('nf-timer-task'),chosen=task.value;task.replaceChildren(el('option','İş seçmeden odaklan'));task.firstChild.value='';for(const t of state.todos.filter(t=>!t.done&&!t.archivedAt&&(t.bucket||'today')==='today')){const o=el('option',t.text);o.value=t.id;task.append(o);}task.value=chosen;document.querySelector('.user-mood-board').hidden=mode!=='user';document.querySelector('.nero-mood-board').hidden=mode!=='nero';for(const calendar of document.querySelectorAll('.mood-calendar')){const today=new Date(),n=today.getDate();if($('moodboard-month').textContent.toLocaleLowerCase('tr').includes(today.toLocaleString('tr-TR',{month:'long'})))for(const b of calendar.querySelectorAll('.mood-day'))b.classList.toggle('nf-today',Number(b.textContent)===n);}
  for(const li of document.querySelectorAll('#archive-list>li,#archive-more-list>li')){li.style.textDecoration='none';const item=state.home?.archive?.recent?.find(i=>li.textContent.includes(i.text));if(item?.doneAt&&!li.querySelector('small'))li.append(el('small','✓ '+date(item.doneAt)));}
  for(const bar of document.querySelectorAll('#week-bars .bar')){const focus=Number(bar.dataset.focus)||0;if(!focus){const fill=bar.querySelector('i');if(fill){fill.style.height='0';fill.style.minHeight='0';}}if(!bar.dataset.nfBound){bar.dataset.nfBound='1';bar.tabIndex=0;bar.setAttribute('role','button');const open=()=>{const index=[...bar.parentElement.children].indexOf(bar),day=state.stats.week[index];dialog(day?.day||'Odak günü',d=>{d.append(el('p',focus+' dakika odak'));for(const session of (state.productivity?.sessions||[]).filter(s=>s.day===day?.day))d.append(el('p',(session.todoName||session.label||'Serbest odak')+' · '+mins(session.elapsedMs)));});};bar.addEventListener('click',open);bar.addEventListener('keydown',e=>{if(e.key==='Enter')open();});}}
 }
 window.NeroFeaturesUI={update};
})();
