(()=>{'use strict';const $=id=>document.getElementById(id),active=()=>document.documentElement.dataset.skin==='bikini-bottom';let mounted=false,state,selected=null,dirty=false,saveTimer=null;const moves=new Map();
 function move(node,parent,before=null){if(node.parentNode===parent&&(before?node.nextSibling===before:node===parent.lastChild))return;if(!moves.has(node)){const mark=document.createComment('sponge original');node.before(mark);moves.set(node,mark);}parent.insertBefore(node,before);}
 function restore(){for(const [node,mark] of moves){mark.after(node);mark.remove();}moves.clear();}
 const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
 function savedStatus(message='Kaydedildi',saved=true){const root=$('sb-saved');root.replaceChildren();root.dataset.saved=String(saved);if(saved){const mark=text('span','✓');mark.className='sb-save-mark';mark.setAttribute('aria-hidden','true');root.append(mark);}root.append(text('span',message));}
 async function save(){clearTimeout(saveTimer);if(!dirty||!selected)return;dirty=false;try{await window.nero.invoke('notes:save',{id:selected,body:$('sb-note-title').value+'\n'+$('sb-note-text').value});savedStatus();}catch(e){dirty=true;savedStatus('Kaydedilemedi: '+e.message,false);}}
 function schedule(){dirty=true;savedStatus('Yazılıyor…',false);clearTimeout(saveTimer);saveTimer=setTimeout(save,400);}
 function mount(){if(mounted)return;mounted=true;document.querySelector('.brand').append(Object.assign(text('small','Bikini Bottom'),{className:'sb-only sb-subtitle'}));document.querySelector('.shell').append(Object.assign(text('div',''),{className:'sb-only sb-seabed'}));document.querySelector('.hello').append(Object.assign(text('span',''),{className:'sb-only sb-hero-character'}));const kitchen=text('section','');kitchen.className='sb-only sb-kitchen';kitchen.append(text('strong','Yengeç Restoranı'),text('small','Sipariş panosu · Bir iş daha hazır!'));$('view-todos').prepend(kitchen);
  for(const [name,title] of Object.entries({notes:'Notlar',todos:'İşler',timer:'Odak zamanı',badges:'Rozetler'})){const root=name==='notes'?$('notes-list-view'):$('view-'+name),heading=text('header','');heading.className='sb-only sb-heading';heading.append(text('h2',title));if(name==='notes'){const button=text('button','+ Yeni not');button.id='sb-new-note';button.type='button';button.addEventListener('click',async()=>{await save();const n=await window.nero.invoke('notes:save',{body:'Yeni not\n'});selected=n.id;renderEditor(n,true);$('sb-note-title').focus();$('sb-note-title').select();});heading.append(button);}root.prepend(heading);}
  const composer=text('section','');composer.id='sb-composer';composer.className='sb-only sb-composer';const header=text('header',''),title=document.createElement('input');title.id='sb-note-title';title.setAttribute('aria-label','Not başlığı');const status=text('span','✓ Kaydedildi');status.id='sb-saved';status.setAttribute('role','status');header.append(title,status);const body=document.createElement('textarea');body.id='sb-note-text';body.setAttribute('aria-label','Not metni');body.spellcheck=true;composer.append(header);const toolbar=text('div','');toolbar.className='sb-format';for(const [label,start,end] of [['B','**','**'],['I','_','_'],['• Liste','\n- ',''],['☐ Liste','\n- [ ] ','']]){const b=text('button',label);b.type='button';b.addEventListener('click',()=>{const a=body.selectionStart,z=body.selectionEnd;body.setRangeText(start+body.value.slice(a,z)+end,a,z,'select');schedule();body.focus();});toolbar.append(b);}composer.append(toolbar,body);$('notes-list-view').insertBefore(composer,$('notes-archive'));title.addEventListener('input',schedule);body.addEventListener('input',schedule);body.addEventListener('blur',save);
  const choose=async e=>{if(!active()||e.target.closest('button,input,label'))return;if(e.type==='keydown'&&!['Enter',' '].includes(e.key))return;const card=e.target.closest('li[data-sb-note]');if(!card)return;e.preventDefault();e.stopImmediatePropagation();await save();selected=card.dataset.sbNote;renderEditor(state.notes.find(n=>n.id===selected),true);if(e.type==='keydown')$('sb-note-title').focus();};
  $('notes-list').addEventListener('click',choose,true);$('notes-list').addEventListener('keydown',choose,true);
 }
 function renderEditor(note,force=false){const root=$('sb-composer');root.hidden=!note;if(!note)return;if(!force&&(dirty||root.contains(document.activeElement)))return;const [title,...lines]=String(note.body||'').split('\n');$('sb-note-title').value=title;$('sb-note-text').value=lines.join('\n');savedStatus();}
 function leave(next){if(next!=='bikini-bottom'&&mounted){save();restore();}}
 function update(next){state=next;if(!active()){if(mounted)restore();return;}mount();document.body.classList.toggle('sb-no-scene',next.settings?.sceneBg===false);move(document.querySelector('.nero-says'),document.querySelector('.hello'));move($('st-days').closest('.tile'),document.querySelector('.home-grid'));const notes=next.notes.filter(n=>!n.archivedAt),note=notes.find(n=>n.id===selected)||notes[0];selected=note?.id||null;[...$('notes-list').children].filter(n=>!n.classList.contains('new-note')).forEach((card,i)=>{card.dataset.sbNote=notes[i]?.id;card.dataset.sbColor=notes[i]?.color&&notes[i].color!=='paper'?notes[i].color:['yellow','pink','blue'][i%3];card.classList.toggle('sb-wide-note',i===0);});renderEditor(note);const badges=$('badge-count');if(badges)badges.classList.add('sb-collection-count');}
 function skins(base){return {'bikini-bottom':{...base,tabs:{home:'Bugün',notes:'Notlar',todos:'İşler',timer:'Sayaç',badges:'Rozetler',budget:'Bütçe',settings:'Ayarlar'},timerIdle:'Bir adım daha ileri.',timerRunning:'Odak zamanı!',timerPaused:'Kısa bir ara…',timerStart:'Başlat',quickFocus:'Odaklan',tagline:'',sticky:'',subs:{}}};}
 window.NeroSpongeTheme={update,skins,leave};
})();
