// Approved series artwork surrounds existing live state and IPC; no demo records.
(()=>{'use strict';const $=id=>document.getElementById(id),themes=['stars-hollow','scranton'];let mounted=false,state=null,selected=null,dirty=false,saveTimer=null,serial=Promise.resolve();const positions=new Map();
 const active=()=>themes.includes(document.documentElement.dataset.skin),which=()=>document.documentElement.dataset.skin;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,fn)=>{const b=el('button',text,'tv-button');b.type='button';b.addEventListener('click',()=>Promise.resolve(fn()).catch(e=>{$('tv-save').textContent=e.message;}));return b;};
 function move(n,p,before=null){if(n.parentElement===p)return;if(!positions.has(n)){const mark=document.createComment('tv original position');n.before(mark);positions.set(n,mark);}p.insertBefore(n,before);}
 function restore(){for(const [n,mark] of positions){mark.after(n);mark.remove();}positions.clear();}
 function asset(name){return `nero-theme://${which()}/assets/${name}.png`;}
 function save(){clearTimeout(saveTimer);if(!dirty||!selected)return serial;const id=selected,body=$('tv-note-title').value+'\n'+$('tv-note-text').value;dirty=false;serial=serial.then(()=>window.nero.invoke('notes:save',{id,body})).then(()=>{$('tv-save').textContent='✓ Kaydedildi';}).catch(e=>{dirty=true;$('tv-save').textContent='Kaydedilemedi: '+e.message;});return serial;}
 function schedule(){dirty=true;$('tv-save').textContent='Yazılıyor…';clearTimeout(saveTimer);saveTimer=setTimeout(save,450);}
 function editor(note,force=false){const c=$('tv-composer');c.hidden=!note;if(!note)return;if(!force&&(dirty||c.contains(document.activeElement)))return;const [title,...lines]=note.body.split('\n');$('tv-note-title').value=title;$('tv-note-text').value=lines.join('\n');$('tv-save').textContent='✓ Kaydedildi';}
 function mount(){if(mounted)return;mounted=true;document.querySelector('.brand').append(el('small','','tv-only tv-subtitle'));const badge=el('span','DUNDER\nMIFFLIN','tv-only tv-company');document.querySelector('.top').append(badge);
  const scene=el('div',undefined,'tv-only tv-home-scene');scene.setAttribute('aria-hidden','true');document.querySelector('.hello').append(scene);
  for(const [page,title] of Object.entries({notes:'Notlar',todos:'Bir sonraki adım',timer:'Odak zamanı',badges:'Rozetler'})){const target=page==='notes'?$('notes-list-view'):$('view-'+page),head=el('header',undefined,'tv-only tv-page-head');head.dataset.tvPage=page;head.append(el('h2',title),el('div',undefined,'tv-page-scene'));if(page==='notes'){head.append(button('+ Yeni not',async()=>{await save();const n=await window.nero.invoke('notes:save',{body:'Yeni not\n'});selected=n.id;editor(n,true);$('tv-note-title').focus();$('tv-note-title').select();}));}target.prepend(head);}
  const c=el('section',undefined,'tv-only tv-composer');c.id='tv-composer';const head=el('header'),title=el('input');title.id='tv-note-title';title.setAttribute('aria-label','Not başlığı');const status=el('span','✓ Kaydedildi');status.id='tv-save';status.setAttribute('role','status');head.append(title,status);const text=el('textarea');text.id='tv-note-text';text.setAttribute('aria-label','Not metni');text.spellcheck=true;
  const tools=el('div',undefined,'tv-note-tools');for(const [label,a,z] of [['B','**','**'],['I','_','_'],['• Liste','\n- ',''],['☐ Kontrol listesi','\n- [ ] ',''],['Bağlantı','[','](https://)']])tools.append(button(label,()=>{text.setRangeText(a+text.value.slice(text.selectionStart,text.selectionEnd)+z,text.selectionStart,text.selectionEnd,'select');schedule();text.focus();}));c.append(head,tools,text);$('notes-list-view').insertBefore(c,$('notes-archive'));title.addEventListener('input',schedule);text.addEventListener('input',schedule);text.addEventListener('blur',save);
  $('notes-list').addEventListener('click',async e=>{if(!active()||e.target.closest('button,input,label'))return;const row=e.target.closest('li[data-tv-note]');if(!row)return;e.preventDefault();e.stopImmediatePropagation();await save();selected=row.dataset.tvNote;editor(state.notes.find(n=>n.id===selected),true);},true);
  for(const [selector,name] of [['.jar','jar'],['.desk','bobble']]){const image=el('img',undefined,'tv-only tv-prop tv-'+name);image.dataset.tvAsset=name;image.alt='';image.setAttribute('aria-hidden','true');document.querySelector(selector).append(image);}
  const footer=el('div',undefined,'tv-only tv-day-footer');footer.id='tv-day-footer';document.querySelector('.home-grid').append(footer);
  const jello=el('img',undefined,'tv-only tv-jello');jello.alt='';jello.src='nero-theme://scranton/assets/jello.png';jello.setAttribute('aria-hidden','true');document.querySelector('.jar').append(jello);
  const reset=button('Sıfırla',()=>window.nero.invoke('timer:cancel'));reset.classList.add('tv-only','tv-timer-reset');reset.id='tv-timer-reset';document.querySelector('.timer-actions').append(reset);
  const timerInfo=el('section',undefined,'tv-only tv-timer-info');timerInfo.id='tv-timer-info';$('view-timer').append(timerInfo);
  const board=el('div',undefined,'tv-only tv-todo-board');board.id='tv-todo-board';for(const [id,title] of [['today','Bugün'],['later','Sonra'],['done','Tamamlananlar']]){const group=el('section',undefined,'tv-todo-group');group.dataset.tvBucket=id;group.append(el('h3',title));board.append(group);}document.querySelector('.list-card').append(board);
  // Cards retain existing native ordering/drag handlers. Clicks/checkboxes never open editor accidentally.
  window.addEventListener('beforeunload',save);
 }
 function leave(next){if(mounted&&next!==which()){save();if(!themes.includes(next))restore();}}
 function arrange(){if(!active()||!mounted)return;const counters={today:2,later:2,done:2};for(const row of $('todo-list').querySelectorAll('[data-todo-id]')){const t=state.todos.find(t=>t.id===row.dataset.todoId);if(!t)continue;const key=t.done?'done':t.bucket||'today';row.dataset.tvBucket=key;row.style.setProperty('--tv-row',String(counters[key]++));}const doneStart=Math.max(counters.today,counters.later)+1;let heading=0;for(const group of $('todo-list').querySelectorAll('.nf-group')){const title=group.querySelector('strong')?.textContent;group.dataset.tvGroup=title==='Bugün'?'today':title==='Sonra'?'later':'done';heading++;group.style.setProperty('--tv-done-start',String(doneStart));}for(const row of $('todo-list').querySelectorAll('[data-tv-bucket=done]'))row.style.setProperty('--tv-row',String(doneStart+Number(row.style.getPropertyValue('--tv-row'))));}
 function update(next){state=next;if(!active()){if(mounted)restore();return;}mount();const theme=which();document.querySelector('.tv-subtitle').textContent=theme==='stars-hollow'?'Stars Hollow':'Scranton Şubesi';document.body.classList.toggle('tv-no-scene',next.settings?.sceneBg===false);
  for(const [page,title] of Object.entries({notes:'Notlar',todos:'Bir sonraki adım',timer:'Odak zamanı',badges:'Rozetler'}))document.querySelector(`[data-tv-page=${page}]`).style.setProperty('--tv-scene',`url("${asset(page)}")`);
  document.querySelector('.hello').style.setProperty('--tv-scene',`url("${asset('home')}")`);for(const img of document.querySelectorAll('[data-tv-asset]')){const name=theme==='stars-hollow'&&img.dataset.tvAsset==='bobble'?'books':img.dataset.tvAsset;img.src=asset(name);}
  move($('st-days').closest('.tile'),$('tv-day-footer'));move(document.querySelector('.nero-says'),document.querySelector('.hello'));
  const notes=next.notes.filter(n=>!n.archivedAt);if(!notes.some(n=>n.id===selected)){if(dirty)save();selected=notes[0]?.id||null;}[...$('notes-list').children].filter(n=>!n.classList.contains('new-note')).forEach((card,i)=>{card.dataset.tvNote=notes[i]?.id||'';card.classList.toggle('tv-wide-note',i===0);card.dataset.tvColor=notes[i]?.color&&notes[i].color!=='paper'?notes[i].color:['yellow','green','pink'][i%3];});editor(notes.find(n=>n.id===selected));
  $('tv-timer-reset').hidden=next.timer.status!=='idle';$('tv-timer-info').replaceChildren(el('span','Bugün odak'),el('strong',$('st-today-focus').textContent),el('span','Tamamlanan sayaç'),el('strong',String(next.stats?.today?.timersDone??0)));
  for(const card of $('badge-grid').children){const index=[...card.parentElement.children].indexOf(card),icons=theme==='stars-hollow'?['badgeMug','badgeBook','badgeDragonfly','badgeGazebo','badgeTape']:['badgeTrophy','badgeCertificate','badgeMug','badgeTray','badgeBobble'];const icon=card.querySelector('.badge-icon');if(card.classList.contains('on')){icon.textContent='';const img=el('img');img.alt='';img.src=asset(icons[index%icons.length]);icon.append(img);}else{icon.textContent='🔒';}}
  arrange();
 }
 function skins(base){const shared={...base,tabs:{home:'Bugün',notes:'Notlar',todos:'İşler',timer:'Sayaç',badges:'Rozetler',budget:'Bütçe',settings:'Ayarlar'},tagline:'',sticky:'',subs:{},timerIdle:'Bir küçük adım daha.',timerRunning:'Odak zamanı',timerPaused:'Duraklatıldı',timerStart:'Başlat',quickFocus:'25 dk odaklan'};return {'stars-hollow':shared,scranton:{...shared}};}
 function timer(t){if(active()&&mounted){$('tv-timer-reset').hidden=t.status!=='idle';const len=$('timer-digits').textContent.length;$('timer-digits').style.setProperty('--tv-digits',len>7?'32px':len>5?'40px':'56px');}}
 window.NeroTVThemes={update,leave,skins,arrange,timer};
})();
