/* Trusted local catalogue; the live desktop character remains animated. */
window.createWardrobePanel=function({root,select,play,toggle}){
 const catalog=window.NeroWardrobe;let category=catalog.categories[0].id,last='',snapshot;
 root.innerHTML='<h2>Nero’nun dolabı</h2><p data-status></p><div class="wardrobe-tabs" data-tabs></div><div class="wardrobe-controls"><button data-choice="auto">Otomatik kıyafet</button><button data-choice="none">Kıyafetleri çıkar</button></div><div class="wardrobe-grid" data-grid></div><label><input type="checkbox" data-animation> Nero’nun yeni hareketleri</label><details><summary>Hareketleri dene</summary><div class="wardrobe-tabs" data-motions></div></details>';
 const names={laugh:'Gülmesini bastır',think:'Düşün',peek:'Merakla bak',balance:'Dengesini toparla',victory:'Minik zafer',tap:'Tempo tut',cross:'Kollarını kavuştur',glance:'Etrafına bak',pet:'Sevilme',shy:'Utan',yawn:'Esne',nod:'Uykulu baş hareketi',dance:'Dans et'};
 for(const [id,label] of Object.entries(names)){const b=document.createElement('button');b.dataset.motion=id;b.textContent=label;root.querySelector('[data-motions]').append(b);}
 root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){category=b.dataset.tab;last='';update(snapshot);}if(b.dataset.choice!==undefined){b.disabled=true;try{await select(b.dataset.choice);}finally{last='';update(snapshot);}}if(b.dataset.motion)await play(b.dataset.motion);});
 root.querySelector('[data-animation]').addEventListener('change',e=>toggle(e.target.checked));
 function update(state){if(!state)return;snapshot=state;const s=state.settings,key=JSON.stringify([category,s.wardrobeOutfit,state.wardrobeSupported,state.wardrobeLocked,s.characterAnimations,state.activeWardrobeOutfit]);if(last===key)return;last=key;
 const disabled=!state.wardrobeSupported||state.wardrobeLocked;root.querySelector('[data-status]').textContent=!state.wardrobeSupported?'Bu tema Nero kıyafetlerini desteklemiyor. Varsayılan Nero temasını seç.':state.wardrobeLocked?'Doğum günü kıyafeti bugün otomatik olarak kullanılıyor.':`Seçili: ${catalog.items.find(i=>i.id===s.wardrobeOutfit)?.name||({none:'Kıyafetsiz',auto:'Otomatik'}[s.wardrobeOutfit]||'Otomatik')}`;
 const tabs=root.querySelector('[data-tabs]');tabs.replaceChildren();for(const c of catalog.categories){const b=document.createElement('button');b.dataset.tab=c.id;b.textContent=c.name;b.setAttribute('aria-pressed',String(c.id===category));tabs.append(b);}
 const grid=root.querySelector('[data-grid]');grid.replaceChildren();for(const item of catalog.items.filter(i=>i.category===category)){const b=document.createElement('button');b.dataset.choice=item.id;b.disabled=disabled;b.setAttribute('aria-pressed',String(s.wardrobeOutfit===item.id));const img=document.createElement('img');img.src=`../character/wardrobe/${item.id}.svg`;img.alt='';img.loading='lazy';const label=document.createElement('span');label.textContent=item.name;b.append(img,label);grid.append(b);}
 root.querySelectorAll('.wardrobe-controls button').forEach(b=>{b.disabled=disabled;b.setAttribute('aria-pressed',String((s.wardrobeOutfit||'auto')===b.dataset.choice));});root.querySelector('[data-animation]').checked=s.characterAnimations!==false;root.querySelectorAll('[data-motion]').forEach(b=>b.disabled=!state.wardrobeSupported||s.characterAnimations===false);
 }
 return {update};
};
