name: Özellik önerisi
description: Nero için yeni bir fikir öner
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Hangi ihtiyacı çözüyor?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Önerilen çözüm
    validations:
      required: true
