'use strict';
const {randomUUID}=require('node:crypto');
const dayKey=(time=Date.now())=>{const d=new Date(time);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const clean=(value,max=100)=>String(value??'').trim().slice(0,max);
const check=(ok,msg)=>{if(!ok)throw Error(msg);};
function checklist(body){const lines=String(body||'').split('\n');const tasks=lines.flatMap((line,index)=>{const m=/^\s*[-*] \[([ xX])\] (.*)$/.exec(line);return m?[{index,done:m[1].toLowerCase()==='x',text:m[2]}]:[];});return {total:tasks.length,done:tasks.filter(t=>t.done).length,tasks};}
class Productivity{
 constructor({store,notes,todos,jar,timer,changed=()=>{}}){Object.assign(this,{store,notes,todos,jar,timer,changed});this.pending=null;this.current=null;const s=store.get();s.sessions ||= [];s.preferences ||= {};for(const row of s.sessions)if(['running','paused'].includes(row.status)){row.status='interrupted';row.endedAt=Date.now();}store.set(s);
  timer.on('started',()=>this.started());timer.on('paused',()=>this.track('paused'));timer.on('resumed',()=>this.track('running'));timer.on('tick',()=>{if(this.current&&Date.now()-(this.persistedAt||0)>30000)this.track(timer.status);});timer.on('done',()=>this.finish('completed'));timer.on('cancelled',p=>this.finish('cancelled',p.minutes*60000*p.progress));
 }
 snapshot(){return {sessions:this.store.get().sessions.map(s=>({...s})),preferences:this.store.get().preferences,jar:this.jar.get().items||[]};}
 meta(kind,input){const source=kind==='note'?this.notes:this.todos;const row=source.get().find(r=>r.id===input.id);check(row,'Kayıt bulunamadı.');if(kind==='note'){if('pinned' in input)row.pinned=!!input.pinned;if('tag' in input)row.tag=clean(input.tag,40);if('color' in input){check(['paper','yellow','pink','blue','green'].includes(input.color),'Renk geçersiz.');row.color=input.color;}}else{if('bucket' in input){check(['today','later'].includes(input.bucket),'Bölüm geçersiz.');row.bucket=input.bucket;}if('priority' in input){check(['normal','high','low'].includes(input.priority),'Öncelik geçersiz.');row.priority=input.priority;}if('tag' in input)row.tag=clean(input.tag,40);if('plannedDurationMin' in input){const n=Number(input.plannedDurationMin);check(Number.isInteger(n)&&n>=0&&n<=10080,'Süre geçersiz.');row.plannedDurationMin=n||null;}}
 source.set(source.get());this.changed();return structuredClone(row);}
 reorder(ids,bucket){check(Array.isArray(ids)&&ids.length<=10000,'Sıralama geçersiz.');const all=this.todos.get(),map=new Map(all.map(t=>[t.id,t]));check(ids.every(id=>map.has(id))&&new Set(ids).size===ids.length,'İş sıralaması geçersiz.');if(bucket){check(['today','later'].includes(bucket),'Bölüm geçersiz.');for(const id of ids)map.get(id).bucket=bucket;}this.todos.set([...ids.map(id=>map.get(id)),...all.filter(t=>!ids.includes(t.id))]);this.changed();return true;}
 preference(key,value){check(['todoFilters','reportFilters','moodboardMode','lessonPosition','toolInputs','hideAmounts'].includes(key),'Tercih geçersiz.');check(JSON.stringify(value).length<=20000,'Tercih çok uzun.');this.store.get().preferences[key]=structuredClone(value);this.store.set(this.store.get());return value;}
 prepare(id){if(!id){this.pending=null;return;}const t=this.todos.get().find(t=>t.id===id&&!t.done&&!t.archivedAt&&(t.bucket||'today')==='today');check(t,'Bugün listesindeki açık bir işi seç.');check(!t.stopwatchStartedAt,'İş kronometresini duraklatıp odak sayacını başlat.');this.pending={todoId:t.id,todoName:t.text};}
 started(){if(this.current)this.finish('interrupted');const snap=this.timer.snapshot(),row={id:randomUUID(),...this.pending,label:snap.label,day:dayKey(),startedAt:Date.now(),endedAt:null,plannedMs:snap.durationMs,elapsedMs:0,status:'running'};this.pending=null;this.current=row;this.store.get().sessions.unshift(row);this.store.get().sessions=this.store.get().sessions.slice(0,5000);this.store.set(this.store.get());this.changed();}
 track(status){if(!this.current)return;const s=this.timer.snapshot();this.current.elapsedMs=Math.max(0,Math.min(this.current.plannedMs,this.current.plannedMs-s.remainingMs));this.current.status=status;this.persistedAt=Date.now();this.store.set(this.store.get());if(status==='paused')this.changed();}
 finish(status,elapsed){if(!this.current)return;const row=this.current;row.elapsedMs=Math.round(Math.max(0,Math.min(row.plannedMs,elapsed??(status==='completed'?row.plannedMs:row.elapsedMs))));row.status=status;row.endedAt=Date.now();const todo=this.todos.get().find(t=>t.id===row.todoId);if(todo){todo.actualDurationMs=(todo.actualDurationMs||0)+row.elapsedMs;todo.focusCreditedMin=(todo.focusCreditedMin||0)+row.elapsedMs/60000;this.todos.set(this.todos.get());}this.current=null;this.store.set(this.store.get());this.changed();}
 randomMemory(){const data=this.jar.get(),items=data.items||[];if(!items.length)return null;let pool=items.filter(i=>!i.shown);if(!pool.length){for(const item of items)item.shown=false;pool=items;}const avoid=pool.filter(i=>i.id!==data.lastShownId);if(avoid.length)pool=avoid;const item=pool[Math.floor(Math.random()*pool.length)];item.shown=true;data.lastShownId=item.id;this.jar.set(data);return {...item,onlyMemory:items.length===1};}
}
module.exports={Productivity,checklist,dayKey};
