const path=require('path'),fs=require('fs'),http=require('http');
function setupRestaurant({app,BrowserWindow,ipcMain}){
 let win=null,server=null,start=null;
 const root=path.resolve(__dirname,'../renderer/restaurant');
 async function ensureServer(){if(start)return start;start=new Promise((resolve,reject)=>{server=http.createServer((request,response)=>{try{const url=new URL(request.url,'http://127.0.0.1'),name=decodeURIComponent(url.pathname==='/'?'/restaurant-layout.html':url.pathname),file=path.resolve(root,'.'+name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){response.writeHead(404);response.end();return;}const mime={'.js':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.woff2':'font/woff2','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'Content-Type':mime,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});fs.createReadStream(file).pipe(response);}catch{response.writeHead(400);response.end();}});server.once('error',error=>{start=null;reject(error);});server.listen(8193,'127.0.0.1',()=>resolve('http://127.0.0.1:8193/restaurant-layout.html'));});return start;}
 async function open(){if(win&&!win.isDestroyed()){if(win.isMinimized())win.restore();win.show();win.focus();return true;}const url=await ensureServer();win=new BrowserWindow({width:1400,height:930,minWidth:900,minHeight:650,title:'Nero · Ezgi’s Krab Shack',backgroundColor:'#d9e5dc',autoHideMenuBar:true,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});win.webContents.setWindowOpenHandler(({url})=>{const allowed=/^http:\/\/127\.0\.0\.1:8193\/(?:quest-review|price-review|unlock-tree)\.html(?:[?#].*)?$/.test(url);return allowed?{action:'allow',overrideBrowserWindowOptions:{width:1250,height:850,autoHideMenuBar:true,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}}}:{action:'deny'};});win.webContents.on('will-navigate',(event,next)=>{if(!next.startsWith('http://127.0.0.1:8193/'))event.preventDefault();});win.on('closed',()=>{win=null;});await win.loadURL(url);return true;}
 ipcMain.handle('restaurant:open',()=>open());
 app.on('before-quit',()=>{if(server)server.close();});
 return{open,getWindow:()=>win,close:()=>{if(win&&!win.isDestroyed())win.close();}};
}
module.exports={setupRestaurant};
