import React, { createContext, useContext, useLayoutEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { flushSync } from 'react-dom';
import { createChart, refreshLegacyCharts, inspectCharts, palette } from './charts';
import { inBase, dailyFlow, scheduledFlow } from './data';

const Context = createContext(null);
const useFinance = () => useContext(Context);
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const monthLabel = month => new Intl.DateTimeFormat('tr-TR', { month: 'short' }).format(new Date(month.slice(0, 7) + '-01T12:00:00'));
function Button({ action, id = '', className = '', children, ...props }) { return <button type="button" data-budget-action={action} data-id={id} className={className} {...props}>{children}</button>; }
function Icon({ name, tone = '' }) { const c = useFinance(); return <span className={'px-icon ' + tone} aria-hidden="true" dangerouslySetInnerHTML={{ __html: c.icon(name) }} />; }
function Html({ html, className = '', id }) {
  const ref = useRef();
  useLayoutEffect(() => { ref.current.innerHTML = html; refreshLegacyCharts(ref.current); }, [html]);
  return <div ref={ref} className={className} id={id} />;
}
function ChartCanvas({ kind, rows, className = '', label, ...props }) {
  const ref = useRef(); const c = useFinance();
  useLayoutEffect(() => createChart(ref.current, { kind, rows, format: c.currency, ...props }), [kind, JSON.stringify(rows), props.selected, props.focus]);
  return <div className={'px-chart ' + className}><canvas ref={ref} className="px-react-chart" role="img" aria-label={label} /></div>;
}
function Heading({ children, action, label = 'Tümü', id }) { return <div className="px-section-heading"><h3>{children}</h3>{action && <Button action={action} id={id} className="px-link">{label}</Button>}</div>; }
function Empty({ children, action, label }) { return <div className="px-empty"><Icon name="wallet" /><p>{children}</p>{action && <Button action={action} className="px-primary">{label}</Button>}</div>; }
function Progress({ value, max, label }) { const percentage = max > 0 ? Math.max(0, Math.min(100, value / max * 100)) : 0; return <div className="px-progress" role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(percentage)}><span style={{ width: percentage + '%' }} /></div>; }
function Legend({ income = true, expense = true, expenseLabel = 'Net gider' }) { return <div className="px-legend">{income && <span><i />Gelir</span>}{expense && <span><i className="purple" />{expenseLabel}</span>}</div>; }
function Flow({ monthly = false }) {
  const c = useFinance(), v = c.view, history = v.trend.slice(-c.range);
  const daily = !monthly && history.filter(r => r.income || r.netExpense).length < 2;
  const rows = daily ? dailyFlow(v, c.month) : history.map(r => ({ ...r, label: monthLabel(r.month) }));
  const index = Math.max(0, Math.min(rows.length - 1, c.cursor ?? rows.length - 1));
  const select = i => document.querySelector(`[data-budget-action="pb-chart-month"][data-id="${i}"]`)?.click();
  return <div className="px-flow"><div className="px-chart-overline"><span>{daily ? 'Günlük para akışı' : 'Gelir ve gider'}</span><span>{daily ? 'Bu ay' : c.range + ' ay'}</span></div>
    <ChartCanvas kind="line" rows={rows} selected={index} focus={c.focus} onSelect={select} label={daily ? 'Gerçekleşen günlük gelir ve net gider' : 'Gerçekleşen aylık gelir ve net gider'} className="px-line-chart" />
    <div className="px-chart-access" aria-label="Grafikte dönem seç">{rows.map((r, i) => <Button key={r.month} action="pb-chart-month" id={i} className="px-chart-period" aria-pressed={index === i} aria-label={`${r.month}: gelir ${c.currency(r.income)}, net gider ${c.currency(r.netExpense)}`} />)}</div>
    {rows[index] && <Button action="chart-records" id={rows[index].month} className="px-link">{rows[index].month} · İlgili işlemleri aç</Button>}
    <div className="px-flow-footer"><Legend income={c.focus !== 'expense'} expense={c.focus !== 'income'} /><span>{rows[index] && c.currency(rows[index].netExpense)} net gider</span></div>
    {rows.every(r => !r.income && !r.netExpense) && <p className="px-note">Bu dönemde gerçekleşmiş işlem yok.</p>}
  </div>;
}
function Ring({ rows, label, total, sub, action, mini = false }) {
  const c = useFinance();
  return <div className={'px-ring-block ' + (mini ? 'mini' : '')}><div className="px-ring"><ChartCanvas kind="ring" rows={rows} format={mini ? n => n + ' ders' : c.currency} label={`${label}: ${total}`} /><div className="px-ring-center"><small>{label}</small><strong>{total}</strong><span>{sub ?? (rows.some(r => r.amount > 0) ? rows.filter(r => r.amount > 0).length + ' hedef' : 'Henüz birikim yok')}</span></div></div>
    {action && <div className="px-ring-key">{rows.map((r, i) => r.amount > 0 && <Button key={r.id} action={action} id={r.id} className="px-key-row"><i style={{ background: palette[i % palette.length] }} /><span>{r.name}</span><b>{c.currency(r.amount)}</b></Button>)}</div>}</div>;
}
function SummaryPair({ planned = false }) {
  const c = useFinance(), v = c.view;
  return <div className="px-summary-pair"><Button action={planned ? 'planned-income' : 'monthly-income'} className="px-summary"><Icon name="income" tone="lime" /><strong>{c.currency(planned ? v.cashFlow.expected : v.summary.income)}</strong><small>{planned ? 'Beklenen gelir' : 'Bu ay gelir'}</small></Button><Button action={planned ? 'month-payments' : 'monthly-expense'} className="px-summary"><Icon name="expense" tone="purple" /><strong>{c.currency(planned ? v.cashFlow.payable : v.summary.netExpense)}</strong><small>{planned ? 'Bu ay ödenecek' : 'Bu ay net gider'}</small></Button></div>;
}
function Insight() {
  const c = useFinance(), v = c.view, diff = v.summary.netExpense - v.previous.netExpense;
  const text = v.previous.netExpense > 0 ? `${diff > 0 ? '+' : diff < 0 ? '−' : ''}${Math.abs(diff / v.previous.netExpense * 100).toLocaleString('tr-TR', { maximumFractionDigits: 1 })}%` : c.currency(v.summary.netExpense);
  return <Button action="monthly-expense" className="px-insight"><span><strong>{text}</strong><small>{v.previous.netExpense > 0 ? diff > 0 ? 'Önceki aya göre daha fazla harcama' : diff < 0 ? 'Önceki aya göre daha az harcama' : 'Önceki aya göre aynı harcama' : 'Bu ay gerçekleşen harcaman · önceki ay kayıt yok'}</small></span><Icon name="northeast" /></Button>;
}
function Balance() { const c = useFinance(); return <Button action="tab-accounts" className="px-balance"><span>Mevcut paran</span><strong>{c.currency(c.view.cashFlow.available)}</strong><small>Banka ve nakit toplamı</small></Button>; }
function CashForecast() {
  const c = useFinance(), f = c.view.cashFlow;
  return <section className="px-panel px-forecast"><Heading>Nakit görünümü</Heading><div className="px-forecast-total"><small>Ödemeler sonrası</small><strong>{c.currency(f.afterPayments)}</strong></div><div className="px-mini-metrics">{[['planned-income', 'Beklenen gelir', f.expected], ['month-payments', 'Ödenecek', f.payable], ['installments', 'Taksit borcu', f.installmentDebt]].map(([action, label, amount]) => <Button key={action} action={action}><small>{label}</small><b>{c.currency(amount)}</b></Button>)}</div><p className="px-note">Beklenen gelir tahmine eklenmez.</p></section>;
}
function Overview() {
  const c = useFinance(), v = c.view;
  const latest = v.transactions.filter(t => t.date.startsWith(c.month) && t.date <= v.today && t.type !== 'transfer' && (c.focus === 'income' ? t.type === 'income' : c.focus === 'expense' ? ['expense', 'refund'].includes(t.type) : true)).sort(c.sortNewest).slice(0, 4);
  return <div className="px-dashboard"><section className="px-analytics"><div className="px-pills">{[['all', 'Tümü'], ['income', 'Gelir'], ['expense', 'Gider'], ['savings', 'Birikim']].map(([id, label]) => <Button key={id} action="pb-focus" id={id} className={'px-pill ' + (c.focus === id ? 'selected' : '')} aria-pressed={c.focus === id}>{label}</Button>)}</div><Balance /><Flow /><SummaryPair /><Insight /></section>
    <aside className="px-dashboard-aside"><CashForecast /><Heading action="tab-reports" label="Raporlar">Son işlemler</Heading>{latest.length ? <Html html={latest.map(c.transactionRow).join('')} className="px-ledger" /> : <Empty action="new-transaction" label="İşlem ekle">Bu ay henüz işlem yok.</Empty>}<Heading action="tab-plans">Yaklaşan ödemeler</Heading><Html html={c.paymentGroups(v.upcoming.filter(o => o.type !== 'income'), true)} className="px-payments" />{v.missingRates.length > 0 && <p className="budget-warning">Eksik kur bulunan hesaplar toplama dahil değil.</p>}<Html html={c.onboarding()} /></aside></div>;
}
function Transactions() {
  const c = useFinance(), legacy = c.transactions();
  const toolbar = legacy.slice(legacy.indexOf('<div class="budget-toolbar">'), legacy.indexOf('<div class="budget-card budget-filters">'));
  const form = legacy.slice(legacy.indexOf('<div class="budget-card budget-filters">'), legacy.indexOf('<div id="budget-transaction-results">'));
  const search = form.match(/<label>Ara[\s\S]*?<\/label>/)?.[0] || '';
  const list = legacy.slice(legacy.indexOf('<div id="budget-transaction-results">'));
  return <div className="px-page-grid"><section><div className="px-search-row"><Html html={search} /><details className="px-details px-filter-details"><summary>Filtreler</summary><Html html={form.replace(search, '')} /></details></div><Html html={list} className="px-ledger" /><details className="px-details"><summary>Ekle, aktar ve şablonlar</summary><Html html={toolbar} /></details></section><aside><div className="px-panel"><Heading>Bu ayın para akışı</Heading><Flow monthly /><SummaryPair /></div><details className="px-details px-statistics"><summary>Gelir / gider dağılımı</summary><Html id="budget-transaction-statistics" html={['income', 'expense'].includes(c.filters.type) ? c.transactionStatistics(c.filters.type) : ''} /></details></aside></div>;
}
function Accounts() {
  const c = useFinance(), v = c.view;
  const rows = v.accounts.filter(a => !a.archived).map(a => ({ name: a.name, amount: inBase(a.balance, a.currency, v.baseCurrency, v.rates) })).filter(a => a.amount !== null);
  return <><div className="px-actions"><Button action="new-account" className="px-primary">+ Hesap ekle</Button><Button action="new-transfer" className="px-secondary">Transfer</Button><Button action="tools" className="px-secondary">Ayarlar</Button></div><div className="px-page-grid"><section><Balance /><div className="px-account-list">{v.accounts.map((a, i) => <article key={a.id} className={'px-account px-panel ' + (a.archived ? 'budget-archived' : '')} style={{ '--account-accent': palette[i % palette.length] }}><div className="px-account-top"><Icon name={a.type === 'credit' ? 'card' : a.type === 'bank' ? 'bank' : 'wallet'} /><span><h3>{a.name}</h3><small>{{ bank: 'Banka', cash: 'Nakit', credit: 'Kredi kartı' }[a.type]} · {a.currency}{a.archived ? ' · Arşiv' : ''}</small></span><Button action="edit-account" id={a.id} className="px-icon-button" aria-label={a.name + ' hesabını düzenle'}><Icon name="settings" /></Button></div><small className="px-account-caption">{a.type === 'credit' ? 'Toplam kart borcu' : 'Hesap bakiyesi'}</small><strong className="px-account-value">{c.currency(a.type === 'credit' ? Math.max(0, -a.balance) : a.balance, a.currency)}</strong>{a.statement ? <><Progress value={a.statement.debt} max={a.limit} label="Kart limitinin kullanımı" /><div className="px-account-meta"><span>Kullanılabilir limit<b>{c.currency(a.statement.available, a.currency)}</b></span><span>Son ödeme<b>{c.when(a.statement.due)}</b></span></div><Button action="card-payment" id={a.id} className="px-link">Kart ödemesi</Button><details className="px-details"><summary>Ekstre</summary><p>Yaklaşık dönem borcu {c.currency(a.statement.estimatedDue, a.currency)}. Banka ekstresiyle kontrol et.</p></details></> : <div className="px-account-meta"><span>Ayrılan<b>{c.currency(a.reserved, a.currency)}</b></span><span>Serbest<b>{c.currency(a.balance - a.reserved, a.currency)}</b></span></div>}</article>)}</div>{!v.accounts.length && <Empty action="new-account" label="Hesap ekle">Paranın bulunduğu hesabı ekle.</Empty>}</section><aside className="px-panel"><Heading>Hesap karşılaştırması</Heading><ChartCanvas kind="bar" rows={rows} horizontal label="Hesap bakiyeleri, kart borçları negatif gösterilir" className="px-bars" /><p className="px-note">Temel para birimine çevrilir. Kart borcu eksi bakiye olarak görünür.</p><div className="px-actions"><Button action="categories" className="px-link">Kategoriler</Button><Button action="rates" className="px-link">Kurlar</Button></div></aside></div></>;
}
function Savings() {
  const c = useFinance(), v = c.view, goals = v.goals.filter(g => !g.archived);
  const converted = goals.map(g => ({ id: g.id, name: g.name, amount: inBase(g.saved, g.currency, v.baseCurrency, v.rates) }));
  const rows = converted.filter(g => g.amount !== null), total = rows.reduce((n, g) => n + g.amount, 0);
  return <div className="px-savings-grid"><section className="px-savings-main"><Ring rows={rows} label="Birikim dağılımı" total={c.currency(total)} /><p className="px-note">Hedefler arasındaki dağılım; hedef ilerlemesi aşağıdaki çubuklarda gösterilir.</p>{converted.some(g => g.amount === null) && <p className="budget-warning">Eksik kurlu hedefler toplama dahil değil.</p>}<Heading action="new-goal" label="+ Hedef">Birikim planlarım</Heading>{v.goals.map((g, i) => <article className={'px-goal ' + (g.archived ? 'budget-archived' : '')} key={g.id} style={{ '--goal-accent': palette[i % palette.length] }}><div className="px-goal-top"><Icon name="category" /><span><h3>{g.name}</h3><small>{c.account(g.accountId)?.name}</small></span><span className="px-goal-target"><b>{c.currency(g.target, g.currency)}</b><small>{g.deadline ? c.when(g.deadline) : 'Hedef tutarı'}</small></span></div><Progress value={g.saved} max={g.target} label={g.name + ' ilerlemesi'} /><div className="px-goal-bottom"><small>{Math.min(100, g.saved / g.target * 100).toLocaleString('tr-TR', { maximumFractionDigits: 1 })}% · {c.currency(g.saved, g.currency)} birikti</small><Button action="edit-goal" id={g.id} className="px-link">Düzenle</Button>{!g.archived && <Button action="fund-goal" id={g.id} className="px-link">Para ayır</Button>}</div></article>)}{!v.goals.length && <Empty action="new-goal" label="Hedef oluştur">Bir hedef eklediğinde birikim dağılımın burada görünür.</Empty>}<Button action="new-goal" className="px-new-goal">+ Yeni birikim planı</Button><p className="px-note">Ayırdığın para hesap içinde rezervdir; gelir/gider oluşturmaz.</p></section><aside className="px-limits"><Heading action="new-budget" label="+ Limit">Aylık harcama limitleri</Heading>{v.budgets.map((b, i) => <article className="px-goal" key={b.id} style={{ '--goal-accent': palette[i % palette.length] }}><div className="px-goal-top"><Icon name="budgets" /><span><h3>{c.budgetCategory(b.categoryId)}</h3><small>Limit {c.currency(b.limit)}</small></span><Button action="edit-budget" id={b.id} className="px-link">Düzenle</Button></div><Progress value={b.spent} max={b.limit} label="Harcama limiti" /><div className="px-goal-bottom"><small>{c.currency(b.spent)} harcandı</small><b className={b.remaining < 0 ? 'budget-negative' : ''}>{b.remaining < 0 ? 'Aşım ' : 'Kalan '}{c.currency(Math.abs(b.remaining))}</b></div><Button action="delete-budget" id={b.id} className="px-link">Limiti kaldır</Button></article>)}{!v.budgets.length && <Empty action="new-budget" label="Limit ekle">Harcamalarına aylık bir sınır belirle.</Empty>}</aside></div>;
}
function Payments() {
  const c = useFinance(), v = c.view;
  const rows = v.upcoming.filter(o => c.planFilter === 'all' || (c.planFilter === 'income' ? o.type === 'income' : o.type !== 'income'));
  const paid = v.transactions.filter(t => t.planId && t.occurrence?.startsWith(c.month)).sort(c.sortNewest);
  return <><div className="px-actions"><Button action="new-plan" className="px-primary">+ Düzenli işlem</Button><Button action="new-installment" className="px-secondary">+ Taksit</Button><Button action="notification-settings" className="px-icon-button" aria-label="Bildirim ayarları"><Icon name="calendar" /></Button><Button action="installments" className="px-link">Taksit borçları</Button></div><div className="px-page-grid"><section><SummaryPair planned /><Heading>Yaklaşan ödemeler</Heading><label className="px-select-label">Göster<select id="budget-plan-filter" defaultValue={c.planFilter}><option value="all">Tüm planlar</option><option value="income">Beklenen gelirler</option><option value="expense">Bekleyen ödemeler</option></select></label><Html html={c.paymentGroups(rows)} className="px-payments" />{!!v.overdue.length && <details className="px-details"><summary>Gecikmiş kayıtlar · {v.overdue.length}</summary><Html html={c.paymentGroups(v.overdue.filter(o => c.planFilter === 'all' || (c.planFilter === 'income' ? o.type === 'income' : o.type !== 'income')).slice(0, 100))} /></details>}<Heading>Bu ay kaydedilenler</Heading>{paid.map(t => <div className="px-paid" key={t.id}><span><b>{t.payee || t.note}</b><small>{c.when(t.date)} · {c.currency(t.amount, t.currency)}</small></span><Button action="unpay-plan" id={t.planId + '|' + t.occurrence} className="px-link">Geri al</Button></div>)}{!paid.length && <p className="px-note">Kaydedilmiş planlı işlem yok.</p>}</section><aside><section className="px-panel"><Heading>Bu ayın ödeme akışı</Heading><ChartCanvas kind="bar" rows={scheduledFlow(v, c.month)} keys={['income', 'expense']} label="Haftalara göre beklenen gelir ve ödemeler" className="px-bars" /><Legend expenseLabel="Ödeme" /></section><Heading>Düzenli kayıtların</Heading>{v.plans.map(p => <div className="px-goal" key={p.id}><div className="px-goal-top"><Html html={c.brandIcon(p.brandId, p.name, p.type)} /><span><h3>{p.name}</h3><small>{p.auto ? 'Otomatik kayıt' : 'Manuel onay'} · {p.paused ? 'Duraklatıldı' : 'Aktif'}</small></span><Button action="edit-plan" id={p.id} className="px-link">Düzenle</Button></div><div className="px-goal-bottom"><b>{c.currency(p.revisions?.at(-1)?.amount || p.amount, c.account(p.accountId)?.currency)}</b><Button action="pause-plan" id={p.id} className="px-link">{p.paused ? 'Devam ettir' : 'Duraklat'}</Button></div></div>)}</aside></div></>;
}
function Reports() {
  const c = useFinance(), v = c.view;
  const rows = Object.entries(v.summary.categories).filter(([, n]) => n > 0).sort((a, b) => b[1] - a[1]).map(([id, amount]) => ({ id, amount, name: c.category(id)?.name || 'Kategori' }));
  return <><div className="px-page-grid"><section className="px-report-main"><div className="px-pills">{[3, 6, 12].map(n => <Button key={n} action="pb-range" id={n} className={'px-pill ' + (c.range === n ? 'selected' : '')} aria-pressed={c.range === n}>{n} ay</Button>)}</div><div className="px-report-total"><small>Bu ay net gider</small><strong>{c.currency(v.summary.netExpense)}</strong></div><Flow monthly /><SummaryPair /><Insight /><details className="px-details"><summary>Tutarlarla oku</summary><div className="px-data-table">{v.trend.slice(-c.range).map(r => <div key={r.month}><b>{r.month}</b><span>Gelir {c.currency(r.income)}<br />Net gider {c.currency(r.netExpense)}</span></div>)}</div></details></section><aside className="px-panel"><Heading>Harcama dağılımı</Heading><Ring rows={rows} label="Toplam dağılım" total={c.currency(rows.reduce((n, r) => n + r.amount, 0))} sub={rows.length + ' kategori'} action="category-details" />{Object.values(v.summary.categories).some(n => n < 0) && <p className="px-note">İade nedeniyle negatif kategoriler halkaya dahil değildir.</p>}</aside></div><Heading>En büyük harcamalar</Heading><Html html={v.transactions.filter(t => t.type === 'expense' && t.date.startsWith(c.month) && t.date <= v.today).sort((a, b) => b.baseAmount - a.baseAmount).slice(0, 5).map(c.transactionRow).join('')} className="px-ledger" /><details className="px-details"><summary>Aylık değerlendirme</summary><Html html={c.monthlySummary() + c.categoryRows(v.summary.categories)} /></details><div className="px-actions"><Button action="csv-export" className="px-secondary">CSV dışa aktar</Button><Button action="report-pdf" className="px-secondary">PDF raporu</Button></div></>;
}
function Calendar() {
  const c = useFinance(), v = c.view;
  const days = new Date(Number(c.month.slice(0, 4)), Number(c.month.slice(5)), 0).getDate();
  const pad = (new Date(c.month + '-01T12:00:00').getDay() + 6) % 7;
  const events = [...(v.calendarRecorded||[]).map(o=>({...o,kind:'recorded'})),...v.calendar.filter(o => o.date.startsWith(c.month)).map(o => ({ ...o, kind: 'plan' })), ...v.cardDates.filter(card => card.debt > 0).map(card => ({ ...card, kind: 'card' }))];
  return <div className="px-page-grid"><section className="px-calendar-panel"><div className="px-calendar-grid">{['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'].map(day => <small key={day}>{day}</small>)}{Array.from({ length: pad }, (_, i) => <span key={'pad' + i} />)}{Array.from({ length: days }, (_, i) => { const date = c.month + '-' + String(i + 1).padStart(2, '0'); const count = events.filter(e => e.date === date).length; return <Button key={date} action="calendar-day" id={date} className={'px-day ' + (date === v.today ? 'today' : '')} aria-label={`${date}, ${count} kayıt`}>{i + 1}{count > 0 && <i />}</Button>; })}</div><div className="px-panel px-calendar-chart"><Heading>Haftalık ödeme yoğunluğu</Heading><ChartCanvas kind="bar" rows={scheduledFlow(v, c.month)} keys={['income', 'expense']} label="Seçilen ayın haftalık gelir ve ödemeleri" className="px-bars" /></div></section><aside><Heading>Bu ayın bekleyenleri</Heading><Html html={c.paymentGroups(v.calendar.filter(o => o.date.startsWith(c.month)))} className="px-payments" />{v.cardDates.filter(card => card.debt > 0).map(card => <div className="px-goal" key={card.id}><h3>{card.name}</h3><p className="px-note">Son ödeme {c.when(card.date)}</p><Button action="card-payment" id={card.id} className="px-secondary">Kart ödemesi</Button></div>)}</aside></div>;
}
function Academy() {
  const c = useFinance(), v = c.view, h = window.NeroHandbook;
  const read = v.learning.read.length, module = h.modules.find(m => m.id === c.academyModule), last = h.chapters.find(ch => ch.id === v.learning.last);
  return <><div className="px-learning-top"><Ring mini rows={[{ name: 'Okunan', amount: read }, { name: 'Kalan', amount: h.chapters.length - read, color: '#232428' }]} label="" total={Math.round(read / h.chapters.length * 100) + '%'} sub="" /><span><h3>Öğrenme yolculuğun</h3><p>{read} / {h.chapters.length} ders tamamlandı</p></span></div><div className="px-pills">{[['learn', 'Dersler'], ['tools', 'Araçlar'], ['dictionary', 'Sözlük']].map(([id, label]) => <Button key={id} action="academy-area" id={id} className={'px-pill ' + (c.academyArea === id ? 'selected' : '')} aria-pressed={c.academyArea === id}>{label}</Button>)}</div>{c.academyArea !== 'learn' ? <Html html={c.handbook().replace(/<div class="academy-menu"[\s\S]*?<\/div>/, '')} className="px-academy-content" /> : <><div className="px-academy-search"><label>Akademide ara<input id="budget-book-search" type="search" defaultValue={c.bookFilter} placeholder="Kart, enflasyon, birikim…" /></label><label>Göster<select id="budget-book-mode" defaultValue={c.bookMode}><option value="all">Tüm dersler</option><option value="bookmarks">Kaydettiklerim</option><option value="read">Okuduklarım</option></select></label></div>{module ? <Heading action="academy-back" label="Tüm konular">{module.title}</Heading> : <Heading>Konular</Heading>}{last && !module && !c.bookFilter && <div className="px-continue"><small>Kaldığın yerden</small><b>{last.title}</b><Button action="read-chapter" id={last.id} className="px-link">Devam et →</Button></div>}<Html id="budget-chapter-list" html={c.academyList()} className="px-module-grid" /></>}</>;
}
const pages = { overview: Overview, transactions: Transactions, accounts: Accounts, budgets: Savings, plans: Payments, reports: Reports, calendar: Calendar, handbook: Academy };
let root, host;
function mount(node, page, context) {
  if (node !== host) { root?.unmount(); host = node; root = createRoot(node); }
  const Page = pages[page];
  flushSync(() => root.render(<Context.Provider value={context}><div className={'px-screen px-' + page} data-renderer="react-canvas"><Page /></div></Context.Provider>));
  refreshLegacyCharts(node);
}
function detach() { if (root) { flushSync(() => root.unmount()); root = null; host = null; } }
function distribution(values, c) {
  const rows = Object.entries(values).filter(([, n]) => n > 0).sort((a, b) => b[1] - a[1]).map(([id, amount]) => ({ id, amount, name: c.category(id)?.name || 'Kategori' }));
  const total = rows.reduce((n, r) => n + r.amount, 0);
  return `<div class="px-legacy-ring"><div class="px-ring"><div class="px-chart"><canvas data-legacy-ring="${escape(JSON.stringify(rows))}" role="img" aria-label="Kategori dağılımı"></canvas></div><div class="px-ring-center"><small>Toplam dağılım</small><strong>${escape(c.currency(total))}</strong></div></div>${rows.map((r, i) => `<button type="button" class="px-key-row" data-budget-action="category-details" data-id="${escape(r.id)}"><i style="background:${palette[i % 6]}"></i><span>${escape(r.name)}</span><b>${escape(c.currency(r.amount))}</b></button>`).join('')}</div>`;
}
window.NeroPremiumUI = Object.freeze({ mount, detach, distribution, refreshCharts: refreshLegacyCharts, inspectCharts, engine: 'React + CSS + Chart.js Canvas' });
