import * as T from './vendor/three.module.min.js';import {box,ball,cylinder,mat,add} from './models.js';import {nodes} from './city-roads.js';
export function buildDayNight(scene,outside,room,sun,hemisphere,fill){const bulbs=[],pools=[],lights=[];const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,4,64,64,64);g.addColorStop(0,'rgba(255,224,133,.52)');g.addColorStop(.5,'rgba(247,204,109,.18)');g.addColorStop(1,'rgba(247,204,109,0)');x.fillStyle=g;x.fillRect(0,0,128,128);const glow=new T.CanvasTexture(c);
 function lamp(parent,x,z,h=4.2){const p=new T.Group();p.position.set(x,-.25,z);parent.add(p);cylinder(p,.055,.10,h,0x547a85,0,h/2,0);box(p,.65,.06,.12,0x507b84,.27,h,0,.03);const bulb=ball(p,.14,new T.MeshStandardMaterial({color:0xfbe2a2,emissive:0xffce70,emissiveIntensity:0}),.52,h-.15,0,[1,.7,1]);bulbs.push(bulb);const pool=add(parent,new T.PlaneGeometry(9,9),new T.MeshBasicMaterial({map:glow,transparent:true,depthWrite:false}),x+.52,-.217,z);pool.rotation.x=-Math.PI/2;pool.visible=false;pools.push(pool);}
 for(const n of nodes)for(const side of [-1,1])lamp(outside,n.x+side*9,n.z+side*9);
 function warmFixture(parent,x,z,height,color,power,radius){const p=new T.PointLight(color,0,radius,2);p.position.set(x,height-.18,z);p.userData.nightPower=power;parent.add(p);lights.push(p);const fixture=new T.Group();fixture.position.set(x,height,z);parent.add(fixture);cylinder(fixture,.17,.33,.18,0x5b9394,0,0,0);const b=ball(fixture,.17,new T.MeshStandardMaterial({color:0xffedc0,emissive:color,emissiveIntensity:0}),0,-.13,0,[1,.45,1]);bulbs.push(b);const pool=add(parent,new T.PlaneGeometry(radius*.9,radius*.9),new T.MeshBasicMaterial({map:glow,transparent:true,depthWrite:false}),x,parent===room?.06:-.217,z);pool.rotation.x=-Math.PI/2;pool.visible=false;pools.push(pool);}
 for(const x of [-8,0,8])warmFixture(room,x,7,3.25,0xffd493,42,17);
 for(const x of [-7,6])warmFixture(room,x,-10,3.3,0xffe9bc,52,17);
 for(const x of [-14,14])for(const z of [-12,16]){lamp(outside,x,z,4.1);warmFixture(outside,x+.52,z,3.95,0xffd68f,27,12);}
 let state={hour:9,day:1,night:false,time:'09:00'};
 function update(seconds,override=null){const total=9+seconds/60,h=override??total%24;const night=h>=20||h<6;const dusk=h>=18&&h<20?(h-18)/2:h>=5&&h<7?1-(h-5)/2:night?1:0;sun.intensity=2.35*(1-.90*dusk);hemisphere.intensity=1.45*(1-.69*dusk);fill.intensity=.35+.12*dusk;scene.background.set(night?0x183846:0xcfd1ad);scene.fog.color.set(night?0x1c4657:0x9dcfce);for(const bulb of bulbs)bulb.material.emissiveIntensity=night?2.8:0;for(const pool of pools)pool.visible=night;for(const light of lights)light.intensity=night?light.userData.nightPower:0;state={hour:h,day:1+Math.floor(total/24),night,time:String(Math.floor(h)).padStart(2,'0')+':'+String(Math.floor((h%1)*60)).padStart(2,'0')};const clock=document.getElementById('game-clock');if(clock)clock.textContent='Gün '+state.day+' · '+state.time+(night?' · Gece':' · Gündüz');return state;}
 update(0);return{update,snapshot:()=>state};}
