// Recipe quantities and supplier prices are injected; no canonical ingredients are inferred.
export class MaterialStock{
 constructor({materials,recipes,capacity,initial={},spend,unlocked=null}){
  this.materials=new Map(materials.map(m=>[m.id,{...m}]));this.recipes=new Map(Object.entries(recipes));this.capacity=capacity;this.spend=spend;
  this.stock=new Map([...this.materials.keys()].map(id=>[id,initial[id]||0]));this.reservations=new Map();this.deliveries=new Map();this.nextId=0;this.automatic=null;this.unlocked=new Set(unlocked??this.materials.keys());this.granted=new Set();this.bonuses=new Map();
  if(!Number.isInteger(capacity)||capacity<0||[...this.stock.values()].some(n=>!Number.isFinite(n)||!Number.isInteger(n*4)||n<0)||this.used()>capacity)throw Error('Invalid opening stock');
  for(const recipe of this.recipes.values())if(!this.validQuantities(recipe))throw Error('Invalid recipe materials');
 }
 validQuantities(items){return items&&Object.keys(items).length>0&&Object.entries(items).every(([id,n])=>this.materials.has(id)&&Number.isFinite(n)&&Number.isInteger(n*4)&&n>0);}
 used(){return [...this.stock.values()].reduce((a,b)=>a+b,0);}
 incoming(){return [...this.deliveries.values()].reduce((sum,d)=>sum+Object.values(d.items).reduce((a,b)=>a+b,0),0);}
 reserved(id){return [...this.reservations.values()].reduce((sum,r)=>sum+(r.items[id]||0),0);}
 available(id){return (this.stock.get(id)||0)-this.reserved(id);}
 missing(recipeId){const items=this.recipes.get(recipeId);if(!items)return null;return Object.fromEntries(Object.entries(items).map(([id,n])=>[id,Math.max(0,n-this.available(id))]).filter(([,n])=>n>0));}
 reserve(recipeId){const items=this.recipes.get(recipeId);if(!items||Object.keys(items).some(id=>!this.unlocked.has(id))||Object.keys(this.missing(recipeId)).length)return false;const token=++this.nextId;this.reservations.set(token,{recipeId,items:{...items}});return token;}
 release(token){return this.reservations.delete(token);}
 consume(token){const r=this.reservations.get(token);if(!r)return false;for(const [id,n]of Object.entries(r.items))this.stock.set(id,this.stock.get(id)-n);this.reservations.delete(token);return true;}
 quote(items,seconds){if(!this.validQuantities(items)||!Number.isFinite(seconds)||seconds<0)return{allowed:false,reason:'invalid-order'};if(Object.keys(items).some(id=>!Number.isFinite(this.materials.get(id).unitGold)||this.materials.get(id).unitGold<0))return{allowed:false,reason:'price-pending'};if(Object.keys(items).some(id=>!this.unlocked.has(id)))return{allowed:false,reason:'material-locked'};const quantity=Object.values(items).reduce((a,b)=>a+b,0),cost=Object.entries(items).reduce((sum,[id,n])=>sum+n*this.materials.get(id).unitGold,0);if(!Number.isFinite(cost)||cost<0)return{allowed:false,reason:'price-pending'};if(this.used()+this.incoming()+quantity>this.capacity)return{allowed:false,reason:'capacity'};return{allowed:true,cost,quantity,seconds};}
 order(items,seconds){const q=this.quote(items,seconds);if(!q.allowed)return q;const id=this.nextId+1;if(this.spend(q.cost,'supply-'+id)!==true)return{allowed:false,reason:'gold'};this.nextId=id;this.deliveries.set(id,{id,items:{...items},remaining:seconds,cost:q.cost});return{...q,id};}
 configureAutomatic({threshold,target,seconds,enabled=true}){if(!Number.isInteger(threshold)||threshold<0||!Number.isInteger(target)||target<=threshold||!Number.isFinite(seconds)||seconds<0)throw Error('Invalid supply thresholds');this.automatic={threshold,target,seconds,enabled:Boolean(enabled)};}
 unlockMaterial(id){if(!this.materials.has(id)||this.granted.has(id))return false;this.unlocked.add(id);this.granted.add(id);this.bonuses.set(id,100);this.flushBonuses();return true;}
 flushBonuses(){let free=this.capacity-this.used()-this.incoming();for(const [id,remaining]of this.bonuses){const amount=Math.min(free,remaining);if(amount>0){this.stock.set(id,this.stock.get(id)+amount);free-=amount;}if(amount===remaining)this.bonuses.delete(id);else this.bonuses.set(id,remaining-amount);}}
 update(dt){if(!Number.isFinite(dt)||dt<0)throw Error('Invalid stock delta');for(const [id,d]of this.deliveries){d.remaining=Math.max(0,d.remaining-dt);if(d.remaining===0){for(const [material,n]of Object.entries(d.items))this.stock.set(material,this.stock.get(material)+n);this.deliveries.delete(id);}}
  this.flushBonuses();if(this.automatic&&this.automatic.enabled!==false){const {threshold,target,seconds}=this.automatic;for(const id of this.unlocked){const incoming=[...this.deliveries.values()].reduce((n,d)=>n+(d.items[id]||0),0),available=this.available(id)+incoming;if(available<=threshold)this.order({[id]:target-available},seconds);}}
 }
 increaseCapacity(next,cost){if(!Number.isInteger(next)||next<=this.capacity||!Number.isFinite(cost)||cost<0||this.spend(cost,'storage-upgrade')!==true)return false;this.capacity=next;this.flushBonuses();return true;}
 exportState(){return JSON.parse(JSON.stringify({version:1,capacity:this.capacity,stock:Object.fromEntries(this.stock),nextId:this.nextId,unlocked:[...this.unlocked],granted:[...this.granted],bonuses:[...this.bonuses],deliveries:[...this.deliveries.values()],automatic:this.automatic}));}
 restore(state){try{if(!state||state.version!==1||![1000,2000,5000,10000].includes(state.capacity)||!Number.isInteger(state.nextId)||state.nextId<0||!Array.isArray(state.deliveries)||!Array.isArray(state.unlocked)||!Array.isArray(state.granted)||!Array.isArray(state.bonuses))return false;const temporary=new MaterialStock({materials:[...this.materials.values()],recipes:Object.fromEntries(this.recipes),capacity:state.capacity,initial:state.stock,spend:this.spend,unlocked:state.unlocked});for(const id of [...state.unlocked,...state.granted])if(!this.materials.has(id))return false;temporary.granted=new Set(state.granted);for(const [id,n]of state.bonuses){if(!this.materials.has(id)||!temporary.granted.has(id)||!Number.isFinite(n)||n<=0||n>100||!Number.isInteger(n*4))return false;temporary.bonuses.set(id,n);}for(const d of state.deliveries){if(!Number.isInteger(d.id)||d.id<=0||d.id>state.nextId||temporary.deliveries.has(d.id)||!temporary.validQuantities(d.items)||!Number.isFinite(d.remaining)||d.remaining<0||!Number.isFinite(d.cost)||d.cost<0)return false;temporary.deliveries.set(d.id,structuredClone(d));}if(temporary.used()+temporary.incoming()>temporary.capacity)return false;if(state.automatic)temporary.configureAutomatic(state.automatic);this.capacity=temporary.capacity;this.stock=temporary.stock;this.unlocked=temporary.unlocked;this.granted=temporary.granted;this.bonuses=temporary.bonuses;this.deliveries=temporary.deliveries;this.automatic=temporary.automatic;this.nextId=state.nextId;this.reservations.clear();return true;}catch{return false;}}
 snapshot(){return{capacity:this.capacity,bonusPending:[...this.bonuses].map(([id,quantity])=>({id,quantity})),used:this.used(),incoming:this.incoming(),free:this.capacity-this.used()-this.incoming(),materials:[...this.materials.values()].map(m=>({...m,unlocked:this.unlocked.has(m.id),openingGrantReceived:this.granted.has(m.id),stock:this.stock.get(m.id),reserved:this.reserved(m.id),available:this.available(m.id),incoming:[...this.deliveries.values()].reduce((sum,d)=>sum+(d.items[m.id]||0),0)})),reservations:[...this.reservations].map(([token,r])=>({token,...r})),deliveries:[...this.deliveries.values()].map(d=>({...d,items:{...d.items}})),automatic:this.automatic?{...this.automatic}:null};}
}
