import {STATION_LEVELS} from './progression.js';
import {foodCatalog} from './food-models.js';import {foodCatalog2} from './food-models-2.js';import {foodCatalog3} from './food-models-3.js';import {foodCatalog4} from './food-models-4.js';import {foodCatalog5} from './food-models-5.js';import {foodCatalog6} from './food-models-6.js';import {foodCatalog7} from './food-models-7.js';
export function createCatalog(progression,economy,factories){
 const byId=new Map(),prices=new Map(economy.map(p=>[p.model,p]));
 if(progression.recipes.length!==142)throw Error('Expected 142 menu products');
 for(const row of progression.recipes){const price=prices.get(row.model);if(byId.has(row.model)||!price||!factories.has(row.model))throw Error('Incomplete or duplicate product '+row.model);const milestone=STATION_LEVELS[row.station];if(!row.station_decision_required&&(row.station_level!==milestone||row.level<milestone))throw Error('Product precedes its station: '+row.model);
  byId.set(row.model,Object.freeze({id:row.model,name:row.name,level:row.level,station:row.station,stationLevel:row.station_level,opensStation:row.new_station,previousRecipe:row.previous_recipe,stationDecisionPending:row.station_decision_required,seconds:price.seconds,saleGold:price.sale_gold,saleXP:price.sale_xp,unlockGold:price.unlock_gold,balanceStatus:'draft',factory:factories.get(row.model)}));}
 const active=new Set(),done=new Set();function visit(id){if(active.has(id))throw Error('Cyclic menu prerequisite '+id);if(done.has(id))return;const p=byId.get(id);if(!p)throw Error('Missing prerequisite '+id);active.add(id);if(p.previousRecipe){const previous=byId.get(p.previousRecipe);if(!previous||previous.station!==p.station||previous.level>=p.level)throw Error('Invalid recipe ordering '+id);visit(p.previousRecipe);}active.delete(id);done.add(id);}for(const id of byId.keys())visit(id);
 for(let level=2;level<=141;level++)if([...byId.values()].filter(p=>p.level===level).length!==1)throw Error('Invalid per-level product count '+level);
 const startingProducts=[...byId.values()].filter(p=>p.level===1).map(p=>p.id);if(startingProducts.length!==2)throw Error('Expected two starting products');
 return Object.freeze({byId,startingProducts,atLevel:level=>[...byId.values()].filter(p=>p.level===level),inStation:station=>[...byId.values()].filter(p=>p.station===station),build:id=>{const p=byId.get(id);if(!p)throw Error('Unknown menu model '+id);return p.factory();},describe:()=>({products:byId.size,stations:Object.keys(STATION_LEVELS).length,startingProducts:[...startingProducts],pendingStationDecisions:[...byId.values()].filter(p=>p.stationDecisionPending).map(p=>p.id),balanceStatus:'draft'})});
}
const [progression,economy]=await Promise.all(['unlock-progression.json','economy-proposal.json'].map(async name=>{const response=await fetch(new URL(name,import.meta.url));if(!response.ok)throw Error('Menu data failed: '+name);return response.json();}));
const factories=new Map([...foodCatalog,...foodCatalog2,...foodCatalog3,...foodCatalog4,...foodCatalog5,...foodCatalog6,...foodCatalog7].map(([id,,factory])=>[id,factory]));
export const menuCatalog=createCatalog(progression,economy,factories);
