import {installNauticalServiceSigns} from './nautical-service-signs.js';
import {nauticalFactories as N,nauticalHood} from './nautical-stations.js';
import {shackCashCounter,shackDrinkBench,shackPickupCounter,flatPass,counterCondiments} from './shack-counters.js';
import {buildShackInterior} from './shack-interior.js';
import {diningSeats} from './dining-layout.js';
import {sandMaterial} from './seafloor-materials.js';
import * as T from './vendor/three.module.min.js';
import * as B from './models-v2.js';
import * as K from './kitchen-models.js';
import {box,ball,cylinder,ring,mat,add,label,fish,instancedCopies} from './models.js';
import {soupStation} from './food-models-3.js';
import {foodCatalog} from './food-models.js';
import {decorateSeafloor} from './environment-decor.js';
import {buildTownLife} from './town-life.js';
import {buildTraffic} from './traffic-system.js';
import {buildPlannedCity} from './planned-city.js';
import {connectGameSave} from './game-save.js';
import {ActivityClock} from './activity-clock.js';
import {buildRestaurantService} from './restaurant-service.js';
import {buildDayNight} from './day-night.js';
import {sandyFryer} from './sandy-model.js';
import {buildSeaEcology} from './sea-ecology.js';
import {installServiceSigns,installBrandSigns} from './shack-signs.js';
import {bindRestaurantControls} from './restaurant-service-ui.js';
await document.fonts.ready;
await document.fonts.load('900 64px Nunito');
const renderer=new T.WebGLRenderer({canvas:document.getElementById('scene'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.4));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;
const scene=new T.Scene();scene.background=new T.Color(0xcfd1ad);scene.fog=new T.FogExp2(0x9dcfce,.0008);scene.add(new T.HemisphereLight(0xfff6e3,0xb29471,1.45));const sun=new T.DirectionalLight(0xffead0,2.35);sun.position.set(-22,35,30);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-40,right:40,top:40,bottom:-40,near:.1,far:100});sun.shadow.normalBias=.025;sun.shadow.bias=-.00015;scene.add(sun,sun.target);const fill=new T.DirectionalLight(0xb9e7ed,.35);fill.position.set(25,15,-20);scene.add(fill);
const world=new T.Group(),room=new T.Group(),outside=new T.Group();world.add(outside,room);scene.add(world);const placements=[],tables=[],seats=[];
function tube(p,points,c,r=.03){return add(p,new T.TubeGeometry(new T.CatmullRomCurve3(points.map(v=>new T.Vector3(...v))),32,r,8,false),mat(c));}
function text(p,value,w,h,x,y,z,bg='#e8cf9c',fg='#395764'){const s=label(value,w,h,bg,fg);s.position.set(x,y,z);p.add(s);return s;}
function place(id,fn,x,z,y=0,rotation=0,p=room){const o=fn();o.traverse(n=>{if(n.userData.displayFood)n.visible=false;});o.userData.placementId=id;o.position.set(x,y,z);o.rotation.y=rotation;p.add(o);o.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(o);placements.push({id,x,z,y,rotation,min:bounds.min.toArray(),max:bounds.max.toArray()});return o;}
// Reference interior study; simulation coordinates remain unchanged.
buildShackInterior(room);
// Hot equipment is backed against the rear wall, not isolated in the middle.
const hot=[['grill',N.burger,-10.6],['fryer',N.fryer,-8.53],['fish',N.fish,-6.73],['warmer',N.warmer,-5.01],['soup',N.soup,-3.15],['hotdog',N.hotdog,-1.37],['dough',N.dough,.31],['oven',N.oven,2.14],['prep',N.prep,4.27],['cold-prep',N['cold-prep'],6.46],['sink',N.sink,8.33]];for(const [id,fn,x]of hot)place(id,fn,x,-13.2);
for(const x of [-8.53,-6.73,-3.15])place('hood-'+x,()=>{const o=nauticalHood();o.scale.x=.78;return o;},x,-13.30,1.53);
place('fridge',N.fridge,-11.90,-10.15,0,Math.PI/2);place('freezer',N.freezer,-11.90,-7.93,0,Math.PI/2);place('storage',N.storage,-11.9,-5.64,0,Math.PI/2);place('crate',K.ingredientCrate,-10.8,-6.5);
// Continuous preparation counter with drinks on its actual worktop.
const benchXs=[-6.7,-4.35,-2, .35,2.7,5.05];for(const [i,x]of benchXs.entries())place('drink-bench-'+i,shackDrinkBench,x,-7.45);
place('coffee',N.coffee,-7.05,-7.45,1.06);place('grinder',N.grinder,-6.15,-7.45,1.06);place('tea',N.tea,-4.68,-7.45,1.06);place('shake',N.shake,-3.46,-7.45,1.06);place('icecream',N.icecream,-1.88,-7.45,1.06);place('juice',N.juice,.12,-7.45,1.06);place('soda',()=>{const o=N.soda();o.scale.setScalar(.62);return o;},2.55,-7.45,1.06);place('tableware',K.tableware,5.1,-7.45,1.06);place('dessert',N.dessert,8.0,-7.45);place('packing',N.packing,10.57,-7.45);
// Three cashier bays; their queues and the order pickup are separate.
for(const x of [-9.3,-6.8,-4.3]){place('cash-counter-'+x,shackCashCounter,x,-3.7);place('register-'+x,B.cashRegister,x,-3.7,1.07,Math.PI);}
place('pickup-left',shackPickupCounter,1.1,-3.7);place('pickup-right',shackPickupCounter,5.65,-3.7);place('pass',flatPass,1.1,-3.7,1.072);place('tray',K.serviceTray,5.17,-3.7,1.07);place('takeaway-box',K.takeawayBox,6.1,-3.7,1.07);place('takeaway-bag',K.takeawayBag,7.07,-3.7,1.07);
place('counter-condiments',counterCondiments,7.5,-3.85,1.065);
// 4 rows x 5 columns, three barrel seats per table. Middle aisles are 1.5 m or wider.
const tablePoses=[],seatPoses=[];for(let row=0;row<4;row++)for(let col=0;col<5;col++){const x=-9.4+col*4.65,z=-.30+row*3.65;tablePoses.push({x,z});tables.push({id:'table-'+(row*5+col+1),x,z,radius:.80});for(const seat of diningSeats){seatPoses.push({x:x+seat.dx,z:z+seat.dz});seats.push({x:x+seat.dx,z:z+seat.dz,radius:.38});}}
// Dining furniture is created only after purchasing its floor marker.
const spongeActor=place('spongebob',B.sponge,-10.55,-11.62,0,.35),squidActor=place('squidward',B.squid,-6.8,-4.77,0,.05);const sandy=place('sandy',sandyFryer,-8.53,-11.62,0,0);const nero=place('nero',B.nero,6.30,-5.36,0,-.20);if(nero.userData.tray)nero.userData.tray.visible=true;
// Entrance framing and maritime flag line; the roof itself is omitted in the cutaway.
for(const x of [-2.05,2.05])box(room,.19,3.2,.21,0x805832,x,1.6,13.75,.016);box(room,4.5,.18,.24,0x775032,0,3.22,13.75,.018);
// Bikini Bottom exterior: real geometry, sand, coral, rocks and background houses.
box(outside,1000,.18,1000,sandMaterial,0,-.39,1,.04);
box(outside,6.8,.022,9.4,0xc5b98e,0,-.276,18.9,.002);for(let i=0;i<6;i++)box(outside,5.7,.006,.018,0xa9a282,0,-.26,15.6+i*1.5,.001);
function coral(x,z,color){const p=new T.Group();outside.add(p);p.position.set(x,-.25,z);for(let i=0;i<5;i++){const a=(i-2)*.38;const points=[[0,0,0],[Math.sin(a)*.35,.55,0],[Math.sin(a)*.70,1.1+(i%2)*.35,.08]];tube(p,points,color,.09);tube(p,[[Math.sin(a)*.25,.48,0],[Math.sin(a)*.55+.22,.8,.08]],color,.058);}return p;}
for(const [x,z,c]of [[-15,11,0xba81ad],[15,12,0x91aaa8],[-17,-10,0xc09573],[19,-10,0x85a3b4],[16,3,0x938ab0],[-17,3,0xb8b078],[-22,17,0xaf8fac],[24,19,0x7cb6a8]]){coral(x,z,c);ball(outside,.80,0x93a3aa,x+.8,-.15,z-.3,[1.4,.4,1]);}
for(const [x,z]of [[-14,17],[15,17],[-18,-15],[20,-17],[28,10],[-28,2]])for(let i=0;i<5;i++)tube(outside,[[x+(i-2)*.17,-.25,z],[x+(i-2)*.29,.54,z+.13],[x+(i-2)*.19,1.50+(i%2)*.6,z]],i%2?0x779868:0x91ac73,.045);
// Additional saturated reef clusters around the outside boundary; access to the entrance stays clear.
for(let i=0;i<16;i++){const side=i%2?-1:1,x=side*(15.2+(i%4)*2.5),z=-16+Math.floor(i/2)*4.6;coral(x,z,[0xcf86b3,0x8c9dd2,0xc4bd7c,0x80b4a0][i%4]);for(let j=0;j<3;j++){const rock=ball(outside,.24+j*.065,0x8ca9b3,x+.6+j*.42,-.20,z+.3,[1.3,.6,1]);}}
for(const [x,z]of [[-17,15],[18,16],[-24,-8],[27,-6]]){for(let j=0;j<4;j++){const stem=new T.Group();outside.add(stem);stem.position.set(x+j*.24,-.24,z);const points=[];for(let k=0;k<=8;k++)points.push([Math.sin(k*.71+j)*.14,k*.29,Math.cos(k*.58+j)*.09]);tube(stem,points,j%2?0x599f81:0x77b28b,.066);}}
// No upright backdrop or light-ray planes: the sea floor continues across the entire view.
for(let i=0;i<25;i++){const side=i%2?-1:1,x=side*(15+(i%6)*2.4),z=-12+(i%9)*3.6,y=.8+(i%5)*1.20;const bubble=new T.Group();bubble.position.set(x,y,z);outside.add(bubble);const radius=.085+(i%4)*.055;const shell=ball(bubble,radius,new T.MeshStandardMaterial({color:0xb9eff0,transparent:true,opacity:.18,roughness:.20,metalness:.05,depthWrite:false}),0,0,0);shell.castShadow=false;const rim=ring(bubble,radius,.009,new T.MeshBasicMaterial({color:0xd1f4eb,transparent:true,opacity:.65}));rim.rotation.y=.48;rim.castShadow=false;ball(bubble,.019,0xe5fff1,-radius*.33,radius*.47,radius*.75,[1,.60,.3]);}
for(let i=0;i<15;i++){const x=-35+i*4.9,y=2+(i%4)*2.7;const bubble=ring(outside,.17+(i%3)*.08,.022,mat(0xc2eef0,{transparent:true,opacity:.55}),x,y,-29);}
for(const x of [-12,12]){cylinder(outside,.06,.08,4.3,0x6e8d8c,x,1.85,17);tube(outside,[[x,3.96,17],[x+.48,4.28,17],[x+.88,4.0,17]],0x6e8d8c,.065);ball(outside,.25,0xe5d8a3,x+.88,3.94,17,[1,.45,1]);}
const signPost=new T.Group();signPost.position.set(-8,-.25,17.4);outside.add(signPost);cylinder(signPost,.11,.15,5.9,0x9b7245,0,2.95,0);const shell=new T.Shape();shell.moveTo(-1.4,-.55);shell.lineTo(-1.8,.20);shell.quadraticCurveTo(-1.45,1.45,0,1.70);shell.quadraticCurveTo(1.45,1.45,1.8,.20);shell.lineTo(1.4,-.55);shell.closePath();const shellMesh=add(signPost,new T.ExtrudeGeometry(shell,{depth:.16,bevelEnabled:true,bevelSize:.045,bevelThickness:.03,bevelSegments:2,curveSegments:20}),mat(0xd39caa),0,4.80,0);for(let i=0;i<7;i++){const x=-1.35+i*.45;tube(signPost,[[x,5.8,.18],[x*.70,5.2,.20],[x*.3,4.38,.19]],0xb7818e,.027);}text(signPost,'EZGI’S KRAB SHACK',2.6,.46,0,4.80,.22,'#eac4b4','#754e47');
const environment=decorateSeafloor(outside);environment.animate(0);
const city=buildPlannedCity(outside),expandedWorld=city.report,town={buildings:city.buildings,landmarks:city.landmarks,layout:city.layout},construction=city.construction;
const townLife=buildTownLife(outside,{town,construction,environmentProps:environment.props,placements,tables,seats,city});
const traffic=buildTraffic(outside,townLife);const ecology=buildSeaEcology(outside,city);
const testSession=new URL(location.href).searchParams.has('test');
// High-budget fixtures are restricted to explicit automated review URLs.
const reviewFixture=new URL(location.href).searchParams.has('review')&&new URL(location.href).searchParams.get('fixture')==='economy';
const restaurantService=buildRestaurantService(room,{placements,tables,seats,sponge:spongeActor,squid:squidActor,nero,sandy,startingGold:reviewFixture?10000000:60,startingLevel:reviewFixture?100:1});
installNauticalServiceSigns(room);const brandSigns=installBrandSigns(room,outside);bindRestaurantControls(restaurantService);const dayNight=buildDayNight(scene,outside,room,sun,scene.children.find(o=>o.isHemisphereLight),fill);
const textAnisotropy=Math.min(16,renderer.capabilities.getMaxAnisotropy());
scene.traverse(o=>{for(const material of (Array.isArray(o.material)?o.material:[o.material])){if(material?.map?.isCanvasTexture){material.map.anisotropy=textAnisotropy;material.map.needsUpdate=true;}}});
let mode='interior';const camera=new T.OrthographicCamera(-25,25,20,-20,.1,500);
const views={traffic:{target:[-102,1,26],offset:[14,24,30],bounds:[[-120,-.4,12],[-84,5,39]]},centre:{target:[-100,1,-25],offset:[25,45,55],bounds:[[-140,-.4,-80],[-60,25,24]]},construction:{target:[83,1,-127],offset:[14,24,32],bounds:[[69,-.4,-139],[97,9,-113]]},town:{target:[-98,1,105],offset:[22,35,48],bounds:[[-136,-.4,87],[-58,12,134]]},interior:{target:[0,.6,0],offset:[22,36,42],bounds:[[-14,-.4,-14.4],[14,4,16.2]]},overview:{target:[0,1,10],offset:[80,135,165],bounds:[[-183,-.4,-150],[183,30,161]]},kitchen:{target:[0,1,-8.9],offset:[10,22,25],bounds:[[-13,-.1,-14],[13,3.3,-3]]},top:{target:[0,0,0],offset:[0,45,.001],bounds:[[-14,-.1,-14.5],[14,3.3,14.5]]}};
const navigation={zoom:1,x:0,z:0};
function resetNavigation(){navigation.zoom=1;navigation.x=navigation.z=0;}
function render(){const v=views[mode],h=innerHeight,ratio=innerWidth/h;sun.target.position.fromArray(v.target).add(new T.Vector3(navigation.x,0,navigation.z));sun.position.copy(sun.target.position).add(new T.Vector3(-22,35,30));const shadowSize=mode==='overview'?215:mode==='centre'?75:mode==='town'?65:42;Object.assign(sun.shadow.camera,{left:-shadowSize,right:shadowSize,top:shadowSize,bottom:-shadowSize,far:700});sun.shadow.camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false);renderer.setViewport(0,0,innerWidth,h);camera.position.fromArray(v.target).add(new T.Vector3(...v.offset));camera.lookAt(new T.Vector3(...v.target));camera.updateMatrixWorld(true);let extent=1;for(const x of [v.bounds[0][0],v.bounds[1][0]])for(const y of [v.bounds[0][1],v.bounds[1][1]])for(const z of [v.bounds[0][2],v.bounds[1][2]]){const p=new T.Vector3(x,y,z).applyMatrix4(camera.matrixWorldInverse);extent=Math.max(extent,Math.abs(p.y)*1.06,Math.abs(p.x)/ratio*1.05);}extent*=1.14/navigation.zoom;camera.position.add(new T.Vector3(navigation.x,0,navigation.z));camera.updateMatrixWorld(true);camera.left=-extent*ratio;camera.right=extent*ratio;camera.top=extent;camera.bottom=-extent;camera.updateProjectionMatrix();renderer.render(scene,camera);for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===mode));}
for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>{mode=b.dataset.view;resetNavigation();render();});addEventListener('resize',render);
const canvas=renderer.domElement;canvas.style.touchAction='none';canvas.style.cursor='grab';
canvas.addEventListener('wheel',event=>{event.preventDefault();navigation.zoom=T.MathUtils.clamp(navigation.zoom*Math.exp(-event.deltaY*.001),.65,5);render();},{passive:false});
let drag=null,press=null,dragMoved=false;const groundPlane=new T.Plane(new T.Vector3(0,1,0),0),raycaster=new T.Raycaster();
function pointerGround(event){const rect=canvas.getBoundingClientRect();raycaster.setFromCamera(new T.Vector2((event.clientX-rect.left)/rect.width*2-1,1-(event.clientY-rect.top)/rect.height*2),camera);return raycaster.ray.intersectPlane(groundPlane,new T.Vector3());}
canvas.addEventListener('pointerdown',event=>{if(event.button!==0)return;drag=pointerGround(event);press={x:event.clientX,y:event.clientY};dragMoved=false;canvas.setPointerCapture(event.pointerId);canvas.style.cursor='grabbing';});
canvas.addEventListener('pointermove',event=>{if(!drag)return;if(!(event.buttons&1)){endDrag();return;}if(Math.hypot(event.clientX-press.x,event.clientY-press.y)<5&&!dragMoved)return;dragMoved=true;const now=pointerGround(event);if(!now)return;navigation.x=T.MathUtils.clamp(navigation.x+drag.x-now.x,-185,185);navigation.z=T.MathUtils.clamp(navigation.z+drag.z-now.z,-160,165);render();});
function endDrag(){drag=null;press=null;canvas.style.cursor='grab';}canvas.addEventListener('pointerup',event=>{if(press&&!dragMoved){const rect=canvas.getBoundingClientRect();raycaster.setFromCamera(new T.Vector2((event.clientX-rect.left)/rect.width*2-1,1-(event.clientY-rect.top)/rect.height*2),camera);const hit=raycaster.intersectObjects(room.children,true)[0];if(hit){let o=hit.object;while(o&&!o.userData.stationKind)o=o.parent;if(o)restaurantService.selectStation(o.userData.stationKind);}}endDrag();});canvas.addEventListener('pointercancel',endDrag);canvas.addEventListener('lostpointercapture',endDrag);
render();let motion=true,lastFrame=0,simulationTime=0,hiddenAt=document.hidden?performance.now():null,lastBackground=performance.now();const activityClock=new ActivityClock(performance.now());activityClock.hidden=document.hidden;
const saves=connectGameSave(restaurantService,{key:testSession?'ezgis-krab-shack-test-start60-v1':undefined,runtime:()=>activityClock.snapshot(),disabled:new URL(location.href).searchParams.has('review')});if(saves.loadedRuntime.manualPaused){activityClock.setPaused(true,performance.now());motion=false;document.getElementById('pause-motion').textContent='Devam et';document.getElementById('pause-motion').setAttribute('aria-pressed','true');}simulationTime=restaurantService.snapshot().time;dayNight.update(simulationTime);restaurantService.refreshUI();setInterval(()=>{saves.save();const label=document.getElementById('save-status');if(label)label.textContent=saves.snapshot().status;},10000);window.addEventListener('beforeunload',()=>saves.save());window.addEventListener('pagehide',()=>saves.save());document.addEventListener('visibilitychange',()=>{if(document.hidden)saves.save();});
function advance(dt){for(let left=dt;left>1e-8;){const step=Math.min(.05,left);left-=step;simulationTime+=step;townLife.update(step,simulationTime);traffic.update(step);restaurantService.update(step);}environment.animate(simulationTime);ecology.animate(simulationTime);dayNight.update(simulationTime);}
function animateFrame(now){requestAnimationFrame(animateFrame);if(!motion||document.hidden||now-lastFrame<1000/30)return;const dt=activityClock.advance(performance.now());lastFrame=now;advance(dt);render();}requestAnimationFrame(animateFrame);
document.addEventListener('visibilitychange',()=>{const now=performance.now();advance(activityClock.setHidden(document.hidden,now));hiddenAt=document.hidden?now:null;lastBackground=now;lastFrame=now;});
setInterval(()=>{if(document.hidden){advance(activityClock.advance(performance.now()));}},1000);
function setMotion(value){const now=performance.now();advance(activityClock.setPaused(!value,now));motion=Boolean(value);lastFrame=now;const button=document.getElementById('pause-motion');if(button){button.textContent=motion?'Duraklat':'Devam et';button.setAttribute('aria-pressed',String(!motion));}}
document.getElementById('pause-motion')?.addEventListener('click',()=>setMotion(!motion));
window.__neroRestaurantService={save:()=>saves.save(),saveStatus:()=>saves.snapshot(),exportCheckpoint:restaurantService.exportCheckpoint,orderSupplies:restaurantService.orderSupplies,upgradeStorage:restaurantService.upgradeStorage,enableAutoSupply:restaurantService.enableAutoSupply,buyResearchSlot:restaurantService.buyResearchSlot,claimQuest:restaurantService.claimQuest,catalog:restaurantService.catalog,unlockConditions:restaurantService.unlockConditions,snapshot:restaurantService.snapshot,upgradeStation:restaurantService.upgradeStation,buyTable:restaurantService.buyTable,upgradeCashier:restaurantService.upgradeCashier,hireCleaner:restaurantService.hireCleaner,upgradeCleaner:restaurantService.upgradeCleaner,buyCashier:restaurantService.buyCashier,unlockProduct:restaurantService.unlockProduct,selectStation:restaurantService.selectStation,preview:seconds=>{setMotion(false);restaurantService.update(seconds);render();return restaurantService.snapshot();},startProduction:restaurantService.startProduction,spawnCustomer:restaurantService.spawnCustomer,hireWaiter:restaurantService.hireWaiter,audit:seconds=>{setMotion(false);const result=restaurantService.audit(seconds);render();return result;}};
window.__neroTraffic={verifyRespawn:traffic.verifyRespawn,snapshot:traffic.snapshot,audit:seconds=>{setMotion(false);const result=traffic.audit(seconds);render();return result;}};
window.__neroRestaurantLayout={ready:true,previewLighting:hour=>{setMotion(false);dayNight.update(simulationTime,hour);render();return dayNight.snapshot();},auditTown:seconds=>{motion=false;const result=townLife.audit(seconds);render();return result;},previewTown:seconds=>{motion=false;const result=townLife.preview(seconds);render();return result;},setMotion,previewEnvironment:time=>{motion=false;environment.animate(time);render();return environment.snapshot();},view:m=>{if(!views[m])throw Error('Unknown view');mode=m;resetNavigation();render();},navigate:({zoom=1,x=0,z=0})=>{navigation.zoom=T.MathUtils.clamp(zoom,.65,5);navigation.x=T.MathUtils.clamp(x,-185,185);navigation.z=T.MathUtils.clamp(z,-160,165);render();},report:()=>({mode,world:expandedWorld,town,construction,townLife:townLife.report(),traffic:traffic.snapshot(),service:restaurantService.snapshot(),ecology:ecology.snapshot(),brandSigns,clock:{...dayNight.snapshot(),...activityClock.snapshot(),paused:!motion,backgroundLimitSeconds:3600,backgroundPaused:document.hidden&&hiddenAt!==null&&(performance.now()-hiddenAt)>=3600000},navigation:{...navigation,extent:camera.top},uprightBackdrop:false,environment:environment.counts,decorProps:environment.props,environmentState:environment.snapshot(),tables:tables.length,seats:seats.length,placements,finite:placements.every(p=>[...p.min,...p.max].every(Number.isFinite)),aisleBetweenTableRows:3.65-1.6,aisleBetweenSeatColumns:4.65-2*(1.14+.38),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles})};

