import {nauticalFactories as N,nauticalHood} from './nautical-stations.js';
import {krabsCleaner} from './staff-prototypes.js';
import {shackCashCounter,shackPickupCounter,shackDrinkBench,flatPass} from './shack-counters.js';
import * as T from './vendor/three.module.min.js';
import {sandyFryer} from './sandy-model.js';
import {shackSign} from './shack-signs.js';
import {catalog as initialCatalog} from './models-v2.js';
import {kitchenCatalog} from './kitchen-models.js';
import {foodCatalog} from './food-models.js';
import {foodCatalog2} from './food-models-2.js';
import {foodCatalog3,soupEquipmentCatalog} from './food-models-3.js';
import {foodCatalog4} from './food-models-4.js';
import {foodCatalog5} from './food-models-5.js';
import {foodCatalog6} from './food-models-6.js';
import {foodCatalog7,toyCatalog} from './food-models-7.js';
import {buildingCatalog2} from './buildings-2.js';
import {buildingCatalog3} from './buildings-3.js';
import {buildingCatalog4} from './buildings-4.js';
import {buildingCatalog5} from './buildings-5.js';
import {buildingCatalog6} from './buildings-6.js';
import {vehicleCatalog} from './vehicle-models.js';
const catalog=[['sandy-chef','Sandy · patates aşçısı',sandyFryer,'character'],['mr-krabs','Bay Yengeç · temizlik',krabsCleaner,'character'],['shack-sign','Ezgi’s Krab Shack · tabela',shackSign,'sign'],...initialCatalog,...kitchenCatalog,...foodCatalog,...foodCatalog2,...foodCatalog3,...soupEquipmentCatalog,...foodCatalog4,...foodCatalog5,...foodCatalog6,...foodCatalog7,...toyCatalog,...buildingCatalog2,...buildingCatalog3,...buildingCatalog4,...buildingCatalog5,...buildingCatalog6,...vehicleCatalog].map(([id,name,build,type])=>[id,name,({grill:N.burger,hood:nauticalHood,fridge:N.fridge,prep:N.prep,sink:N.sink,pass:flatPass,'cash-counter':shackCashCounter,'pickup-counter':shackPickupCounter,'drink-machine':N.soda,fryer:N.fryer,warmer:N.warmer,'fish-station':N.fish,oven:N.oven,'dough-bench':N.dough,'hotdog-station':N.hotdog,'cold-prep':N['cold-prep'],'shake-machine':N.shake,'coffee-machine':N.coffee,'coffee-grinder':N.grinder,'tea-boiler':N.tea,'icecream-machine':N.icecream,'juice-machine':N.juice,'dessert-case':N.dessert,freezer:N.freezer,'storage-rack':N.storage,'packing-bench':N.packing,'drink-bench':shackDrinkBench,'soup-station':N.soup})[id]||build,type]);
await document.fonts.ready;
const $=id=>document.getElementById(id),views=[],cache=new Map();let current=0;
function build(id){if(!cache.has(id)){const item=catalog.find(a=>a[0]===id);const object=item[2]();object.updateMatrixWorld(true);cache.set(id,object);}return cache.get(id);}
function stats(object){let meshes=0,triangles=0;object.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;}});return{meshes,triangles:Math.round(triangles),animationNodes:object.userData.animationNodes||[]};}
function makeView(canvas,angle){const renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;const scene=new T.Scene();scene.background=new T.Color(0xe2e8e4);const camera=new T.OrthographicCamera(-2,2,2,-2,.01,100);scene.add(new T.HemisphereLight(0xfff6dd,0x849da5,1.8));const light=new T.DirectionalLight(0xfff3de,2.6);light.position.set(-3,6,7);light.castShadow=true;light.shadow.mapSize.set(1024,1024);light.shadow.camera.left=-4;light.shadow.camera.right=4;light.shadow.camera.top=5;light.shadow.camera.bottom=-5;light.shadow.normalBias=.012;light.shadow.bias=-.0002;scene.add(light);const fill=new T.DirectionalLight(0xc3e8f1,.8);fill.position.set(4,3,-4);scene.add(fill);const plane=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:0xe2e8e4,roughness:1}));plane.rotation.x=-Math.PI/2;plane.receiveShadow=true;plane.position.y=-.025;scene.add(plane);return{canvas,renderer,scene,camera,angle,object:null};}
function draw(view,object){if(view.object)view.scene.remove(view.object);view.object=object;view.scene.add(object);object.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(object),center=bounds.getCenter(new T.Vector3());const w=view.canvas.clientWidth||470,h=view.canvas.clientHeight||540;view.renderer.setSize(w,h,false);const ratio=w/h;const pos=view.angle==='front'?new T.Vector3(0,.025,7):view.angle==='side'?new T.Vector3(7,.025,0):new T.Vector3(4.6,4.8,7);const distance=Math.max(8,bounds.getSize(new T.Vector3()).length()*1.5);view.camera.near=.01;view.camera.far=distance*4+100;view.camera.position.copy(center).add(pos.normalize().multiplyScalar(distance));view.camera.lookAt(center);view.camera.updateMatrixWorld(true);let extent=object.name.startsWith('food-')?.50:.18;for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const p=new T.Vector3(x,y,z).applyMatrix4(view.camera.matrixWorldInverse);extent=Math.max(extent,Math.abs(p.y)*1.17,Math.abs(p.x)/ratio*1.13);}view.camera.left=-extent*ratio;view.camera.right=extent*ratio;view.camera.top=extent;view.camera.bottom=-extent;view.camera.updateProjectionMatrix();view.renderer.render(view.scene,view.camera);}
for(const angle of ['front','side','game'])views.push(makeView($(angle),angle));
for(const item of catalog){const opt=document.createElement('option');opt.value=item[0];opt.textContent=item[1];$('assets').append(opt);}
function show(id){current=catalog.findIndex(a=>a[0]===id);if(current<0)throw Error('Unknown model '+id);document.body.classList.remove('sheet');const item=catalog[current],object=build(id),s=stats(object);$('title').textContent=item[1];$('stats').textContent=`${s.triangles.toLocaleString('tr-TR')} üçgen · gerçek model V2`;$('assets').value=id;for(const view of views)draw(view,object.clone(true));return s;}
$('assets').addEventListener('change',e=>show(e.target.value));$('prev').addEventListener('click',()=>show(catalog[(current+catalog.length-1)%catalog.length][0]));$('next').addEventListener('click',()=>show(catalog[(current+1)%catalog.length][0]));addEventListener('resize',()=>{if(!document.body.classList.contains('sheet'))show(catalog[current][0]);});
function exportModel(id){const obj=build(id),saved=[];obj.traverse(o=>{saved.push([o,o.userData]);o.userData={};});let result;try{result=obj.toJSON();}finally{for(const [o,data]of saved)o.userData=data;}return result;}
const sheetViews=[];
function sheet(ids,title){document.body.classList.add('sheet');$('title').textContent=title;$('stats').textContent='Gerçek motor görüntüleri · V2 onay taslağı';for(const v of sheetViews){v.renderer.dispose();v.renderer.forceContextLoss();}sheetViews.length=0;$('contact-sheet').replaceChildren();for(const id of ids){const card=document.createElement('article');card.className='sheet-card';const h=document.createElement('h2');h.textContent=catalog.find(a=>a[0]===id)[1];card.append(h);const canvas=document.createElement('canvas');card.append(canvas);$('contact-sheet').append(card);const v=makeView(canvas,'game');sheetViews.push(v);draw(v,build(id).clone(true));}}
show(new URLSearchParams(location.search).get('asset')||'nero');
function focus(id,name,title){show(id);const detail=build(id).getObjectByName(name);if(!detail)throw Error('Missing detail '+name);$('title').textContent=title;$('stats').textContent='Model ayrıntısı · aynı oyun geometrisi';for(const view of views){const object=detail.clone(true);object.position.set(0,0,0);draw(view,object);}}
window.__neroStudio={ready:true,focus,catalog:catalog.map(([id,title,,type])=>({id,title,type})),show,sheet,exportModel,stats:id=>stats(build(id)),validate:id=>{const o=build(id);let finite=true;o.traverse(n=>{if(n.isMesh){for(const x of n.geometry.attributes.position.array)if(!Number.isFinite(x))finite=false;}});const data=exportModel(id),restored=new T.ObjectLoader().parse(data);return{finite,source:stats(o),restored:stats(restored),bounds:new T.Box3().setFromObject(o).getSize(new T.Vector3()).toArray()};}};
