import {bikiniBus,classicBoat,woodBoat,cruiserBoat,setVehiclePose} from './vehicle-models.js';
import {transportStops,transportRoutes,vehiclePolygon,polygonsOverlap,nearVehicle} from './traffic-network.js';
import {nodes,edges,nextNodes,laneChunk,roadAreas} from './city-roads.js';
const mod=(n,l)=>((n%l)+l)%l;
const rectangle=o=>[{x:o.minX,z:o.minZ},{x:o.maxX,z:o.minZ},{x:o.maxX,z:o.maxZ},{x:o.minX,z:o.maxZ}];
export function buildTraffic(outside,townLife){
 const people=townLife.transit,vehicles=[],violations=[],stats={boarded:0,alighted:0,visits:0,maxDwell:0,followYields:0,pedestrianYields:0,junctionYields:0,collisionYields:0,staticYields:0,randomTurns:0,respawns:0};let time=0,nextRequest=2,seed=503;
 const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 const choose=(id,prev)=>{const options=nextNodes(id,prev);return options[Math.floor(random()*options.length)];};
 const junctions=nodes.map(n=>({...n,owner:null,entered:false}));
 const staticObstacles=townLife.nav.obstacles.map(o=>o.radius===undefined?o:{...o,minX:o.x-o.radius,maxX:o.x+o.radius,minZ:o.z-o.radius,maxZ:o.z+o.radius});
 const definitions=[['bus-1',0,.12,bikiniBus,4.0],['bus-2',0,.65,bikiniBus,4.0],['bus-3',1,.35,bikiniBus,3.8],['car-1',0,.35,classicBoat,4.8],['car-2',3,.40,woodBoat,4.5],['car-3',5,.55,cruiserBoat,5.0],['car-4',8,.30,()=>classicBoat(0x78a9c7),4.7],['car-5',13,.45,()=>woodBoat(0x57a8a8),4.4],['car-6',16,.40,()=>cruiserBoat(0xdb9480),4.7],['car-7',1,.32,()=>woodBoat(0xbca36b),4.6],['car-8',4,.68,()=>classicBoat(0x858bc3),4.9],['car-9',10,.30,()=>cruiserBoat(0x90baa3),4.5],['car-10',12,.65,()=>woodBoat(0x9db1c6),4.6]];
 for(const [id,line,phase,fn,maxSpeed]of definitions){const bus=id.startsWith('bus'),edge=edges[line],route=bus?transportRoutes[line]:laneChunk(edge.a,edge.b,choose(edge.b,edge.a)),o=fn(),s=route.length*phase,p=route.point(s);if(bus)o.scale.setScalar(.9);outside.add(o);const v={id,line:bus?line:null,route,o,s,...p,bus,maxSpeed,speed:0,halfWidth:bus?1.242:1.18,leftWidth:bus?1.242:1.18,rightWidth:bus?1.53:1.18,halfLength:bus?2.718:2.55,state:'driving',distance:0,riders:[],capacity:6,doorOpen:0,elapsed:0,stop:null,nextStop:null,transfer:null,visitDone:false,alightDone:false,boardDone:false,lastYield:null,lastProgress:0,progressSinceCheck:0,visitedNodes:new Set()};if(bus)v.nextStop=transportStops.filter(t=>t.line===line).sort((a,b)=>mod(route.stopDistance(a)-s,route.length)-mod(route.stopDistance(b)-s,route.length))[0];o.position.set(p.x,-.25,p.z);o.rotation.y=p.heading;vehicles.push(v);}
 function aheadPoint(v,d){return v.route.point(v.bus?v.s+d:Math.min(v.route.length,v.s+d));}
 people.guard(()=>true); // User-approved cosmetic overlap between vehicles and residents.
 const door=v=>({x:v.x+Math.cos(v.heading)*1.35+Math.sin(v.heading)*1.143,z:v.z-Math.sin(v.heading)*1.35+Math.cos(v.heading)*1.143});
 function staticClear(v,p){const poly=vehiclePolygon(v,p);return !staticObstacles.some(o=>Math.abs((o.minX+o.maxX)/2-p.x)<(o.maxX-o.minX)/2+5&&Math.abs((o.minZ+o.maxZ)/2-p.z)<(o.maxZ-o.minZ)/2+5&&polygonsOverlap(poly,rectangle(o),.08));}
 const routeBlocks=[];
 // Check every straight and junction connector against the same physical obstacles.
 const busShape=vehicles[0];for(const e of edges)for(const [a,b]of [[e.a,e.b],[e.b,e.a]])for(const next of nextNodes(b,a)){const route=laneChunk(a,b,next);for(let s=0;s<route.length;s+=.8){const p=route.point(s);if(!staticClear(busShape,p)&&!routeBlocks.some(r=>r.from===a&&r.to===b&&r.next===next))routeBlocks.push({from:a,to:b,next,x:p.x,z:p.z});}}
 function completeVisit(v){stats.maxDwell=Math.max(stats.maxDwell,v.elapsed);v.elapsed=0;v.stop=null;v.nextStop=transportStops.filter(t=>t.line===v.line&&t.id!==v.nextStop.id)[0];v.state='driving';v.visitDone=false;v.transfer=null;v.boardDone=false;v.alightDone=false;}
 function stopTick(v,dt){v.elapsed+=dt;const d=door(v);v.doorOpen=Math.min(1,v.doorOpen+dt*2.5);
  if(v.transfer){const state=people.state(v.transfer.id);if(v.transfer.kind==='board'&&state==='onbus'){v.riders.push({id:v.transfer.id,from:v.stop.id});stats.boarded++;v.transfer=null;v.boardDone=true;}else if(v.transfer.kind==='alight'){const actor=people.people().find(a=>a.id===v.transfer.id);if(state!=='alighting'||(actor&&!nearVehicle(v,actor,.52))){v.riders=v.riders.filter(a=>a.id!==v.transfer.id);stats.alighted++;v.transfer=null;v.alightDone=true;}}}
  if(v.doorOpen>=.95&&!v.transfer&&!v.visitDone){const rider=v.riders.find(a=>a.from!==v.stop.id);if(!v.alightDone&&rider){if(people.alight(rider.id,v.stop,v.id,d))v.transfer={kind:'alight',id:rider.id};}else{v.alightDone=true;if(!v.boardDone&&v.riders.length<v.capacity&&v.elapsed<2.3){const id=people.waiting(v.stop)[0];if(id!==undefined&&v.elapsed+people.boardTime(id,d)<4.5&&people.board(id,v.id,d))v.transfer={kind:'board',id};else v.boardDone=true;}else v.boardDone=true;}}
  if(v.elapsed>=3.2&&v.alightDone&&v.boardDone&&!v.transfer)v.visitDone=true;
  if(v.visitDone){v.doorOpen=Math.max(0,v.doorOpen-dt*5);if(v.doorOpen<.01)completeVisit(v);}
 }
 function releaseJunctions(){for(const j of junctions)if(j.owner){const v=vehicles.find(a=>a.id===j.owner),d=Math.hypot(v.x-j.x,v.z-j.z);if(d<11)j.entered=true;if(j.entered&&d>14.5){j.owner=null;j.entered=false;}}}
 function respawn(v){for(let attempt=0;attempt<120;attempt++){let route=v.route;if(!v.bus){const e=edges[Math.floor(random()*edges.length)],from=random()<.5?e.a:e.b,to=from===e.a?e.b:e.a;route=laneChunk(from,to,choose(to,from));}const s=route.length*(.15+random()*.70),p=route.point(s);if(junctions.some(j=>Math.hypot(p.x-j.x,p.z-j.z)<18)||!staticClear(v,p)||vehicles.some(b=>b!==v&&polygonsOverlap(vehiclePolygon(v,p),vehiclePolygon(b),1.2)))continue;if(v.transfer)people.cancelTransfer(v.transfer.id,v.stop);for(const j of junctions)if(j.owner===v.id){j.owner=null;j.entered=false;}v.route=route;v.s=s;Object.assign(v,p);v.speed=0;v.state='driving';v.elapsed=0;v.doorOpen=0;v.transfer=null;v.stop=null;v.lastProgress=time;v.progressSinceCheck=0;v.o.position.set(p.x,-.25,p.z);v.o.rotation.y=p.heading;if(v.bus)v.nextStop=transportStops.filter(t=>t.line===v.line).sort((a,b)=>mod(route.stopDistance(a)-s,route.length)-mod(route.stopDistance(b)-s,route.length))[0];stats.respawns++;return true;}return false;}
 function update(dt){if(!Number.isFinite(dt)||dt<0)throw Error('Invalid traffic delta');for(let left=dt;left>1e-8;){const tick=Math.min(.05,left);left-=tick;time+=tick;
   if(time>=nextRequest){nextRequest=time+24;for(const stop of transportStops)people.request(stop);}releaseJunctions();
   for(const v of vehicles){if(time-v.lastProgress>=20)respawn(v);v.lastYield=null;if(v.state==='stopped'){v.speed=0;stopTick(v,tick);setVehiclePose(v.o,{distance:v.distance,doorOpen:v.doorOpen});continue;}
    let desired=v.maxSpeed;const stopGap=v.bus?mod(v.route.stopDistance(v.nextStop)-v.s,v.route.length):Infinity;if(v.bus)desired=Math.min(desired,Math.sqrt(Math.max(0,2*2.6*stopGap)));
    for(const j of junctions){const look=aheadPoint(v,Math.max(3,v.speed*v.speed/5+2)),d=Math.hypot(look.x-j.x,look.z-j.z);if(d>=13||j.owner===v.id)continue;if(j.owner){desired=0;stats.junctionYields++;v.lastYield='junction';}else if(!vehicles.some(b=>b!==v&&Math.hypot(b.x-j.x,b.z-j.z)<10)){j.owner=v.id;j.entered=false;}else{desired=0;v.lastYield='junction';}}
    const pedestrians=people.people();let hazard=null;
    // Brake for a stopped vehicle or pedestrian before the final collision guard.
    const scan=Math.max(4,v.speed*v.speed/5+3);for(let d=1;d<=scan&&!hazard;d+=.6){const p=aheadPoint(v,d);if(vehicles.some(b=>b!==v&&polygonsOverlap(vehiclePolygon(v,p),vehiclePolygon(b),.9)))hazard={type:'following',gap:Math.max(0,d-1.2)};}
    if(hazard){desired=Math.min(desired,Math.sqrt(2*2.5*hazard.gap));v.lastYield=hazard.type;stats[hazard.type==='pedestrian'?'pedestrianYields':'followYields']++;}
    v.speed=desired<v.speed?Math.max(desired,v.speed-3.4*tick):Math.min(desired,v.speed+1.4*tick);const travel=Math.min(v.speed*tick,stopGap,v.bus?Infinity:v.route.length-v.s);let accepted=0;
    while(accepted<travel-1e-8){const move=Math.min(.1,travel-accepted),candidate=aheadPoint(v,accepted+move);if(!staticClear(v,candidate)){stats.staticYields++;v.lastYield='obstacle';break;}if(vehicles.some(b=>b!==v&&polygonsOverlap(vehiclePolygon(v,candidate),vehiclePolygon(b),.07))){stats.collisionYields++;v.lastYield='vehicle';break;}accepted+=move;}
    if(accepted<travel-1e-8)v.speed=0;v.s+=accepted;v.distance+=accepted;v.progressSinceCheck+=accepted;if(v.progressSinceCheck>=.10){v.lastProgress=time;v.progressSinceCheck=0;}Object.assign(v,v.route.point(v.s));if(v.bus)v.s=mod(v.s,v.route.length);else if(v.s>=v.route.length-1e-7){v.visitedNodes.add(v.route.to);const from=v.route.to,to=v.route.next;v.route=laneChunk(from,to,choose(to,from));v.s=0;stats.randomTurns++;Object.assign(v,v.route.point(0));}
    v.o.position.set(v.x,-.25,v.z);v.o.rotation.y=v.heading;if(v.bus&&stopGap-accepted<.025){v.state='stopped';v.stop=v.nextStop;v.elapsed=0;v.speed=0;stats.visits++;}setVehiclePose(v.o,{distance:v.distance,doorOpen:v.doorOpen});
   }
  }}
 function snapshot(){return{time,pedestrianOverlapAllowed:true,respawnAfterSeconds:20,buses:3,cars:10,lines:2,roadSegments:edges.length,junctions:nodes.length,residentPool:20,queueCapacity:1,transitResidentLimit:4,capacity:6,stops:transportStops.map(s=>({id:s.id,line:s.line,queued:people.queue(s).length})),stats:{...stats},routeBlocks,violations:[...violations],vehicles:vehicles.map(v=>({id:v.id,line:v.line,x:v.x,z:v.z,heading:v.heading,s:v.s,speed:v.speed,state:v.state,distance:v.distance,doorOpen:v.doorOpen,passengers:v.riders.length,elapsed:v.elapsed,yield:v.lastYield,visitedNodes:[...v.visitedNodes]}))};}
 function audit(seconds){const start=vehicles.map(v=>v.distance);for(let t=0;t<seconds;t+=1/20){townLife.update(1/20,time);update(1/20);for(let i=0;i<vehicles.length;i++){const v=vehicles[i];if(!staticClear(v,v))violations.push({type:'static',vehicle:v.id});for(let j=i+1;j<vehicles.length;j++)if(polygonsOverlap(vehiclePolygon(v),vehiclePolygon(vehicles[j])))violations.push({type:'vehicle',a:v.id,b:vehicles[j].id});}}return{seconds,travel:vehicles.map((v,i)=>v.distance-start[i]),...snapshot(),people:townLife.snapshot()};}
 return{update,snapshot,audit,verifyRespawn:id=>{const v=vehicles.find(v=>v.id===id);if(!v)return false;v.lastProgress=time-20;const before={x:v.x,z:v.z};update(.05);return{before,after:{x:v.x,z:v.z},respawns:stats.respawns,safe:staticClear(v,v)&&vehicles.every(b=>b===v||!polygonsOverlap(vehiclePolygon(v),vehiclePolygon(b))) };}};
}
