import {evaluateUnlock} from './unlock-rules.js';
import {STATION_LEVELS} from './progression.js';
import {menuCatalog as liveCatalog} from './live-menu-catalog.js';
import {MENU} from './service-menu.js';import {ECONOMY} from './economy.js';import {icon as basicIcon} from './restaurant-service-ui.js';
const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString('tr-TR'),allNodes=new Map();
const extraIcons={table:'M3 10h18v4H3zM6 14v7m12-7v7M9 7V3m6 4V3',shake:'M7 9h10l-1 12H8L7 9m-1 0q0-6 6-6t6 6M12 3V1',juice:'M5 9h14M7 9l1 12h8l1-12M12 9V3h5M5 5a3 3 0 0 1 6 0',book:'M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3V4m9 2v16M6 9h3m6 0h3M6 13h3m6 0h3'};
function icon(name){return extraIcons[name]?`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${extraIcons[name]}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>`:basicIcon(name);}
function add(n){allNodes.set(n.id,{requires:[],sales:[],draft:true,...n});}
add({id:'opening',name:'Dükkânın açılışı',icon:'home',category:'all',level:1,cost:0,description:'İlk kasa, burger ve kola istasyonları ile iki koltuklu ilk masa başlangıçta açıktır.'});
for(const [id,k]of [['burger','burger'],['drink','drink'],['fries','fries'],['pizza','pizza']]){const m=MENU[k];add({id,name:m.name+(id==='drink'?' makinesi':''),icon:k,category:'kitchen',level:m.unlockLevel,cost:m.unlockGold,seconds:m.baseSeconds,price:m.price,xp:m.xp,requires:id==='fries'?['burger']:id==='pizza'?['fries']:['opening'],sales:id==='fries'?[{key:'burger',count:5}]:id==='pizza'?[{key:'burger',count:20},{key:'fries',count:5}]:[],description:id==='pizza'?'Yeni bir ana yemek dalı. Pizza istasyonunun aşçısı olarak Sandy düşünülüyor; karakter modeli ayrıca onay bekliyor.':id==='fries'?'Ana yemeğin yanına eklenebilen ilk yan ürün. Burger dalından ilerleyerek açılır.':id==='drink'?'İçecekler makinede hazırlanır. Nero ve servis komileri bu makineden alır.':'Pişen yemek ortak hazır yemek tezgâhına gelir. Taşıyıcı çalışan ızgaraya gitmez.'});}
add({id:'shake',name:'Milkshake makinesi',icon:'shake',category:'kitchen',level:STATION_LEVELS.shake,cost:1325,seconds:18,requires:['drink','pizza'],sales:[{key:'drink',count:30}],description:'İçecek dalının sonraki istasyonu. Pizza ve başlangıç içecek dalı üzerinden gelişir. Bu bağlantı ve bedel henüz öneridir.'});
add({id:'juice',name:'Meyve suyu makinesi',icon:'juice',category:'kitchen',level:STATION_LEVELS.juice,cost:1675,seconds:20,requires:['shake'],sales:[{key:'shake',count:10}],description:'Milkshake dalını geliştirdikten sonra açılan farklı bir içecek istasyonu. Ekonomi zinciri için inceleme önerisi.'});
add({id:'runner',name:'Servis komisi',icon:'person',category:'staff',level:null,cost:ECONOMY.waiterCost,requires:['opening'],sales:[{key:'served',count:25}],description:'Nero ile aynı görev havuzundan çalışır. Her ürün tek kişiye ayrılır; aynı ürün için iki çalışan yola çıkmaz.'});
add({id:'cash-2',name:'İkinci kasiyer',icon:'cash',category:'staff',level:null,cost:ECONOMY.cashierCosts[0],requires:['runner'],sales:[{key:'served',count:60}],description:'İkinci kasada sipariş kabul eden çalışan. Ek servis kapasitesi oluşmadan kasa sayısını artırmayan önerilen sıra.'});
add({id:'cash-3',name:'Üçüncü kasiyer',icon:'cash',category:'staff',level:null,cost:ECONOMY.cashierCosts[2],requires:['cash-2'],sales:[{key:'served',count:160}],description:'Üçüncü kasa için ek çalışan. Önceki kapasite yatırımı ve satış hedefi üzerinden açılır.'});
for(let i=1;i<=20;i++)add({id:'table-'+i,name:i===1?'İlk masa':i+'. masa',icon:'table',category:'dining',level:null,cost:i===1?0:24*i*i,requires:[i===1?'opening':'table-'+(i-1)],description:i===1?'İki bağımsız koltuk başlangıçta açıktır. Birlikte sipariş vermeyen müşteriler aynı masayı paylaşabilir.':`Satın alınan ${i}. masa. Yerini restorandaki + işaretlerinden seçersin; fiyat satın alma sırasına bağlıdır. Bedel formülü henüz denge önerisidir.`});
add({id:'cleaner',name:'Temizlik garsonu',icon:'clean',category:'dining',level:null,cost:60,requires:['table-1'],description:'Boşalan kirli masaları temizler. Yeni müşteri temizlenmeden oturamaz. Silme süresi 5 saniyedir; iki geliştirmeyle 3,5 ve 2 saniyeye düşer.'});
const recipes=[...liveCatalog.byId.values()].map(p=>({model:p.id,name:p.name,station:p.station,station_level:p.stationLevel,level:p.level,unlock_gold:p.unlockGold,seconds:p.seconds,sale_gold:p.saleGold,sale_xp:p.saleXP,previous_recipe:p.previousRecipe,new_station:p.opensStation}));
const familyNames={burger:'Burgerler',soda:'Gazlı içecekler',fryer:'Kızartmalar',oven:'Fırın ürünleri',shake:'Milkshake',juice:'Meyve suları','hot-drink':'Sıcak içecekler',icecream:'Dondurmalar',hotdog:'Hot dog','cold-prep':'Soğuk hazırlık',dessert:'Tatlılar','soup-pasta-extra':'Çorba ve makarna','manual-review':'Karar bekleyen tarifler'};
const familyKeys={burger:'burger',soda:'drink',fryer:'fries',oven:'pizza',shake:'shake',juice:'juice','hot-drink':'family-hot-drink',icecream:'family-icecream',hotdog:'family-hotdog','cold-prep':'family-cold-prep',dessert:'family-dessert','soup-pasta-extra':'family-soup','manual-review':'family-review'};
const familyParent={'hot-drink':'drink',icecream:'shake',hotdog:'fries','cold-prep':'juice',dessert:'pizza','soup-pasta-extra':'pizza'};
const startingModels={'food-1':'burger','food-96':'drink','food-32':'fries','food-44':'pizza'},familyRecipes={};
for(const [family,name]of Object.entries(familyNames)){const records=recipes.filter(r=>r.station===family).sort((a,b)=>Number(Boolean(startingModels[b.model]))-Number(Boolean(startingModels[a.model]))||(a.level??999)-(b.level??999));if(!records.length)continue;familyRecipes[family]=records.map(r=>'recipe-'+r.model);const key=familyKeys[family];if(!allNodes.has(key)){const first=records[0];add({id:key,name:name+' istasyonu',icon:'book',category:family==='manual-review'?'recipes':'kitchen',level:family==='manual-review'?null:STATION_LEVELS[family],cost:first?.unlock_gold,requires:['opening'],decisionRequired:family==='manual-review',description:'Bu istasyonun açılma şartları ve araştırma ilişkisi taslak. Nihai bağlantı ve fiyatlar birlikte kararlaştırılacak.'});}
 records.forEach((r,i)=>add({id:'recipe-'+r.model,name:r.name,icon:family==='burger'?'burger':family==='fryer'?'fries':family==='oven'?'pizza':family==='soda'?'drink':'book',category:'recipes',family,stationLevel:r.station_level,model:r.model,level:r.level,cost:r.new_station?0:r.unlock_gold,seconds:r.seconds,price:r.sale_gold,xp:r.sale_xp,requires:[r.previous_recipe?'recipe-'+r.previous_recipe:key],alias:r.new_station?key:(startingModels[r.model]||null),decisionRequired:r.level===null,description:'İstasyon içindeki tarif sırası için öneri. Önceki tarif, oyuncu seviyesi ve altın birlikte koşul oluşturur. Gerçek tarif modelini stüdyoda inceleyebilirsin.'}));
 const option=document.createElement('option');option.value=family;option.textContent=name+' · '+records.length;$('family').append(option);
}
for(const n of allNodes.values())if(n.category==='kitchen'||n.category==='staff'){n.sales=[];n.requires=['opening'];}allNodes.get('pizza').description='Fırın hattında Sandy çalışır. İlk pizza tarifi makine bedeline dahildir.';allNodes.get('shake').description='Ayrı içecek hattı. İlk tarif makine bedeline dahildir.';allNodes.get('juice').description='Meyve suyu hattı. İlk tarif makine bedeline dahildir.';
const scenarios={start:{level:1,gold:24,sales:{burger:0,drink:0,fries:0,served:0},unlocked:['opening','burger','drink','table-1']},early:{level:5,gold:640,sales:{burger:18,drink:12,fries:0,served:18},unlocked:['opening','burger','drink','table-1']},grown:{level:27,gold:6400,sales:{burger:100,drink:68,fries:24,pizza:15,shake:8,served:110},unlocked:['opening','burger','drink','fries','pizza','shake','runner','cash-2','table-1','table-2','cleaner']}};
let profile,unlocked,selected='fries',filter='all',positions=new Map(),graphWidth=1060,graphHeight=870,zoom=.8,pan={x:0,y:0},drag=null;
function loadScenario(key){profile=structuredClone(scenarios[key]);unlocked=new Set(profile.unlocked);}
function has(id){const n=allNodes.get(id);return unlocked.has(id)||Boolean(n?.alias&&unlocked.has(n.alias));}
function requiresLevel(n){return n.category==='kitchen'||n.category==='recipes';}
function conditions(n){return[...(requiresLevel(n)?[{label:'Oyuncu seviyesi '+(n.level??'karar bekliyor'),met:n.level!==null&&profile.level>=n.level,detail:'Mevcut seviyen: '+profile.level}]:[]),...n.requires.map(id=>({label:allNodes.get(id).name,met:has(id),detail:'Önce açılması gerekiyor',id})),...n.sales.map(t=>({label:(t.key==='served'?'Sipariş tamamla':(allNodes.get(t.key)?.name||t.key)+' sat')+' · '+t.count,met:(profile.sales[t.key]||0)>=t.count,progress:profile.sales[t.key]||0,target:t.count})),{label:n.cost===null?'Altın bedeli kararlaştırılacak':fmt(n.cost)+' altın',met:n.cost!==null&&profile.gold>=n.cost,detail:'Cüzdanında '+fmt(profile.gold)+' altın'}];}
function state(n){if(has(n.id))return'unlocked';return evaluateUnlock({level:requiresLevel(n)?n.level:null,cost:n.cost,requires:n.requires,sales:n.sales,decisionRequired:n.decisionRequired},{level:profile.level,gold:profile.gold,sales:profile.sales,has}).allowed?'ready':'locked';}
function visible(){if(filter==='levels'){const from=Number($('level-range').value);return recipes.filter(r=>r.level>=from&&r.level<from+10).sort((a,b)=>a.level-b.level).map(r=>'recipe-'+r.model);}if(filter==='recipes')return[familyKeys[$('family').value],...familyRecipes[$('family').value]];if(filter==='kitchen')return['opening',...[...allNodes.values()].filter(n=>n.category==='kitchen').map(n=>n.id)];if(filter==='dining')return['opening',...Array.from({length:20},(_,i)=>'table-'+(i+1)),'cleaner'];const overview=['opening','burger','fries','pizza','drink','shake','juice','runner','cash-2','cash-3','table-1','table-2','cleaner'];return overview.filter(id=>filter==='all'||id==='opening'||allNodes.get(id).category===filter);}
function layout(ids){positions.clear();if(filter==='all'){const rows=[['burger','fries','pizza'],['drink','shake','juice'],['runner','cash-2','cash-3'],['table-1','table-2','cleaner']];positions.set('opening',{x:25,y:355});rows.forEach((row,r)=>row.forEach((id,c)=>positions.set(id,{x:285+c*250,y:20+r*210})));graphWidth=1040;graphHeight=815;}else{const cols=filter==='recipes'?4:filter==='dining'?5:3;ids.forEach((id,i)=>positions.set(id,{x:25+(i%cols)*250,y:25+Math.floor(i/cols)*205}));graphWidth=cols*250+30;graphHeight=Math.ceil(ids.length/cols)*205+25;}}
function transform(){const stage=$('stage');stage.style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$('zoom-label').textContent=Math.round(zoom*100)+'%';}
function fit(){const v=$('viewport');zoom=Math.max(.30,Math.min(1,(v.clientWidth-36)/graphWidth,(v.clientHeight-24)/graphHeight));pan={x:(v.clientWidth-graphWidth*zoom)/2,y:(v.clientHeight-graphHeight*zoom)/2};transform();}
function connect(from,to,kind){const a=positions.get(from),b=positions.get(to);if(!a||!b)return;const sx=a.x+198,sy=a.y+73,tx=b.x,ty=b.y+73;let d;if(tx>sx+260&&Math.abs(ty-sy)<1){const gap=a.y-22;d=`M${sx} ${sy} L${sx+16} ${sy} Q${sx+30} ${sy} ${sx+30} ${sy-16} L${sx+30} ${gap+14} Q${sx+30} ${gap} ${sx+44} ${gap} L${tx-32} ${gap} Q${tx-16} ${gap} ${tx-16} ${gap+16} L${tx-16} ${ty-14} Q${tx-16} ${ty} ${tx} ${ty}`;}else if(tx>sx){const mid=(sx+tx)/2;d=`M${sx} ${sy} C${mid} ${sy} ${mid} ${ty} ${tx} ${ty}`;}else{const gy=b.y-24;d=`M${sx} ${sy} L${sx+20} ${sy} L${sx+20} ${gy} L${tx-18} ${gy} L${tx-18} ${ty} L${tx} ${ty}`;}const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('class','edge '+kind);$('edges').append(p);}
function draw(recenter=false){document.querySelector('.map-caption span:first-child').textContent=filter==='levels'?'SEVİYE YOLU · SIRALI ÜRÜNLER':'GELİŞTİRME AĞACI';const ids=visible();layout(ids);$('nodes').replaceChildren();$('edges').replaceChildren();$('stage').style.width=graphWidth+'px';$('stage').style.height=graphHeight+'px';$('edges').setAttribute('width',graphWidth);$('edges').setAttribute('height',graphHeight);for(const id of ids){const n=allNodes.get(id),p=positions.get(id),s=state(n),button=document.createElement('button');button.className='node '+s+(id===selected?' selected':'');button.style.left=p.x+'px';button.style.top=p.y+'px';button.dataset.id=id;button.setAttribute('aria-pressed',String(id===selected));button.innerHTML=`<span class="state-badge">${s==='unlocked'?'✓':s==='ready'?'Açılabilir':'Kilitli'}</span><span class="node-icon">${icon(n.icon)}</span><strong></strong><span class="meta"><span>${requiresLevel(n)?n.level===null?'Karar bekliyor':'Sv. '+n.level:'Seviye şartı yok'}</span><span>${s==='unlocked'?'Açıldı':n.cost===null?'—':fmt(n.cost)+' altın'}</span></span>`;button.querySelector('strong').textContent=n.name;button.addEventListener('click',()=>{if(drag?.moved)return;selected=id;draw(false);});$('nodes').append(button);for(const parent of n.requires)connect(parent,id,id===selected?'selected':has(parent)?'unlocked':'');}
 $('gold').textContent=fmt(profile.gold);$('level').textContent='Sv. '+profile.level;details();if(recenter)fit();else transform();}
function details(){const n=allNodes.get(selected),s=state(n),d=$('details');d.replaceChildren();const kind=document.createElement('span');kind.className='detail-kind';kind.textContent=n.category==='recipes'?'TARİF':n.category==='staff'?'EKİP':n.category==='dining'?'MASA & SERVİS':'MUTFAK GELİŞİMİ';const hero=document.createElement('div');hero.className='detail-hero';hero.innerHTML=icon(n.icon);const h=document.createElement('h2');h.textContent=n.name;const desc=document.createElement('p');desc.className='description';desc.textContent=n.description;d.append(kind,hero,h,desc);if(n.seconds){const stats=document.createElement('div');stats.className='detail-stats';stats.innerHTML=`<span>${n.seconds} sn üretim</span>${n.price?`<span>${n.price} altın / satış</span>`:''}${n.xp?`<span>${n.xp} XP</span>`:''}`;d.append(stats);}const price=document.createElement('div');price.className='detail-price';price.innerHTML=`<span>Açılış bedeli · <b>taslak</b></span><strong>${s==='unlocked'?'Açıldı':n.cost===null?'Karar bekliyor':fmt(n.cost)+' <small>altın</small>'}</strong>`;d.append(price);const title=document.createElement('span');title.className='conditions-title';title.textContent='AÇILMA KOŞULLARI';d.append(title);
 for(const c of conditions(n)){const row=document.createElement('div');row.className='condition'+(c.met||s==='unlocked'?' met':'');row.innerHTML=`<i>${c.met||s==='unlocked'?'✓':'○'}</i>`;const body=document.createElement('div');body.textContent=c.label;if(c.progress!==undefined){const small=document.createElement('small');small.textContent=Math.min(c.progress,c.target)+' / '+c.target;const progress=document.createElement('progress');progress.max=c.target;progress.value=c.progress;body.append(small,progress);}else if(c.detail){const small=document.createElement('small');small.textContent=c.detail;body.append(small);}row.append(body);d.append(row);}
 const button=document.createElement('button');button.className='action';button.textContent=s==='unlocked'?'Bu gelişme açık':s==='ready'?'Prototipte açmayı dene':'Önce koşulları tamamla';button.disabled=s!=='ready';button.addEventListener('click',()=>{if(state(n)!=='ready')return;profile.gold-=n.cost;unlocked.add(n.id);draw();toast(n.name+' açıldı · yalnızca önizleme');});d.append(button);const note=document.createElement('p');note.className='prototype-note';note.textContent='Bağlantılar, satış hedefleri ve bedeller öneridir. Bu deneme gerçek oyuna uygulanmaz.';d.append(note);if(n.model){const a=document.createElement('a');a.href='studio.html?asset='+n.model;a.target='_blank';a.textContent='Gerçek 3B tarif modelini incele ↗';a.style.cssText='display:block;text-align:center;color:#538b90;font-size:11px;margin-top:14px';d.append(a);}}
let toastTimer;function toast(text){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.append(t);clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.remove(),2500);}
for(const b of document.querySelectorAll('[data-filter]'))b.addEventListener('click',()=>{filter=b.dataset.filter;for(const btn of document.querySelectorAll('[data-filter]'))btn.classList.toggle('active',btn===b);$('family-wrap').hidden=filter!=='recipes';$('level-wrap').hidden=filter!=='levels';selected=filter==='levels'?visible()[0]:filter==='recipes'?familyRecipes[$('family').value][0]:filter==='dining'?'table-2':filter==='staff'?'runner':filter==='kitchen'?'fries':'fries';draw(true);});
for(let from=1;from<=141;from+=10){const option=document.createElement('option');option.value=from;option.textContent=from+'–'+Math.min(141,from+9);$('level-range').append(option);}
$('level-range').addEventListener('change',()=>{selected=visible()[0];draw(true);});
$('family').addEventListener('change',()=>{selected=familyRecipes[$('family').value][0];draw(true);});$('scenario').addEventListener('change',()=>{loadScenario($('scenario').value);draw();});$('reset').addEventListener('click',()=>{loadScenario($('scenario').value);draw();toast('Önizleme sıfırlandı');});$('fit').addEventListener('click',fit);
function setZoom(value){const v=$('viewport'),next=Math.max(.30,Math.min(1.6,value)),cx=v.clientWidth/2,cy=v.clientHeight/2;pan.x=cx-(cx-pan.x)*next/zoom;pan.y=cy-(cy-pan.y)*next/zoom;zoom=next;transform();}
$('zoom-in').addEventListener('click',()=>setZoom(zoom*1.15));$('zoom-out').addEventListener('click',()=>setZoom(zoom/1.15));const v=$('viewport');v.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.001));},{passive:false});v.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,panX:pan.x,panY:pan.y,moved:false};});v.addEventListener('pointermove',e=>{if(!drag||!(e.buttons&1))return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5){drag.moved=true;pan={x:drag.panX+e.clientX-drag.x,y:drag.panY+e.clientY-drag.y};v.style.cursor='grabbing';transform();}});window.addEventListener('pointerup',()=>{v.style.cursor='grab';setTimeout(()=>drag=null,0);});window.addEventListener('resize',fit);
loadScenario('early');await document.fonts.ready;draw(true);
function validate(){const seen=new Set(),active=new Set();function visit(id){if(active.has(id))throw Error('Dependency cycle: '+id);if(seen.has(id))return;const n=allNodes.get(id);if(!n)throw Error('Missing prerequisite: '+id);active.add(id);for(const p of n.requires)visit(p);active.delete(id);seen.add(id);}for(const id of allNodes.keys())visit(id);return{nodes:allNodes.size,recipes:recipes.length,acyclic:true};}
window.__unlockTree={ready:true,validate,snapshot:()=>({profile:{level:profile.level,gold:profile.gold},selected,filter,zoom,unlocked:[...unlocked],visible:visible(),state:Object.fromEntries([...allNodes].map(([id,n])=>[id,state(n)]))})};validate();
